### ISSUE TITLE
Request: Exclusive FullScreen Option

### ISSUE THREAD

**Issue by PKite** [34736384/genshin-fps-unlock#1]
First of all, thank you so much for this fps unlocker.

I normally run the game in exclusive fullscreen mode using a command line argument.  I didn't know how to do this with the unlocker so modified a copy of the code.

Here is example code I used if you want to add a fullscreen toggle to the config.
`
    std::string ProcessPathWArgs = "\"" + ProcessPath + "\" -ArgumentList -window-mode exclusive";
    size_t len = ProcessPathWArgs.length();
    LPSTR str2 = new char[len + 1];
    ProcessPathWArgs._Copy_s(str2, len, len);
    str2[len] = '\0';
    if (!CreateProcessA(nullptr, str2, nullptr, nullptr, FALSE, 0, nullptr, nullptr, &si, &pi))
`

**Comment by 34736384** [comment]
I've added command line forwarding in the newest release, just launcher the unlocker with your desired command line options. It'll launch the game with the options you supplied to the unlocker

**Comment by PKite** [comment]
I tried it out and it works. Thank you.
I use the following powershell script to start it in exclusive fullscreen mode now.
Start-Process -filepath "unlockfps.exe" -ArgumentList "-window-mode exclusive"

**Comment by DerPon3** [comment]
> I tried it out and it works. Thank you. I use the following powershell script to start it in exclusive fullscreen mode now. Start-Process -filepath "unlockfps.exe" -ArgumentList "-window-mode exclusive"

can you explain me how to do this?

**Comment by xknat** [comment]
Hey there.

Maybe this workaround of mine helps?:
I use the Alt tab in combination with https://github.com/Codeusa/Borderless-Gaming
