### ISSUE TITLE
解锁帧数后打散兵周本，硬吃散兵大招不会死

### ISSUE THREAD

**Issue by lujiecan** [34736384/genshin-fps-unlock#102]
我在刷成就「生灭去来」时发现的，要被散兵第二阶段破盾后那个大球打死角色才能获得这个成就。硬吃技能结果无伤，试了几次都这样。关闭解锁器后再试就可以了。

**Comment by lujiecan** [comment]
今天去测试了两次，官方不知道啥时候修复了。

**Comment by Aqirito** [comment]
any update on this?
