### ISSUE TITLE
Kokomi FPS Drop

### ISSUE THREAD

**Issue by Mijinion** [34736384/genshin-fps-unlock#104]
After the recent patch 3.3, it seems like running the game past 60 fps will tank the fps whenever you use Kokomi's normal attack. It doesn't seem like other characters are affected by this so far. Any idea what could be causing the issue? I've tried it with 61 fps and it still tanks the fps. Putting back to 60 makes it stable again.

**Comment by iSpeedHD** [comment]
I just came here to say that I have the same exact problem. Did they link Kokomi's attack animation to the engine FPS? This is very odd.

**Comment by gIac1er** [comment]
Same problem here, seems like it's the effect of kokomi's auto attack. Auto attacking with the lowest camera angle seems to not have any frame drops. 

3.3之后只要是60帧以上心海aa严重掉帧，看样子是aa的视效造成的问题

**Comment by Pots4342** [comment]
Having the same problem as well

**Comment by heen14** [comment]
Same problem

**Comment by 34736384** [comment]
Please note that all the unlocker does is change a number inside the game memory. While you guys are free to discuss any problems encountered with higher fps. Just remember that resulting issues from higher fps is usually a game bug and I'm not here to investigate them.

**Comment by logib** [comment]
came here to mention this as well. I did raise the issue with mihoyo CS and provided a video (without FPS display or mention of the mod) to demonstrate it. Unfortunately the fact that it depends on higher frame rate might make it difficult for them to track down. However, iphone does have 120 FPS as well now so perhaps they may be experiencing the issue too? If anyone here also owns an iPhone with 120 FPS support you should try to get footage of the issue on there to report to Mihoyo. Probably only way it gets fixed

**Comment by amnes7y** [comment]
@logib 
I reported it. I got it happening on ipad and iphone that supports 120 FPS.

**Comment by cokebar** [comment]
Tested on iPad Pro M1 with 120FPS, same issue. So this is a bug of the game itself. Hope mihoyo fix it soon.

**Comment by BlankIsDumb** [comment]
And here i thought it was my pc having a skill issue, turns out everyone got the same issue

**Comment by eeVaderqtf** [comment]
this is happening to me too,please fix it

**Comment by Kahlrim** [comment]
I can confirm as of 3.4 the issue is resolved.

**Comment by Kahlrim** [comment]
I can confirm as of 3.4 the issue is resolved.
