### ISSUE TITLE
[BUG] Minimize to tray: Win/Alt+Tab

### ISSUE THREAD

**Issue by Trixlight** [34736384/genshin-fps-unlock#107]
Even with the option "Minimize to tray", the program is still displayed in the Win/Alt+Tab dialogue box.
![2022-12-29_06-12-27](https://user-images.githubusercontent.com/33410668/209890948-13eb0bfe-6558-4e29-ae4b-94be1a88c04c.png)

**Comment by MohamadSabree8** [comment]
A workaround is to use Windows+Tab to make a new desktop then moving it there.

**Comment by Trixlight** [comment]
Seems to be fixed in e679d9f

**Comment by Trixlight** [comment]
This issue is back in https://github.com/34736384/genshin-fps-unlock/commit/07e9c9449847cde4a5347ec343b7ef69b07cc3e3

**Comment by NBOOK** [comment]
Can confirm that the bug exist in the latest (v2.1.1) version.

**Comment by 34736384** [comment]
fixed in latest build
