### ISSUE TITLE
Reshade injection

### ISSUE THREAD

**Issue by Atthorpe** [34736384/genshin-fps-unlock#11]
Sorry to make an issue but i was confused on how to get reshade to work properly, ive tried putting the reshade dlls into same folder as unlocker and also tried renaming the dlls but they dont seem to work, i tried putting them in the normal game folder and and it loads up but yeah i get the file check error, soo im not sure what im missing. any help would be appreciated, thanks for this amazing fps improvement!

**Comment by Atthorpe** [comment]
disregard, i was being stupid and was launching game with powershell trying to use exclusive fullscreen mode and it wasnt starting unlocker as admin and the reshade is requiring admin, running unlocker as admin normally without powershell causes reshade to load

**Comment by 34736384** [comment]
If you want exclusive fullscreen you can just pass the command line arguments to the unlocker, the unlocker will pass it to the game
