### ISSUE TITLE
这个开了怎么关掉啊，我有点怂

### ISSUE THREAD

**Issue by 2023899320** [34736384/genshin-fps-unlock#111]

**Comment by 34736384** [comment]
https://lab.isaaclin.cn/lmbtfy/?%E5%A6%82%E4%BD%95%E5%85%B3%E9%97%AD%E5%90%8E%E5%8F%B0%E8%BF%9B%E7%A8%8B
https://letmegooglethat.com/?q=%E5%A6%82%E4%BD%95%E5%85%B3%E9%97%AD%E5%90%8E%E5%8F%B0%E8%BF%9B%E7%A8%8B
