### ISSUE TITLE
Custom Resolution

### ISSUE THREAD

**Issue by catches** [34736384/genshin-fps-unlock#112]
yo so i have a 1080p 165hz monitor, does setting the custom resolution to like 3840 x 2160 upscale the game to 4k? will it look better, or is it not gonna make a difference?

**Comment by AkuraIzumu** [comment]
If buying 1 burger makes you full, then should you buy 3 burgers? No, you can only eat 1 burger and cannot stuff the 2nd and the 3rd. Same concept. You can try rendering at 4k but your monitor only shows 1080p.

**Comment by AkuraIzumu** [comment]
Genshin isnt a competitive game so capping your game at the refresh rate of your monitor would be the best choice. If you want the game to look better simply put all the settings as high and lowering your rendering resolution a little bit like to .9 or something so the game can utilize fsr and not kill your gpu.

**Comment by 34736384** [comment]
If you're on nvidia, use DSR instead

**Comment by rickk23** [comment]
Totally off-topic, commenting here because I don't know how to contact the developer any other way
I mostly use this tool to set custom resolution in genshin
since honkai star rail coming out and beta is out
wanted to ask if similar tool can be made for it

**Comment by Transcan** [comment]
What OP wants can be done 

> yo so i have a 1080p 165hz monitor, does setting the custom resolution to like 3840 x 2160 upscale the game to 4k? will it look better, or is it not gonna make a difference?

That can be achieve with the setting "Render Resolution" inside the game. Use the max 1.5 and it will look clearer.
I doubt you will get better image quality than that with external methods.

You can also try to use FSR2 for antialiasing, but it sharpens the image too much for my taste, I personally use SMAA.
