### ISSUE TITLE
Sound issues

### ISSUE THREAD

**Issue by G2Poti** [34736384/genshin-fps-unlock#113]
Most sfx - like footsteps, voicelines, abilities, in game music and the sound effect of closing the escape menu (opening it is loud and clear) - are either very quiet or completely inaudible, while others - like the music in the pre-game launcher, and the sound effect of changing settings and browsing the options menu - work perfectly. All audio is set to 10 (max) in the settings so that shouldn't be the problem, but I've tried multiple audio levels and nothing's changed.

OS: Windows 11 Home 22H2
CPU: Ryzen 7 5700x
GPU: Radeon RX 6700 XT
Graphics driver: Adrenaline 22.11.2 (Latest)

**Comment by G2Poti** [comment]
Never mind, restarted my pc and now everything works just fine.

**Comment by wtdcode** [comment]
Having the same issue but restarting doesn't help.
