### ISSUE TITLE
[BUG] Hoyoverse Login Puzzle-Piece Captcha Laggy/Not Working

### ISSUE THREAD

**Issue by lattemango** [34736384/genshin-fps-unlock#117]
Title says it all. Don't know if it can be replicated on other systems or not, though.

**Comment by PERCENTisMODULo** [comment]
I've noticed that this happens for some other UI elements inside Genshin Impact as well, such as the in-game browser for patch notes and things like that.

**Comment by dromzeh** [comment]
> I've noticed that this happens for some other UI elements inside Genshin Impact as well, such as the in-game browser for patch notes and things like that.

I've never had this issue at all. I've tried but I'm unable to replicate this.

**Comment by lattemango** [comment]
> > I've noticed that this happens for some other UI elements inside Genshin Impact as well, such as the in-game browser for patch notes and things like that.
> 
> I've never had this issue at all. I've tried but I'm unable to replicate this.

It looks like it has stopped for me. No clue what could have caused it or why it's not happening anymore. Closing this as "cant repro".
