### ISSUE TITLE
Message for the Dev

### ISSUE THREAD

**Issue by ArkhXI** [34736384/genshin-fps-unlock#12]
Sorry for posting this and wasting your time.
I want to know if as today you are still using this and are still undetected by the CCP kernel spyware :)

I dont want to risk losing my day 1 account but at the same time i despise the fact that i have a 21:9 144hz gsync awesome screen and im stuck to 60fps.

Is the gameplay/animation tied to the framerate in anyway? And would it work at lets say, 120 or 144fps whit gsync enabled?

Thanks a lot!

**Comment by 34736384** [comment]
**Is the gameplay/animation tied to the framerate in anyway?**
Nope

**And would it work at lets say, 120 or 144fps whit gsync enabled?**
At the current state of the game, it is very hard to maintain a stable 120 at all time

**Comment by ArkhXI** [comment]
Did some test, whit an RTX 3080 and a Ryzen 5800x im able to run the game at 140 fps @3440x1440.
This + nvcp filter + nvidia freestyle makes an HUGE difference.

**Comment by r0wger** [comment]
@ArkhXI what is the nvcp filter?
