### ISSUE TITLE
causing high ping confirm...

### ISSUE THREAD

**Issue by GHN93** [34736384/genshin-fps-unlock#120]
with fps unlock : 330~400ms

without fps unlock : 80~90ms (peak 120ms)

**Comment by Transcan** [comment]
Not in my system...

**Comment by BlueStarBRS** [comment]
cant confirm it.

Redownload the game and the unlocker and clear the data about the unlocker also restart your router and let him off for 10 minutes i can tell you sometimes your ping is shit but on all other stuff good but not in Genschin a router restart can help to fix this
