### ISSUE TITLE
2.0 doesn't work anymore

### ISSUE THREAD

**Issue by lunimater** [34736384/genshin-fps-unlock#123]
Version 2.0 stopped working with the 3.6 game update. Old versions are still working tho. For example, v1.4.2 is still working with the new version.

The problem happens when the Genshin logo shows up, the game just froze and close itself.

**Comment by logib** [comment]
2.0 works completely fine for me. At first it didn't work because my launcher installed the game to the wrong drive so fps unlocker was pointing towards an old version. Make sure that's not the issue.

**Comment by DAOWAce** [comment]
Still working just fine here with no changes whatsoever.

**Comment by BlueStarBRS** [comment]
cant recommend outdated versions if you want to keep your account.
just dont do that ok ?
