### ISSUE TITLE
Possible workaround for FPS drop in dialogue

### ISSUE THREAD

**Issue by hatsune-miku** [34736384/genshin-fps-unlock#125]
Problem: FPS drops significantly (~10) in dialogue or Paimon menu. If the game window is not active, the problem disappears.

My current working solution: Disable `Auto Disable Vsync` in the unlocker

I am playing in 3440x1440 with 3060laptop and 5800H

---

问题：对话或者进入派蒙菜单时，帧率下降到10左右。如果游戏窗口是后台，则问题消失。

我的解决方法：在帧率解锁器里关闭 `Auto Disable Vsync`

**Comment by 34736384** [comment]
You are not missing out on anything if 'Auto Disable Vsync' is turned off. You can do the same by going into the game settings and turning on/off vsync. On the other hand, any issues encountered with higher fps are an issue with the game. Not the unlocker itself. All the unlocker does is change a number in memory
