### ISSUE TITLE
Opening the "Notices", "Version Highlights" or "Survey" windows can cause soft locks

### ISSUE THREAD

**Issue by Clavus** [34736384/genshin-fps-unlock#126]
When I open either the "Notices", "Version Highlights" or "Survey" windows, they often don't render properly / partially or don't show up altogether and simply softlock my game and I can no longer navigate back.

I've tried a few combinations of settings, unchecking "auto disable vsync" or changing the fullscreen mode to "exclusive", but that didn't solve the problem.

I'm playing at 3440x1440 at 160hz. Issue also appears at 120hz. When I launch with 60hz (via the unlocker still) the windows do work as expected.

**Comment by 34736384** [comment]
https://github.com/34736384/genshin-fps-unlock/issues/104#issuecomment-1342992315

**Comment by Clavus** [comment]
Okay, it'd be nice if someone kept track of the "known issues" somewhere though.
