### ISSUE TITLE
Bluescreen if enabled Kernel-mode Hardware-enforced Stack Protection on windows 11

### ISSUE THREAD

**Issue by SyouShiro** [34736384/genshin-fps-unlock#127]
Using v2.0 with the latest Genshin impact version.
Instant bluescreen on launch.

**Comment by Tachyonwing** [comment]
I also got this error.

**Comment by psychonz** [comment]
Yes, same here.

**Comment by lagopodous** [comment]
Not related to unlock fps. The stack protection is interfering with hoyo's anti-cheat module and causes BSOD.

**Comment by 34736384** [comment]
This setting targets kernel code aka kernel-level drivers (.sys)
Unlocker does not load any drivers
