### ISSUE TITLE
"Abornal data. Please uninstall the game and download it from the official channel"

### ISSUE THREAD

**Issue by SirSaber** [34736384/genshin-fps-unlock#129]
Like the title says, I've installed, ran this program and the moment I hit "Play" I get :

"Abornal data. Please uninstall the game and download it from the official channel"

Had to reinstall the game afterwards.

**Comment by dromzeh** [comment]
This is normal and can happen sometimes - it isn't always related to the FPS unlocker, more enough corrupt files.

**Comment by SirSaber** [comment]
I did indeed made a folder and put the file inside as was instructed in the YT video I've watched that lead me to this post.
