### ISSUE TITLE
Doesn't work with 3.7.0

### ISSUE THREAD

**Issue by DenSwitch** [34736384/genshin-fps-unlock#137]
hi. it doesn't work with the new update 3.7.0. please update it :) 
![image](https://github.com/34736384/genshin-fps-unlock/assets/47791189/b90ff39b-80ac-417d-8644-8e4ce5e63a3d)

**Comment by pocasolta01** [comment]
yeah same problem here, pls fix i cant play this game at 60fps after using this godly fps unlocker

**Comment by lunimater** [comment]
Same here.
![image](https://github.com/34736384/genshin-fps-unlock/assets/114543945/ad9e19a5-1959-475b-9e00-ae9566e0044a)

**Comment by jamespmnd** [comment]
+1 on this. Hope tool can be updated for 3.7 and beyond

**Comment by WenchenWang** [comment]
same cant use it

**Comment by yangtryyds** [comment]
same problem

**Comment by GatoTristeY** [comment]
Same here. It's too awful playing again with 60 fps

**Comment by dioni04** [comment]
same here

**Comment by Qepz** [comment]
Same here

**Comment by xzf0509** [comment]
same here

**Comment by RyanDVasconcelos** [comment]
same here

**Comment by hayzar-s** [comment]
same here please fix IT thank you

**Comment by theloraxofdeath** [comment]
A dark day for gamers...

**Comment by GraveUypo** [comment]
Yep, doesn't work anymore. Gross how they would go out of their way to sabotage something that literally doesn't hurt anyone in any way. If there's no way around this, i'm quitting this game early.

**Comment by cybik** [comment]
Finally they patched it.

**Comment by markuskusxyren** [comment]
its over

**Comment by hotpot1026** [comment]
60 FPS I really can't :(

**Comment by nofuma99** [comment]
this wasn't patched, just some internal changes, probably some semantic shit. Just needs the new memory pattern to scan for. [Here's the issue](https://github.com/34736384/genshin-fps-unlock/blob/main/unlockfps_clr/Unmanaged.cpp#L194-L196C65)

**Comment by t0xic0der** [comment]
Does not work for me as well :(

![image](https://github.com/34736384/genshin-fps-unlock/assets/49605954/60d7c52b-abc5-4ca3-8d43-130d8b558bd8)

**Comment by twiGGyAJOfficial** [comment]
Same here. I hope an update will be released soon. My eyes can't handle 60FPS anymore.. they're bleeding..

**Comment by MisakaMikoto2333** [comment]
Meet to

**Comment by UnlishedTen83** [comment]
I really hope someone comes in and finds the new memory patterns to fix it.

**Comment by 34736384** [comment]
calm the fuck down, gonna update it soon

**Comment by kuznetsov-ns** [comment]
> calm the fuck down, gonna update it soon

hurrah
I look forward to it
ty

**Comment by UnlishedTen83** [comment]
> calm the fuck down, gonna update it soon

Based

**Comment by LouisD69** [comment]
> calm the fuck down, gonna update it soon

goated dev

**Comment by SalenGency** [comment]
W dev. Unplayable with 60fps, glad someone actually made this and fixes it ❤

**Comment by narnian19** [comment]
i love <3

**Comment by rlawjdtn8890** [comment]
> 진정해, 곧 업데이트할게

기대 할게요 감사

**Comment by 34736384** [comment]
updated, download at [Release](https://github.com/34736384/genshin-fps-unlock/releases)

**Comment by hotpot1026** [comment]
> updated, download at [Release](https://github.com/34736384/genshin-fps-unlock/releases)

<3

**Comment by narnian19** [comment]
> actualizado, descargar en [Release](https://github.com/34736384/genshin-fps-unlock/releases)

Hero <3

**Comment by MisakaMikoto2333** [comment]
> updated, download at [Release](https://github.com/34736384/genshin-fps-unlock/releases)

Cool

**Comment by rlawjdtn8890** [comment]
> > [업데이트됨, 취소](https://github.com/34736384/genshin-fps-unlock/releases) 시 다운로드[](https://github.com/34736384/genshin-fps-unlock/releases)
> 
> 다시

실행이 안됨

**Comment by kuznetsov-ns** [comment]
> > > [업데이트됨, 취소](https://github.com/34736384/genshin-fps-unlock/releases) 시 다운로드
> > 
> > 
> > 다시
> 
> 실행이 안됨

delete json config and run again

**Comment by rlawjdtn8890** [comment]
> json 구성

방법을 몰라요

**Comment by kuznetsov-ns** [comment]
> > json 구성
> 
> 방법을 몰라요

in directory where .exe file placed delete "fps_config.json"
and Auto Close function actually doesn't work that's why on the next start it again locks on 60 fps

**Comment by rlawjdtn8890** [comment]
> > > json 구성
> > 
> > 
> > 방법을 모르요
> 
> .exe 파일이 있는 디렉토리에서 "fps_config.json"을 삭제하면 자동 닫기 기능이 실제로 작동하지 않으므로 다음에 시작할 때 다시 60fps로 잠깁니다.

2.1.0 버전에서 실행 하면 작업관리자는 나와있는데 실제는 안나옴
![스크린샷(42)](https://github.com/34736384/genshin-fps-unlock/assets/98939350/97f1dd20-b835-4e79-99af-a490677b5c32)

**Comment by rlawjdtn8890** [comment]
![스크린샷(43)](https://github.com/34736384/genshin-fps-unlock/assets/98939350/6911f895-b2fc-4528-b082-c0d3674d7dfd)

**Comment by rlawjdtn8890** [comment]
> 진정해, 곧 업데이트할게

![스크린샷(43)](https://github.com/34736384/genshin-fps-unlock/assets/98939350/0c0153d1-b662-41ce-a134-72bd1db3129b)

**Comment by rlawjdtn8890** [comment]
> > 진정해, 곧 업데이트할게
> 
> 2.1.0.exe 실행시 Setup 설치가 쉽지 않아 문제가 발생합니다 어서 수정하세요! ![스크린샷(43)](https://user-images.githubusercontent.com/98939350/240508829-0c0153d1-b662-41ce-a134-72bd1db3129b.png)

Someone else has a problem!
https://github.com/34736384/genshin-fps-unlock/issues/139#issue-1723272551

**Comment by mio12333** [comment]
Seeing everyone in a state of panic and confusion because of the tool malfunction really cracks me up. Does mihoyo even realize how poorly their game is designed? They rely on a tool to enhance their 'game experience,' such an arrogant and disgusting company. They really need to reflect on themselves.

**Comment by rlawjdtn8890** [comment]
> > > > 진정해, 곧 업데이트할게
> > > 
> > > 
> > > 2.1.0.exe 실행시 Setup 설치가 쉽지 않아 문제가 발생합니다 어서 수정하세요!![스크린샷(43)](https://user-images.githubusercontent.com/98939350/240508829-0c0153d1-b662-41ce-a134-72bd1db3129b.png)
> > 
> > 
> > 다른 사람이 문제가 있습니다! [#139(댓글)](https://github.com/34736384/genshin-fps-unlock/issues/139#issue-1723272551)
> 
> 제 생각에는 당신의 PC에 문제가 있는 것 같습니다. 또한 이 프로젝트의 관리자는 귀하에게 솔루션을 제공할 의무가 없습니다. 매너 좀 지켜주세요.

Chrome blocked it because it appeared as a malicious code when downloading it.

**Comment by DenSwitch** [comment]
works fine. thanks

**Comment by GraveUypo** [comment]
thank you for fixing it. i can't live without the extra smoothness anymore.

**Comment by nodaSnowball** [comment]
is this program part of hutao? or another independent program?

**Comment by Drekaelric** [comment]
I downloaded the new patch but i'm still locked at 60 fps, do i need to do something else besides replace the .exe?

**Comment by Dartv** [comment]
Same here, still locked at 60. Tried changing different settings in program and game, but no luck.

**Comment by copyvw** [comment]
new one stopped working also
