### ISSUE TITLE
About page shows v2.0.0 even in the v2.1.0 release

### ISSUE THREAD

**Issue by t0xic0der** [34736384/genshin-fps-unlock#139]
It is a minor house-keeping bug.

![image](https://github.com/34736384/genshin-fps-unlock/assets/49605954/082fe651-a50e-4a20-842e-6550735e8257)

**Comment by rlawjdtn8890** [comment]
![스크린샷(43)](https://github.com/34736384/genshin-fps-unlock/assets/98939350/416de225-9c96-456b-af10-f4855cb6e59a)

**Comment by t0xic0der** [comment]
@rlawjdtn8890 Please be mindful of the fact that this is a free and open-source project that @34736384 is developing and maintaining in their free time. They are in no way obligated to get you a solution quickly and you should appreciate them for pushing releases for v3.7 promptly like they did.
