### ISSUE TITLE
Could you please optimize the updated software?

### ISSUE THREAD

**Issue by Pinghaichuan** [34736384/genshin-fps-unlock#140]
The software is opened by default to run in the window, need to enter the game Settings to readjust the window Settings, you can optimize to open the software is full screen? thank you

**Comment by Pinghaichuan** [comment]
> You can already do that by setting `Fullscreen` to true in the config json file.

Thanks

**Comment by GrizzlyMyers** [comment]
The fullscreen setting can also be changed from the fps unlocker app options if you are not comfortable editing the json file directly. 

![settings](https://github.com/34736384/genshin-fps-unlock/assets/134516230/82d9913d-6189-4e03-9f30-14dc708f33d1)
