### ISSUE TITLE
3DMigoto + FPS Unlocker

### ISSUE THREAD

**Issue by Yakinuki** [34736384/genshin-fps-unlock#142]
Hi, I dont know what changed but previously you could run both at the same time without issues, If you have the time, could you look into that ?

Also thanks for creating this, I have been playing for a year with your Program and the game is not stable on my Computer without it.

**Comment by Yakinuki** [comment]
Small addition, I was testing around a bit and played with custom resolution settings / fullscreen etc. it's working now, though i cannot understand why.

Whatever, I somehow managed to fix it, if something should arise again, I will try more tests and play around with all options before posting something here again.

**Comment by aCriminaI** [comment]
I am also having this issue for some reason.

**Comment by aCriminaI** [comment]
I had this issue. The fix is to start the game with only the fps unlocker one time. Once you do this one time 3dmigoto and fps unlocker will both work together.

**Comment by Yakinuki** [comment]
> I had this issue. The fix is to start the game with only the fps unlocker one time. Once you do this one time 3dmigoto and fps unlocker will both work together.

Appears to have worked, only tested it twice, but thank you for the advice !

**Comment by Yakinuki** [comment]
> hi, I'm new to moding and wanna ask, can I use 3DMigoto and the FPS Unlocker on my main account without getting banned?

https://github.com/34736384/genshin-fps-unlock/issues/19 

Not the right place to ask, all I can say is that I have been using both ever since i started playing and link you to the thread that talks about this. So far , no reported bans.

**Comment by Fundamenta117** [comment]
It feels random if it will work or not. can you please fix it.
I tried everything and I am not getting any consistent results.

**Comment by Nixeld** [comment]
If anyone is still having this problem, you need to add the `d3d11.dll` file from 3DMigoto into the list of DLLs injected using the FPS unlocker.
Go to Genshin FPS Unlocker Options > Settings > DLLs > Add > Select `d3d11.dll` from your 3DMigoto directory.
Note that Enable HDR must be unchecked under the General tab of the FPS unlocker settings for this to work otherwise you will just see a black screen.
