### ISSUE TITLE
The game launches on window mode when opened from the unlocker, and fullscreen from the Epic Client.

### ISSUE THREAD

**Issue by Asterlsck** [34736384/genshin-fps-unlock#146]
Sorry if its an easy fix, but the game opens on windowed screen every time from the unlocker, and I have to manually adjust it on the ingame settings. Again, sorry if its an easy fix. Much love, unlocker is the best <3

**Comment by dweebdj** [comment]
just press alt + enter when the game launches, windows shortcut for fullscreen ♥

**Comment by dweebdj** [comment]
> @Asterlsck, that should not be the case. Could you please share the settings you are making use of in the framerate unlocker application?

wow i didnt even see the options tab....... fixed for me, wonder if thats OP fix too

**Comment by Asterlsck** [comment]
> @Asterlsck, that should not be the case. Could you please share the settings you are making use of in the framerate unlocker application?

![image](https://github.com/34736384/genshin-fps-unlock/assets/134565777/e0eab691-355b-4030-9c99-992d9bedd61c)

**Comment by sleepydream431** [comment]
> > @Asterlsck, that should not be the case. Could you please share the settings you are making use of in the framerate unlocker application?
> 
> ![image](https://user-images.githubusercontent.com/134565777/241094261-e0eab691-355b-4030-9c99-992d9bedd61c.png)
> 
> Is this it? Ty for the help :D



> > @Asterlsck, that should not be the case. Could you please share the settings you are making use of in the framerate unlocker application?
> 
> ![image](https://user-images.githubusercontent.com/134565777/241094261-e0eab691-355b-4030-9c99-992d9bedd61c.png)
> 
> Is this it? Ty for the help :D

I am also facing the same issue, not sure what is causing this.
