### ISSUE TITLE
Suggesting changing the project name to something else

### ISSUE THREAD

**Issue by t0xic0der** [34736384/genshin-fps-unlock#147]
Being a proponent of free and open-source software, I absolutely love the project and the fact that it lets me play (read, grind through) my favourite videogame with smoother animations and framerates and does not let the publishers limit the framerate even when I have a desktop video gaming setup that is more than capable of performing great. The 1121 stars on GitHub (at the time of creating this issue ticket) makes it more than evident that this project was successful in doing what the original developers did not even consider adding to the video game even after countless times telling them about this in the in-game surveys and a variety of forums.

That being said - I do feel concerned about the project and about its contributors. The publishers being a huge corporate body will have no mercy towards smaller developers who are introducing a quality-of-life feature to the game that they themselves should have implemented in the first place. We know that this application is harmless and does not do anything that would directly affect the publisher's revenue but chances are that they do not really care. As a result, this project and the contributors might get severely affected by possible lawsuits or cease/desist orders that they might send the way of the original author, forcing the project's sunset.

Like many other projects that are built for this videogame, I think that we should rename this project to some name that is somewhat relevant to the purpose of the application and yet, makes it harder for the publisher's management to be able to track it. We have seen that happening to a bunch of multiplayer mods made for the videogame, the mods that let you switch models, the mods that let you unlock hidden features and a bunch more that really do not have to do anything with the monetization of the videogame and yet had to be protected under the dire situations. I understand that it might make it difficult for the users to find this application though.

Here are some suggestions.

- **Option A** `animegame-framerate-unlocker`
- **Option B** `framerate-unlocker`
- **Option C** `animegame-framerate-enhancer`
- **Option D** `framerate-enhancer`
- **Option E** `animegame-experience-enhancer`
- **Option F** `experience-enhancer`

I have added additional suggestions that do not include the word "unlocker" as it might be perceived as intrusive to the in-game monetization system by the publisher's management and they might assume that the application lets folks obtain premium items in the videogame without having to pay the necessary monetary amount for the same. That being said - feel free to take them (or not) but do consider protecting this project from the evil eyes of the videogame publishers. I am also interested to hear what the user community feels about this proposal.

**Comment by 34736384** [comment]
IMO it's unnecessary.
First, it will break all existing links out there on the internet. Second, I can assure you that they do not care about this tool, not based on "how long it has existed" or "I haven't been banned in xxx days". I can't say why, but I can be sure they won't ban anyone from using this.

**Comment by t0xic0der** [comment]
I would like to think that as well but that does not necessarily seems to be the case. As evident with the v3.7 release https://github.com/34736384/genshin-fps-unlock/issues/145, the memory pattern for the framerate limit was moved - necessitating you to provide an update for the application. I am not sure if they did it as a response to the application but assuming the worst situation helps us stay afloat.

It might be that they moved the memory pattern only slightly to see if either this application is still updated as a response to that or if you are able to reverse engineer their changes so that they can introduce even more protection features down the line. It really helps us to be extra careful before they start locking down but then again I will let you decide.

**Comment by Ph42oN** [comment]
At this point i think apple is paying for exclusive 120 fps support.

**Comment by t0xic0der** [comment]
> IMO it's unnecessary.
> First, it will break all existing links out there on the internet. Second, I can assure you that they do not care about this tool, not based on "how long it has existed" or "I haven't been banned in xxx days". I can't say why, but I can be sure they won't ban anyone from using this.

To address the point about the possible breaking of existing links - GitHub sets automatic redirects for the links with the older project name to the ones with the newer project name. Take, for instance, I maintain this project that lets you install NVIDIA drivers easily on Fedora Linux and it was called `nvidia-auto-installer-for-fedora` before with the link https://github.com/t0xic0der/nvidia-auto-installer-for-fedora but now the project is renamed to `nvidia-auto-installer-for-fedora-linux` and clicking on the previous link would still lead you to the correct location and not break the link.

> it's not directed toward fps unlock, it's common for the pattern to change if they have made modifications to the engine

That's the best-case scenario. As their codebase is not open-source, we do not know for a fact if this was an attempt to gauge your capability of reworking the application to suit the newer memory pattern, to check your responsiveness to the project repository (owing to the fact that the previous release of v2.0.0 was made over a year ago) or if it was a normal modification to the engine as you mentioned. I would like to believe that they are modifying their engine to allow for a bigger asset control when the next region drops in the videogame update v4.0 but I cannot say that for sure. 

All I am going to say is - It really helps to be protective all the time instead of being so as a response to something bad that the publishers might end up doing.

**Comment by khallnayak** [comment]
Having a different name to the project might cause confusion at a single glance but it might help to keep the project alive in case of any involvement from publishers.

**Comment by DhruvBhirud** [comment]
I totally agree with what @t0xic0der is suggesting, this project needs some new name which does not explicitly mentions the "animegame" to avoid being railed by legal team at the animegame. Might I even suggest more things to do the logo in application can be changed to something which does not have same logo as animegame, the company might file Cease and Desist order against developers, and them being corporate giant as of now won't help your case, staying low and hidden is the best option as of now there are other animegame mods which does not mention name once but are accessible to people nonetheless. Having precautionary measures are always better than facing potential legal consequences later on.

**Comment by 34736384** [comment]
> > IMO it's unnecessary.
> > First, it will break all existing links out there on the internet. Second, I can assure you that they do not care about this tool, not based on "how long it has existed" or "I haven't been banned in xxx days". I can't say why, but I can be sure they won't ban anyone from using this.
> 
> To address the point about the possible breaking of existing links - GitHub sets automatic redirects for the links with the older project name to the ones with the newer project name. Take, for instance, I maintain this project that lets you install NVIDIA drivers easily on Fedora Linux and it was called `nvidia-auto-installer-for-fedora` before with the link https://github.com/t0xic0der/nvidia-auto-installer-for-fedora but now the project is renamed to `nvidia-auto-installer-for-fedora-linux` and clicking on the previous link would still lead you to the correct location and not break the link.
> 
> > it's not directed toward fps unlock, it's common for the pattern to change if they have made modifications to the engine
> 
> That's the best-case scenario. As their codebase is not open-source, we do not know for a fact if this was an attempt to gauge your capability of reworking the application to suit the newer memory pattern, to check your responsiveness to the project repository (owing to the fact that the previous release of v2.0.0 was made over a year ago) or if it was a normal modification to the engine as you mentioned. I would like to believe that they are modifying their engine to allow for a bigger asset control when the next region drops in the videogame update v4.0 but I cannot say that for sure.
> 
> All I am going to say is - It really helps to be protective all the time instead of being so as a response to something bad that the publishers might end up doing.

Again, there is no need to worry. Changing the repo name will not prevent mihoyo from tracking it. It is completely unnecessary. They are aware of this repo from the beginning, they don't care, and no one will be banned from using it.

**Comment by 34736384** [comment]
> I totally agree with what @t0xic0der is suggesting, this project needs some new name which does not explicitly mentions the "animegame" to avoid being railed by legal team at the animegame. Might I even suggest more things to do the logo in application can be changed to something which does not have same logo as animegame, the company might file Cease and Desist order against developers, and them being corporate giant as of now won't help your case, staying low and hidden is the best option as of now there are other animegame mods which does not mention name once but are accessible to people nonetheless. Having precautionary measures are always better than facing potential legal consequences later on.

There won't be any legal consequences. This tool does not hurt their revenue, it's not a cheat. The worse thing it can happen is just a DMCA.
