### ISSUE TITLE
Doesn't work on 3.7 cuz "outdated pattern"

### ISSUE THREAD

**Issue by Jamesquid** [34736384/genshin-fps-unlock#150]
i use this external sofware since a year now, still not banned, and it's amazing but since the last update seems like mhy did something to change our comfortness. i saw another issue talking about it not working on the 3.8 beta, they probably make  it so that it doesn't work on 3.7 (not beta)  too.

![image](https://github.com/34736384/genshin-fps-unlock/assets/134612440/e3c9be6e-42ed-47a4-b602-0b7694ec125b)

**Comment by 34736384** [comment]
only if you have checked commits, closed issues, or release page.......
