### ISSUE TITLE
guys, what is this? how can i fix it

### ISSUE THREAD

**Issue by MegaDit1** [34736384/genshin-fps-unlock#151]
![Error 24 05 2023 23_50_33](https://github.com/34736384/genshin-fps-unlock/assets/134555363/3b23a5aa-ce2e-4e32-82ce-8fea29eb63d2)

**Comment by MegaDit1** [comment]
second sentence says "the specified file cannot be found"

**Comment by 34736384** [comment]
dont use anything other than alpha num path, you might need to manually edit the config file after you have changed your directory name

**Comment by MegaDit1** [comment]
> dont use anything other than alpha num path, you might need to manually edit the config file after you have changed your directory name

i changed it, now it just won't open, i downloaded lastest version 2.1.1 but still the same issue
please help
