### ISSUE TITLE
Possible Threat in new File

### ISSUE THREAD

**Issue by Sharkorawr** [34736384/genshin-fps-unlock#154]
My antivirus flagged the new file for malware after downloading it. It could be possible that it's just oversensitive since the file is modifying another application. However, I never had this problem with the previous files released. I always used the previous fps unlockers and never had a problem, so I would be surprised if there was suddenly malintent. However, an explanation would be nice.
-Thanks

**Comment by copyvw** [comment]
mine also flagged the new one, pretty sure its fine though

**Comment by Sharkorawr** [comment]
90% chance your right but im just gonna wait for a few more responses

**Comment by 34736384** [comment]
false positive, source is here, you can compile it yourself
