### ISSUE TITLE
It seems that the new 3.7 version unlockfps fails sometimes!

### ISSUE THREAD

**Issue by shishenmiemo** [34736384/genshin-fps-unlock#155]
It seems that the new 3.7 version doesn't work well sometimes:

I really don't know how to describe it. My monitor has a refreshing rate of 165Hz. I used to run Genshin Impact in 144Hz FPS with the help of unlockfps, and the motion there is really smooth.

However, when I use this new version of 3.7 and set the fps to 144Hz, although it's really better than 60Hz, IN MOST CASES the smoothness doesn't reach the former 144Hz as I used to feel (Say it's more like a 90-100Hz experience. It's way more better than 60Hz, but you still can find lagging or smear). However, RARE case such as the first time you download unlockfps into your computer and run 144Hz after first configuration, it works well as usual.

So I wonder that if there are bugs that may cause this happened. Here are my settings for unlockfps and something I need to share:
![image](https://github.com/34736384/genshin-fps-unlock/assets/13353289/b0f1b04a-6ed7-4a30-85a8-d3c99b1f8cd7)
![image](https://github.com/34736384/genshin-fps-unlock/assets/13353289/3f208b03-45f7-4ac6-924c-118b4b386305)
![image](https://github.com/34736384/genshin-fps-unlock/assets/13353289/9d6cdf72-c2d9-434b-aa1e-74854ba70bb1)

- Although I tickled 'Auto Disable VSync', I can still find that VSync options is ON in the game, and as I change it to OFF in the game, it feels better.
- In most rare cases, the fullscreen is not tickled at first (just after re-download unlockfps), and it works really well. And after I start unlockfps the second or more times, it won't work well at all. (Better than 60Hz, but much worse than the real 144hz experience I used to take)
- For some unknown reasons, the Release version I downloaded right after new version updated, I can choose FPS up to 1000, but fps in recent version are only up to 360, which is really weird cuz I didn't see any new commit in github.

**Comment by shishenmiemo** [comment]
Here is a solution that might be helpful for situation above:

- Tickle both 'Fullscreen' and 'Custom Resolution', and set Custom Resolution as a much smaller resolution than the monitor resolution you use, such as 1920*1080 ,if you use 2560*1440 resolution like me.
- Change value of FPS to a significant large one, which can be more than the real FPS your monitor can have, such as 300.
- Start the game, and you will get a really smooth but a little bit low resolution feature in game.
- Change the resolution in game to your desired one, i.e. 2560 * 1440 for me.
- Apply it, and the game might change to popup window version. Use Alt + Enter to change it to Fullscreen mode.
- Enjoy it ;)

**Comment by CXwudi** [comment]
One thing I noticed is that Exclusive Fullscreen is better in any cases. Once you're in the game (after the 7 element icons), press windows key to temporary exit from the game, and then click the Genshin icon to go back. Then you can feel the true smoothness.

However, this method comes with a cost of having https://github.com/34736384/genshin-fps-unlock/issues/92 bug

**Comment by shishenmiemo** [comment]
@CXwudi Got it, I'll give it a try and ttyl

**Comment by superwx1985** [comment]
> Here is a solution that might be helpful for situation above:
> 
> * Tickle both 'Fullscreen' and 'Custom Resolution', and set Custom Resolution as a much smaller resolution than the monitor resolution you use, such as 1920 x 1080, if you use 2560 x 1440 resolution like me.
> * Change value of FPS to a significant large one, which can be more than the real FPS your monitor can have, such as 300 or 360
> * Start the game, and you will get a really smooth but a little bit low resolution game.
> * Change the resolution in game to your desired one, i.e. 2560 x 1440 for me.
> * Apply it, and the game might change to popup window version. Use Alt + Enter to change it to Fullscreen mode.
> * Enjoy it ;)

not work for me :(

**Comment by Arcanologue** [comment]
We all seem o have the same  issue :
When This tool is lauching the game FOR THE FIST TIME (1 per restart) it never apply the selected FPS.

i've got 3 differents comptuers that behave the same way...

**Comment by BlueStarBRS** [comment]
> We all seem to have the same issue : When This tool is lauching the game FOR THE FIST TIME (1 per restart) it never apply the selected FPS.
> 
> i've got 3 differents comptuers that behave the same way...

tried now on 2 systems on both the error appers

**Comment by BlueStarBRS** [comment]
try out the new updated version:
https://github.com/34736384/genshin-fps-unlock/releases/tag/v2.1.1
