### ISSUE TITLE
whenever i open fps unlock it says the application was unable to start correctly this issue was not present in the previous version

### ISSUE THREAD

**Issue by Kinzig334** [34736384/genshin-fps-unlock#157]
My previous fps unlock started normally but when i downloaded the latest 3.7 fps unlock it just kept saying the application couldn't start correctly, I'm wondering if I'm the only one with this issue or maybe i am missing something.

**Comment by 34736384** [comment]
anti virus issues

**Comment by Kinzig334** [comment]
what exactly can I do to fix the issue? I already tried disabling anti-virus protection but nothing works
