### ISSUE TITLE
how do i install this 

### ISSUE THREAD

**Issue by beerus123** [34736384/genshin-fps-unlock#158]
can someone pls help me how to install this ive been using this from the past 6 months after this 3.7 update there's  no .exe application in fps unlocker iam unable to play this shit min 60 fps pls hlp!!

**Comment by beerus123** [comment]
and there's no .exe showing in the file for me

**Comment by dromzeh** [comment]
> and there's no .exe showing in the file for me

??? you can get the exe from the releases page https://github.com/34736384/genshin-fps-unlock/releases/download/v2.1.0/unlockfps_clr.exe

**Comment by beerus123** [comment]
i could'nt see the .exe but thankyou so much i downloaded it now
