### ISSUE TITLE
Antivirus detects .exe as a virus

### ISSUE THREAD

**Issue by GatoTristeY** [34736384/genshin-fps-unlock#159]
Windows defender: Trojan:Win32/Bearfoos.A!ml

First time this happens

**Comment by sefinek24** [comment]
Screenshot?

**Comment by GatoTristeY** [comment]
> Screenshot?
![2023-05-29 00_40_21-Seguridad de Windows](https://github.com/34736384/genshin-fps-unlock/assets/134466098/8d16a4ab-b9df-4389-ab3a-697ada5754f6)

**Comment by GatoTristeY** [comment]
> 

![2023-05-29 00_42_19-Seguridad de Windows](https://github.com/34736384/genshin-fps-unlock/assets/134466098/17c9a58e-ee3f-4cf1-b9e5-2667ed78dce2)

(I renamed the original exe)

**Comment by sefinek24** [comment]
@GatoTristeY, make sure you are downloading the correct file by verifying its checksum.

**Windows:**
```bash
certutil -hashfile <PATH> SHA256
```

**Linux:**
```bash
sha256sum <PATH>
```

`unlockfps_clr.exe` <https://github.com/34736384/genshin-fps-unlock/releases/download/v2.1.0/unlockfps_clr.exe>
> **SHA256 CHECKSUM:**
```
2161da01a3d0121ac487c2edc3be63f39164433bb8ff0be18e44f39d49309c07
```

If the checksum matches the one I provided above, update your Windows system. Windows Defender sometimes act strange, so I don't use it.

Anyway, you can always compile the source code yourself using Visual Studio.
