### ISSUE TITLE
is this safe?  too many viruses

### ISSUE THREAD

**Issue by fbdl77** [34736384/genshin-fps-unlock#160]
![Screenshot_20230530_042346_Chrome](https://github.com/34736384/genshin-fps-unlock/assets/84037957/9c9ba5e9-d1d8-4444-9a1c-eb14cd4f5ffa)
too many what do you think?
![Icon_Emoji_Paimon's_Paintings_17_Collei_4](https://github.com/34736384/genshin-fps-unlock/assets/84037957/2f21392c-b179-433a-8670-5b9c23d8d864)

**Comment by fbdl77** [comment]
> ![Screenshot_20230530_042346_Chrome](https://user-images.githubusercontent.com/84037957/241795646-9c9ba5e9-d1d8-4444-9a1c-eb14cd4f5ffa.png) too many what do you think? ![Icon_Emoji_Paimon's_Paintings_17_Collei_4](https://user-images.githubusercontent.com/84037957/241795804-2f21392c-b179-433a-8670-5b9c23d8d864.png)

**Comment by BlueStarBRS** [comment]
it is safe.
