### ISSUE TITLE
The latest version is detected in Windows Defender

### ISSUE THREAD

**Issue by simm4256** [34736384/genshin-fps-unlock#161]
![image](https://github.com/34736384/genshin-fps-unlock/assets/25508348/4ba48a6c-002a-4837-965f-13a7257f752d)

The last version of the virus 'Trojan:Win32/Wacatac.B!ml' is detected in Windows Defender.
Does the added code cause this?
Can I just ignore it?

**Comment by 34736384** [comment]
you can just ignore it
