### ISSUE TITLE
FPS Unlock v2.1.0 no longer works as of 2nd June 2023

### ISSUE THREAD

**Issue by t0xic0der** [34736384/genshin-fps-unlock#163]
Tested on videogame version 3.7.

I have an AMD Radeon RX 6800 XT and AMD Ryzen 9 5900X. The memory installed is 32GB DDR4 3600MHz and the game is installed on a PCIe 3.0x4 NVMe SSD. I am running Windows 10 22H2.

The unlocker was working up until yesterday but it does not anymore since one in-game patch download that I noticed. The said patch might have to do something with this or it might not.

**Comment by 34736384** [comment]
Tested on 22h2 and 2004, still working using the newest version

**Comment by MrZomboED** [comment]
Download 2.1.1, all works perfect

**Comment by t0xic0der** [comment]
Let me check the most recent version and report back

**Comment by t0xic0der** [comment]
Thanks @MrZomboED. v2.1.1 works fine for me. Closing this issue.
