### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by Eriririri** [34736384/genshin-fps-unlock#165]
![error](https://github.com/34736384/genshin-fps-unlock/assets/39609893/e5f8a86b-d943-45dd-9adb-065c3d88d92e)

microsoft .net framework unhandled exception has occurred in your application the given key was not present in the dictionary

i have this error.
my fps config is something like this
{
  "DllList": [],
  "Priority": 3,
  "MonitorNum": 0,
  "CustomResY": 1080,
  "CustomResX": 1920,
  "FPSTarget": 120,
  "UsePowerSave": false,
  "StartMinimized": false,
  "IsExclusiveFullscreen": false,
  "UseCustomRes": false,
  "Fullscreen": false,
  "PopupWindow": false,
  "AutoClose": false,
  "AutoDisableVSync": true,
  "AutoStart": false,
  "GamePath": ""
}

if i edit game path to

{
  "DllList": [],
  "Priority": 3,
  "MonitorNum": 0,
  "CustomResY": 1080,
  "CustomResX": 1920,
  "FPSTarget": 120,
  "UsePowerSave": false,
  "StartMinimized": false,
  "IsExclusiveFullscreen": false,
  "UseCustomRes": false,
  "Fullscreen": false,
  "PopupWindow": false,
  "AutoClose": false,
  "AutoDisableVSync": true,
  "AutoStart": false,
  "GamePath": "E:\Genshin Impact\Genshin Impact Game\GenshinImpact.exe"
}

then it wont error but the game wont load.i run as admin.
it just blinking for some second then nothing happen.
i install genshin on C drive but i move to E drive.i manually set gamepath then nothing happen.no error but nothing happen.

**Comment by MrZomboED** [comment]
1. Disable windows protection/antivirus or add program in whitelist
2. Download latest v2.1.1
3. Try again

**Comment by BlueStarBRS** [comment]
broken .NET framework 
or outdated unlocker version

**Comment by 34736384** [comment]
reinstall official launcher and update your game path there
