### ISSUE TITLE
Application not working, FPS is still capped at 60.

### ISSUE THREAD

**Issue by ItzDerock** [34736384/genshin-fps-unlock#167]
see this video: https://derock.media/HgzSvO.mp4

Windows 11 22H2 (22621.1702)
NVIDIA GTX 2070 SUPER running 532.03 Game Ready drivers.
3440x1440 display at 180Hz with HDR on.

**Comment by ItzDerock** [comment]
nvm updating graphics drivers to 535.98 worked

**Comment by BlueStarBRS** [comment]
532 is a bit old yes...
