### ISSUE TITLE
Arrows are not working

### ISSUE THREAD

**Issue by quqsy1** [34736384/genshin-fps-unlock#17]
I cant change amount of fps. I have most of people who use this programm has 144hz or higher monitor. Can u please set deafult fps to 150?

**Comment by 34736384** [comment]
You don’t have to tab out to change, just stay tabbed in game to change it

**Comment by quqsy1** [comment]
> You don’t have to tab out to change, just stay tabbed in game to change it

Oh sorry my fault. Still thank you.
