### ISSUE TITLE
Arrow particles bug / Unlocker inconsistencies

### ISSUE THREAD

**Issue by nexuhss** [34736384/genshin-fps-unlock#174]
After shooting a charged attack arrow, when using the fps unlocker, (easily noticeable on Hydro arrows)

The particles fly back in an abnormal way, at least its an easy way to check if the unlocker started correctly since lastly there are some times that the unlocker doesn't work nor closes automatically after the game is closed (the auto close option is on)

![image](https://github.com/34736384/genshin-fps-unlock/assets/136111096/aae38ee9-aaed-4d16-8159-4789cb848a49)

**Comment by 34736384** [comment]
game engine issues, not related to unlocker

and it seems that you aren't using the newest version

**Comment by nexuhss** [comment]
would an auto updater be possible in order to fix these issues brought by the game updating?
