### ISSUE TITLE
Game freezing for no reason after staying at the game for a while

### ISSUE THREAD

**Issue by Subarashill** [34736384/genshin-fps-unlock#175]
This issue happens to me in this version and its really frustrating, When I enter the game it's works perfectly for about 5 minutes to 10 minutes and then the screens freezes and gets crashed (sometimes crash after 1 min) and I don't know what to do can anyone help me with this issue?

**Comment by Breizh-Brittany** [comment]
Sometimes my game crash:
The screen freeze but the audio is still audible.
The reason for me is my overclocked GPU.

**Comment by Subarashill** [comment]
> Sometimes my game crash: The screen freeze but the audio is still audible. The reason for me is my overclocked GPU.

Mine isn't tho, and when the screen freezes the audio goes with it (only happens in genshin other games don't have this issue)

**Comment by hiluncermomo** [comment]
have you tried to start the normally (without unlock)?

**Comment by Subarashill** [comment]
> Sometimes my game crash: The screen freeze but the audio is still audible. The reason for me is my overclocked GPU.

if you still face this issue I recommend you to use ddu, and unstall the gpu driver from it's root I guess it's solved this issue for me

**Comment by Subarashill** [comment]
> have you tried to start the normally (without unlock)?

yes it was working successfully but I had to unstall my gpu driver and install it again and it's stable to far

**Comment by Asterlsck** [comment]
Im experimenting the same problem, both my monitors shutdown and my PC freezes after 10-15min of playing, only option is to force shutdown and reset PC, any help? Thank youuu

**Comment by Subarashill** [comment]
> Im experimenting the same problem, both my monitors shutdown and my PC freezes after 10-15min of playing, only option is to force shutdown and reset PC, any help? Thank youuu

I don't know if that would help, but can I know what's your gpu? if it was from the 40 gen of nvidia you and have this issue you should try a certain update by following these instructions and if it didn't work your could ask in this forums too the people there will help!

https://www.nvidia.com/en-us/geforce/forums/geforce-graphics-cards/5/520896/4070ti-crashes-when-its-reaches-100-usage/3361132/
