### ISSUE TITLE
全屏模式

### ISSUE THREAD

**Issue by jzfzzzz** [34736384/genshin-fps-unlock#176]
请问为什么开启是窗口模式？希望能搞成开启是全屏模式谢谢

**Comment by 34736384** [comment]
设置里的选项你是一点都不看？

**Comment by jzfzzzz** [comment]
(°_°)…可是软件一打开就启动了，界面也只有一个start的按钮，设置是在哪里啊请问

**Comment by Leao9203** [comment]
> (°_°)…可是软件一打开就启动了，界面也只有一个start的按钮，设置是在哪里啊请问

。。。在这

![图片](https://github.com/34736384/genshin-fps-unlock/assets/45661339/2e25465e-9032-4552-a6e8-60a2b2dcebca)

**Comment by jzfzzzz** [comment]
> > (°_°)…可是软件一打开就启动了，界面也只有一个start的按钮，设置是在哪里啊请问
> 
> 。。。在这
> 
> ![图片](https://private-user-images.githubusercontent.com/45661339/288291488-2e25465e-9032-4552-a6e8-60a2b2dcebca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NjEyNzksIm5iZiI6MTcwMTg2MDk3OSwicGF0aCI6Ii80NTY2MTMzOS8yODgyOTE0ODgtMmUyNTQ2NWUtOTAzMi00NTUyLWE2ZTgtNjBhMmIyZGNlYmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDExMDkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmM2E2ZDNhMGM1MGYyNzE4N2UyM2RjN2U0YjMyMGFiMzY2ZDc3NDAzNmRhOTkxYWJjYmIzMGIyMDkxOTg2ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c1OjmeOWmgkSgVDN_mIb0mFHGUVowbeqRLsID794cbg)

谢谢
