### ISSUE TITLE
unlock not working 

### ISSUE THREAD

**Issue by Raze876** [34736384/genshin-fps-unlock#178]
As someone said it works once after a reboot, just rebooted which I didn't want to do because of stuff i have open and it didnt even work for the first try after reboot, still capped at 60, the unlocker works up to when it starts stuttering when loading at the start just before the door comes up to "START GAME", the fps drops from higher fps then rises up back to only 60 and stays 60, so it works up to that point where something stops it or overrides it etc. never had a problem with the fps until the latest version, it was working every other close app and reopen in 3.7 but i guess they shadow updated something, im gonna try reloading the whole unlocker see if anything changes.

Edit: I deleted unlockfps_clr.exe and fps_config.json (they were in a different folder) downloaded latest version and put it in the same folder as the genshin folder aka the root folder of the drive, pasted back my old config settings tested it works, closed game reopened it and still works no reboot needed, maybe putting the files in the same main folder as genshin would help, I'll update this again if anything stops working.

**Comment by Spedemix** [comment]
Did you place the unlockfps in the GI main folder or the "Genshin Impact Game" folder aka where the exe is? I'm having the same problem with the unlock having stopped working yesterday.

**Comment by Raze876** [comment]
![image](https://github.com/34736384/genshin-fps-unlock/assets/112791187/72512c87-851f-4490-b995-3f786644bfa0)

neither, I put it in the root folder of the drive where I also have the genshin folder as you can see in this screenshot, also went in and out the game a few more times since and no problems :)

**Comment by steven52880** [comment]
I am having the same problem too. It has probably stopped working in the past few days

The unlocker is placed in G:\Genshin\FPSUnlocker\
The game is placed in G:\Genshin\Genshin Inpact Game\

**Comment by cristiandevweb** [comment]
I am having the same problem too. It has probably stopped working in the past few days

**Comment by aabbey33** [comment]
I'm getting an error for Incorrect FPS pattern, if its of any assistance

![image](https://github.com/34736384/genshin-fps-unlock/assets/7175893/8abd30c1-b868-4ff6-ac37-5a13092ec1d1)

**Comment by kuznetsov-ns** [comment]
> I'm getting an error for outdated FPS pattern, if its of any assistance
> 
> ![image](https://github.com/34736384/genshin-fps-unlock/assets/7175893/8abd30c1-b868-4ff6-ac37-5a13092ec1d1)
> 

did you use the latest release version? i played 1 hour ago with this build and it worked perfectly!

**Comment by aabbey33** [comment]
> > I'm getting an error for outdated FPS pattern, if its of any assistance
> > ![image](https://user-images.githubusercontent.com/7175893/244960390-8abd30c1-b868-4ff6-ac37-5a13092ec1d1.png)
> 
> did you use the latest release version? i played 1 hour ago with this build and it worked perfectly!

Yes, I used 2.1.1

**Comment by Raze876** [comment]
> > > I'm getting an error for outdated FPS pattern, if its of any assistance
> > > ![image](https://user-images.githubusercontent.com/7175893/244960390-8abd30c1-b868-4ff6-ac37-5a13092ec1d1.png)
> > 
> > did you use the latest release version? i played 1 hour ago with this build and it worked perfectly!
> 
> Yes, I used 2.1.1

I deleted my old fps unlocker.exe and the json file and downloaded the latest version of fps unlocker and put them in the same folder beside the genshin main folder so the unlocker is not inside the genshin folder both the genshin folder and unlocker exe are in a folder beside each other, then the json file also got created there automatically, I then pasted back my old settings which I already had written down elsewhere, no problems atall today either, I know sometimes you have to have some files in root folders and in specific places for the programs to work properly.

**Comment by cristiandevweb** [comment]
i downloaded the new version 2.1.1 and it worked for me, many thanks to all who make this possible :D

**Comment by BlueStarBRS** [comment]
> I'm getting an error for outdated FPS pattern, if its of any assistance
> 
> ![image](https://user-images.githubusercontent.com/7175893/244960390-8abd30c1-b868-4ff6-ac37-5a13092ec1d1.png)

download new version.

**Comment by BlueStarBRS** [comment]
> > > > I'm getting an error for outdated FPS pattern, if its of any assistance
> > > > ![image](https://user-images.githubusercontent.com/7175893/244960390-8abd30c1-b868-4ff6-ac37-5a13092ec1d1.png)
> > > 
> > > 
> > > did you use the latest release version? i played 1 hour ago with this build and it worked perfectly!
> > 
> > 
> > Yes, I used 2.1.1
> 
> I deleted my old fps unlocker.exe and the json file and downloaded the latest version of fps unlocker and put them in the same folder beside the genshin main folder so the unlocker is not inside the genshin folder both the genshin folder and unlocker exe are in a folder beside each other, then the json file also got created there automatically, I then pasted back my old settings which I already had written down elsewhere, no problems atall today either, I know sometimes you have to have some files in root folders and in specific places for the programs to work properly.

btw the folder location isnt necessary,

**Comment by aabbey33** [comment]
> > I'm getting an error for outdated FPS pattern, if its of any assistance
> > ![image](https://user-images.githubusercontent.com/7175893/244960390-8abd30c1-b868-4ff6-ac37-5a13092ec1d1.png)
> 
> download new version.

As I said earlier, I was already using the latest version (2.1.1).

someone mentioned deleting the cfg earlier and I have yet to attempt that, so that will be the next step taken when I get home.

**Comment by BlueStarBRS** [comment]
> Edit 2: Okay for some reason the file modification date seemed to be listed as Jan 22nd on my executable, which didn't make sense for a release 2 weeks ago. despite already replacing the file two days ago, I just did it again.  Working now.

I just sayed it 90% of the issues in this context is exactly Like that 😅
