### ISSUE TITLE
Do you also get crashes since 2.0 ? 

### ISSUE THREAD

**Issue by Lehner82** [34736384/genshin-fps-unlock#18]
upload_crashed

**Comment by dromzeh** [comment]
those crashes seem to be just you, I'm using this unlocker with 2.0 and it's running fine.

**Comment by Erik-97** [comment]
> those crashes seem to be just you, I'm using this unlocker with 2.0 and it's running fine.

same, I started to play a little bit more than a week and even 10-hour sessions don't have a crash.
