### ISSUE TITLE
作者大大你好，如何配置国服和国际服同时解锁帧率？

### ISSUE THREAD

**Issue by WenchenWang** [34736384/genshin-fps-unlock#181]
配置文件咋改？

**Comment by Thunderz2016** [comment]
可以在国服和国际服的目录各放一个解锁器，分开配置然后分开运行。

**Comment by WenchenWang** [comment]
谢谢🙏

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Thunderz2016 ***@***.***>
发送时间: Sunday, June 18, 2023 4:42:33 PM
收件人: 34736384/genshin-fps-unlock ***@***.***>
抄送: Phinsin ***@***.***>; Author ***@***.***>
主题: Re: [34736384/genshin-fps-unlock] 作者大大你好，如何配置国服和国际服同时解锁帧率？ (Issue #181)


可以在国服和国际服的目录各放一个解锁器，分开配置然后分开运行。
