### ISSUE TITLE
374fps limit and audio stuttering\disappearing.

### ISSUE THREAD

**Issue by ZEFIR001** [34736384/genshin-fps-unlock#182]
It appears that 374fps is current limit. Is there any way to go above that without using older "hotkey based" versions?
My hardware is capable doing much more and i want to have minimum amount of input delay while clearing abbyss.

Also dialogs started being cut mid play and some ingame SFX as well. Any way to fix that or its game engine related?

**Comment by 34736384** [comment]
game engine related
