### ISSUE TITLE
Skipping effect when aiming with a bow

### ISSUE THREAD

**Issue by Andyy58** [34736384/genshin-fps-unlock#185]
When aiming with a bow while using the fps unlocker, it seems to result in crosshair skipping, almost like how pixel skipping looks when you have super low dps and super high sensitivity in other games. This is most noticeable when moving slowly, but also noticeable if you're trying to aim more precisely, since there are some pixels you can't aim at and the reticle will just skip over. Will post a short video showcasing later

**Comment by 34736384** [comment]
Game engine issues, not related to unlocker
