### ISSUE TITLE
点击开始游戏后出现K32EnumProcessModule failed with code: 299报错

### ISSUE THREAD

**Issue by lpa20020220** [34736384/genshin-fps-unlock#186]
但是进入游戏内之后帧率正常解锁，已尝试删除cfg无效
![QQ截图20230622095050](https://github.com/34736384/genshin-fps-unlock/assets/34177963/0503817d-ea49-49d1-a6d1-1685cb9c1171)

**Comment by t0xic0der** [comment]
I can confirm I experience the same error every now and then.

**Comment by 34736384** [comment]
可忽略

**Comment by StepS-** [comment]
Just wanted to let you know that this error hasn't happened a single time since the .NET 8 rewrite. Good job
