### ISSUE TITLE
VirusTotal Results: 5/71 Flagged as Malicious

### ISSUE THREAD

**Issue by RafaelDee** [34736384/genshin-fps-unlock#189]
I always send files to VirusTotal when I am suspicious
can someone explain what's happening here?
link result: https://www.virustotal.com/gui/file/cbe404e97faa75d2aafbfff617c4ed980e1948cbcab17fe6b7f18544f8165e73/detection

![image](https://github.com/34736384/genshin-fps-unlock/assets/69748293/261a806a-9194-4d2b-956c-56f5b91d89a0)

**Comment by 34736384** [comment]
false positive, and the source code is available so I don't know what are you being suspicious of
