### ISSUE TITLE
borderless fullscreen?

### ISSUE THREAD

**Issue by mariokiller64** [34736384/genshin-fps-unlock#192]
How do I use borderless fullscreen with this program? I usually launch Genshin with these arguments
"C:\Program Files\Genshin Impact\Genshin Impact game\GenshinImpact.exe" -screen-fullscreen 0 -popupwindow -screen-width 1920 -screen-height 1080
And I get fullscreen borderless but I can't seem to do that with this program, it always runs in windowed mode. And when I check Fullscreen, custom resolution, Window mode: Borderless, it still minimizes. It only works when I launch it with my shortcut.

**Comment by ByZorks** [comment]
You have to use the popup window option + windows mode borderless
![image](https://github.com/34736384/genshin-fps-unlock/assets/80073731/a208aefd-c809-442a-9dd8-1224ef0f8285)

**Comment by Halaxane** [comment]
how did you get this window ?

**Comment by ByZorks** [comment]
> how did you get this window ?

![image](https://github.com/34736384/genshin-fps-unlock/assets/80073731/23dd8def-af94-4a61-b424-5f29d3fefd3c)

**Comment by Halaxane** [comment]
thx
