### ISSUE TITLE
3.8 fps unlocked not working ? 

### ISSUE THREAD

**Issue by kaiser0419** [34736384/genshin-fps-unlock#194]
When entering the game ( The door animation ), the fps is unlocked . but when i entered the game , it locked it back to 60fps again
when i open up settings , it goes back to 144fps again. How do i fix it ?

**Comment by 0Blueaura** [comment]
When you launch the game, force vsync off in the FPSU, and enable vsync in game. The game will run at the speed you set in FPSU. It's a glitch that works for me. The issue is the screen will flicker very slightly.
