### ISSUE TITLE
'Start Game Automatically' feature doesn't work properly

### ISSUE THREAD

**Issue by LeonardoZernes** [34736384/genshin-fps-unlock#198]
Since the update for 3.7, the tool does not save the option for "Start Game Automatically" when I try to open the Unlock FPS program. When I mark the option for the next time the program starts, the option still appears as non checked. So, I always have to start the Genshin Impact ".exe" by hand. I do not know what is going wrong. I have tried to reinstall the Unlock FPS program several times, deleting the config file, but it does not seem working. 

I do not know if these problems are related, but sometimes the program shows me the Error 299 from the graphic, but it seems like nothing bad is happening. Screenshot: 
![image](https://github.com/34736384/genshin-fps-unlock/assets/60662663/716d9b6e-cf92-4b84-a4c5-22cb7a682e4b)

Thanks you in advance for all the support.

**Comment by osilir** [comment]
Maybe this can help you.

1. Run Unlock FPS
2. Check the "Start Game Automatically"
3. Do not click "Start Game" and just close the Unlock FPS.
4. Run Unlock FPS again and what's going on.

In my case, the autorun check was not saved when the auto close option was enabled.
By manually close windows the check is saved.

**Comment by ImChinaNB** [comment]
Alternatively, you could simply edit the `fps_config.json` file and change `"AutoStart": false` to true.

**Comment by LeonardoZernes** [comment]
> Maybe this can help you.
> 
> 1. Run Unlock FPS
> 2. Check the "Start Game Automatically"
> 3. Do not click "Start Game" and just close the Unlock FPS.
> 4. Run Unlock FPS again and what's going on.
> 
> In my case, the autorun check was not saved when the auto close option was enabled. By manually close windows the check is saved.

thanks lot! this steps solve my problem ♥
