### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by King-Sign** [34736384/genshin-fps-unlock#2]
no ban account?

**Comment by 34736384** [comment]
my alt is currently ar38, no bans so far.

**Comment by teyhouse** [comment]
> my alt is currently ar38, no bans so far.

Will there be an Update for 1.6?

**Comment by 34736384** [comment]
> > my alt is currently ar38, no bans so far.
> 
> Will there be an Update for 1.6?

there is no need to, still working

**Comment by KeyBrute** [comment]
suppose you get a first offense ban, would it be a 24hr ban or?

**Comment by 34736384** [comment]
> suppose you get a first offense ban, would it be a 24hr ban or?

honestly no idea, haven't have a case yet, could be a week or a month
