### ISSUE TITLE
I'm getting an Error after clicking Start Game Please Help

### ISSUE THREAD

**Issue by Rosaliyne** [34736384/genshin-fps-unlock#201]
![Ekran görüntüsü 2023-08-02 145844](https://github.com/34736384/genshin-fps-unlock/assets/141238412/b718dce9-c002-4f1e-95ee-2d18d563d4d4)

**This is the error i get. If anyone knows a permanent solution please let me know i will be appreciated.**

**Comment by AquaSimulacra** [comment]
You can try the newer release of 2.1.1

**Comment by Rosaliyne** [comment]
> You can try the newer release of 2.1.1

Thank you for the advice

**Comment by AquaSimulacra** [comment]
I have to say there are still same bugs when I used the newer version, however 4.0 is coming, let's see what genshin will change in their graphics.

**Comment by Rosaliyne** [comment]
> I have to say there are still same bugs when I used the newer version, however 4.0 is coming, let's see what genshin will change in their graphics.
I guess 4.0 will be an issue for modders as well as fps unlockers. The version will be very huge and complex.

**Comment by 34736384** [comment]
can be ignored
