### ISSUE TITLE
Locked at 60fps 

### ISSUE THREAD

**Issue by g-x-w** [34736384/genshin-fps-unlock#205]
Using latest version (release 2.1.1) on new fontaine release patch 4.0 and having similar issues to #178 where fps is uncapped up until door loads then drops to 60 and doesn't go any higher. Also on latest gpu driver version, so not sure what else it could be. Hardware is 7600X with 2070, on 1440 monitor. Any ideas?

![image](https://github.com/34736384/genshin-fps-unlock/assets/54957868/b226ebde-31b5-4a69-9879-f8e45517f9f6)

Settings:
![image](https://github.com/34736384/genshin-fps-unlock/assets/54957868/c58d374e-390d-4323-b46f-422f6e1ed963)
![image](https://github.com/34736384/genshin-fps-unlock/assets/54957868/a398de4c-3a6f-43c9-8700-7d9fb9276a7d)
NVIDIA control panel settings:
![image](https://github.com/34736384/genshin-fps-unlock/assets/54957868/b15d5e1b-3ca8-4ded-877f-694c2787064e)

**Comment by eternaljune** [comment]
I guess we should wait for update, it's cause of new patch.

**Comment by AquaSimulacra** [comment]
Not get what you are talking about, you should turn off auto turn off vsync and disable it in game manually. My unlocked works well.

**Comment by eternaljune** [comment]
It worked for me another way. I enabled VSync in game, turned off "Auto Disable VSync" in unlocker, and now it works.
![image](https://github.com/34736384/genshin-fps-unlock/assets/43187160/771e34c1-ff19-4039-a0c8-22cbcb72caac)

**Comment by xzorzx** [comment]
I tried both of your solutions, it doesn't want go past 60fps. I suppose I'll wait for an update !
I checked my nvidia control panel, vsync is off
in the unlocker I turned off the Auto Disable Vsync (since both of you have turned it off)
and ingame too, vsync is off. I also tried 'on'. Something else is limiting my framerate idk..
unless you have any other idea I could try ^^

**Comment by Raze876** [comment]
my autodisablevsync is false and in game vsync off, vsync in nvidia control panel also off, no problems

**Comment by g-x-w** [comment]
Okay so with 3 different binary vsync settings there should be 8 possible permutations, so here's my testing:

Genshin in-game = G, Unlocker = U, NVIDIA Control Panel = N, 1 = on, 2 = off

G  U  N  Works?
0   0   0     No
0   0   1     No
0   1   0     No
0   1   1     No
1   0   0     No
1   0   1     No
1   1   0     No
1   1   1     No

For the unlocker, Auto Disable VSync checked = 1, unchecked = 0.
Quit and reloaded game and unlocker twice for each attempt, running unlocker as administrator, none of these params gave me >60fps using FPSMonitor, fraps or RTSS. 

Since none of these parameterizations changed anything, it might point to it not being related to vsync at all, I'm thinking it's _possibly_ the visual C++ redist sinceie have 2015-2022 so I uninstalled that and reinstalled the 2015-2019 version just to check but that also didn't resolve it,

Any ideas?

**Comment by g-x-w** [comment]
Uninstalled the entire game and reinstalled and rebooted from cold start, still no luck. 

Would it potentially be an issue if I have a quadruple monitor setup with two of the monitor running at 165hz and the other two at 144hz?

**Comment by xzorzx** [comment]
I'm not sure if you've already checked whether some background programs were the issue or if you've install something else recently that could potentially "overwrite" your fps.
Like steam with overlay, something like that.

Generally, when the majority of players have no issue with the unlocker I'd question if it wasn't a human error like I did (I was running the wrong unlocker).

**Comment by BlueStarBRS** [comment]
still workin use the latest unlocker version.
