### ISSUE TITLE
fps drop when using 3dmigoto

### ISSUE THREAD

**Issue by 1q84ltd** [34736384/genshin-fps-unlock#208]
I am using fps unlock to get higher fps( >20). But, I have a question, it looks like when you using fps unlock + 3dmigo, it will drop 20-80 fps compare with using fps unlock alone. In addition,the fps is unstable when using 3dmigo+fps unlock

**Comment by BlueStarBRS** [comment]
Third Party isnt supported so it will not rin great i guess

**Comment by 34736384** [comment]
I have no plans to investigate compatibility issues with other software
