### ISSUE TITLE
Version update found. Please start the launcher to download the latest version. Log in after the completion of this update to immediately obtain 300 Primogems

### ISSUE THREAD

**Issue by cabronmafioso** [34736384/genshin-fps-unlock#211]
I've been using FPS unlocker successfully for a long time, but today for some reason it stopped working. It gives the error message: "Version update found. Please start the launcher to download the latest version. Log in after the completion of this update to immediately obtain 300 Primogems" once I click confirm, the game just crashes. 

My game is up to date and working normally without using FPS unlocker.

**Comment by AquaSimulacra** [comment]
You need to open the official launcher to update the game, then use unlocker.

**Comment by cabronmafioso** [comment]
@AquaSimulacra thanks. It's updated via launcher. I just double checked for game updates now, and it's the latest version

**Comment by cabronmafioso** [comment]
The issue was resolved. For some reason, I had 2 folders with different installations, I don't know how. Once I found it and updated the other version, it worked fine.
