### ISSUE TITLE
This tried to steal my account

### ISSUE THREAD

**Issue by naotyu8** [34736384/genshin-fps-unlock#216]
downloaded this 2 days ago and used it without issue, today for the first time in 3 years playing this game i got an email because someone tried to either log in my account or change my password. I got 2fa on cuz im not an idiot but this fps unlocker is not safe to use

**Comment by exciar** [comment]
no this does not steal your account if that's the case its probably something else
stop spreading misinformation

**Comment by 34736384** [comment]
let me guess, you probably didn't download from here
and you're retarded
so fuck off
thanks

**Comment by exciar** [comment]
truer words have been said

**Comment by BlueStarBRS** [comment]
> let me guess, you probably didn't download from here
> and you're retarded
> so fuck off
> thanks

Hahaha
