### ISSUE TITLE
No save button

### ISSUE THREAD

**Issue by amaangigani7** [34736384/genshin-fps-unlock#219]
I previous used to 75 fps, now I bump it up to 90, but everytime I have manually increase from 75 to 90, there is no save button to use the last used fps.

**Comment by jktrn** [comment]
@amaangigani7 There should be a configuration file that's automatically generated in the same directory as the executable is located called `fps_config.json`:

```json
{
  "DllList": [],
  "Priority": 1,
  "MonitorNum": 1,
  "CustomResY": 1080,
  "CustomResX": 1920,
  "FPSTarget": 240,
  "UsePowerSave": false,
  "StartMinimized": true,
  "IsExclusiveFullscreen": false,
  "UseCustomRes": false,
  "Fullscreen": true,
  "PopupWindow": false,
  "AutoClose": true,
  "AutoDisableVSync": true,
  "AutoStart": true,
  "GamePath": "C:\\Program Files\\Genshin Impact\\Genshin Impact game\\GenshinImpact.exe"
}
```

Ensure that the executable has proper write permissions on this file and that it's not read-only, etc.

**Comment by 34736384** [comment]
it should auto saves
