### ISSUE TITLE
version 4.0 is not working

### ISSUE THREAD

**Issue by SteveHe24** [34736384/genshin-fps-unlock#220]
Since today morning, the 4.0 version has not worked.

**Comment by GloomyNooby** [comment]
it's not working for me either, Whenever I launch the app it just says "outdated fps pattern"
![Screenshot 2023-08-31 121916](https://github.com/34736384/genshin-fps-unlock/assets/143742268/0cdc9e2c-8f76-4cfc-bd87-98901a716c51)

**Comment by half-drop** [comment]
try https://github.com/xiaonian233/genshin-fps-unlock

**Comment by trunghuyne** [comment]
:(((

**Comment by Spedemix** [comment]
Working fine here.

https://i.imgur.com/lQIURz8.png

**Comment by Kradziej** [comment]
Working no problem, maybe delete fps_config.json and try again?

**Comment by BlueStarBRS** [comment]
> it's not working for me either, Whenever I launch the app it just says "outdated fps pattern" ![Screenshot 2023-08-31 121916](https://user-images.githubusercontent.com/143742268/264727262-0cdc9e2c-8f76-4cfc-bd87-98901a716c51.png)

use latest version oyu open to wrong one
