### ISSUE TITLE
how to use dxvk in win10?

### ISSUE THREAD

**Issue by Licykoc** [34736384/genshin-fps-unlock#222]
I tried to use the latest unlockfps.exe to inject dxgi.dll and d3d11.dll but it gives me "CreateRemoteThread failed with code:5"

**Comment by Licykoc** [comment]
I have read about this [issue](https://github.com/34736384/genshin-fps-unlock/issues/35)

**Comment by Licykoc** [comment]
I have used the latest unlockfps.exe but it gives me "CreateRemoteThread failed with code:5"

**Comment by 34736384** [comment]
probably av issues
