### ISSUE TITLE
When using Genshin seems a bit washed out

### ISSUE THREAD

**Issue by danialzikri14** [34736384/genshin-fps-unlock#228]
![image](https://github.com/34736384/genshin-fps-unlock/assets/138662969/e7c7a717-6d81-4621-9dd6-884d1bb85c61)
This is Before

![image](https://github.com/34736384/genshin-fps-unlock/assets/138662969/d83fdd29-09a4-436c-87a6-47525010fb0b)
This is After

**Comment by BlueStarBRS** [comment]
maybe it is now native (or now no more) check if you have some window settings other than default.
if you use nvidea filters maybe its a bug on nvideas side

**Comment by danialzikri14** [comment]
> e

I used an AMD gpu but everything is normal. I even adjusted the brightness and it does not have any effects.

**Comment by danialzikri14** [comment]
> maybe it is now native (or now no more) check if you have some window settings other than default. if you use nvidea filters maybe its a bug on nvideas side

I used an AMD gpu but everything is normal. I even adjusted the brightness and it does not have any effects.

**Comment by danialzikri14** [comment]
I have fixed it by uninstalling Rectify11

**Comment by BlueStarBRS** [comment]
@danialzikri14  ist this not acomplete modded win11 os ?
