### ISSUE TITLE
Game capture makes the game look around 80fps

### ISSUE THREAD

**Issue by Wyzmic** [34736384/genshin-fps-unlock#23]
So I stream genshin from time to time and I cap my fps at 160 but it definitely doesn’t look or feel 160. I’ve checked using the fps overlay from msi afterburner and the fps is at a constant 160. When I don’t have any sort of display capture going, the game is perfectly fine. I have an rtx 3080ti and a 5900x, hardware isn’t a problem. My ingame settings are also maxed out. Anyone else had this happen?

**Comment by Elixcore** [comment]
just wanted to say without streaming with an rtx3060 and a 5600x my genshin caps at around 160fps on highest settings, it seems it's pretty badly optimized.

**Comment by Raymonf** [comment]
You're expecting way too much from an open-world Unity game, my dude.

**Comment by Wyzmic** [comment]
> just wanted to say that without streaming, with an rtx3060 and a 5600x my genshin caps at around 160fps on highest settings, it seems it's pretty badly optimized.

actually I’m capping it at 160 just to stay consistent, but in some areas it can push to around 240. It really is horribly optimized for frames higher than 120

**Comment by Wyzmic** [comment]
> You're expecting way too much from an open-world Unity game, my dude.

yeah I probably am. there’s definitely a reason why they don’t allow higher frames, most likely related to game inconsistencies and multi problems

**Comment by 34736384** [comment]
> So I stream genshin from time to time and I cap my fps at 160 but it definitely doesn’t look or feel 160. I’ve checked using the fps overlay from msi afterburner and the fps is at a constant 160. When I don’t have any sort of display capture going, the game is perfectly fine. I have an rtx 3080ti and a 5900x, hardware isn’t a problem. My ingame settings are also maxed out. Anyone else had this happen?

What are you using for streaming the game? If the streaming software supports capturing above 60 and receiving device is over 60hz then it should be the same as playing on the host

**Comment by Wyzmic** [comment]
> > So I stream genshin from time to time and I cap my fps at 160 but it definitely doesn’t look or feel 160. I’ve checked using the fps overlay from msi afterburner and the fps is at a constant 160. When I don’t have any sort of display capture going, the game is perfectly fine. I have an rtx 3080ti and a 5900x, hardware isn’t a problem. My ingame settings are also maxed out. Anyone else had this happen?
> 
> What are you using for streaming the game? If the streaming software supports capturing above 60 and receiving device is over 60hz then it should be the same as playing on the host

I've actually looked into it a bit more and it seems that OBS game capture cuts my frames almost in half. I don't have that issue with any other game. gpu is also hovering at about 60% while streaming, rec and playing genshin, cpu at around 50

**Comment by Spedemix** [comment]
Are you running OBS on a second screen that's not a VRR display or higher than 60 fps?

If yes, try minimizing OBS so there's no preview playback on the second screen. That might help.
