### ISSUE TITLE
30 FPS

### ISSUE THREAD

**Issue by Fearan1** [34736384/genshin-fps-unlock#230]
Hi 
I have a problem that I couldn't solve, the game run only at 30 FPS it don't go up nor down and no matter what I do either lowering or rising my setting, so I tried unlock hoping it will help yet it didn't and I don't know what I do now can someone help please?

to clarify: my monitor is 144 FPS and I disabled V-sync from Nvidia and inside the game too and made sure the game setting are 60 FPS.

**Comment by Spedemix** [comment]
Does the game run over 30fps if you boot it without fps-unlocker?

**Comment by 34736384** [comment]
It's probably your power settings
