### ISSUE TITLE
Not working on version 4.2 beta

### ISSUE THREAD

**Issue by hiddenz08** [34736384/genshin-fps-unlock#235]
My friend who is on the beta told me that this unlocker is currently not working on the 4.2 beta versionwith an error that says "outdated fps patern", the unlocker always worked on the previous betas. Just a heads up that once 4.2 officially comes out this unlocked will probably not work and need an update.

**Comment by 34736384** [comment]
beta has compiler changes that are not present in 4.2 live version, no update is needed for 4.2 live

**Comment by RealistikDash** [comment]
> beta has compiler changes that are not present in 4.2 live version, no update is needed for 4.2 live

VSync auto-disable does not work from my testing on the live version. Looks to need a signature update.
