### ISSUE TITLE
Is this unlocker considering updating the icon?

### ISSUE THREAD

**Issue by SakuraChanNya** [34736384/genshin-fps-unlock#236]
Because Genshin Impact version 4.2 has been updated, and its icon has changed to include the third anniversary. Is this unlocker considering updating the icon?

**Comment by exciar** [comment]
not really necessary and you can just replace the icon yourself
![image](https://github.com/34736384/genshin-fps-unlock/assets/139718583/cc111a91-0fa4-4a72-9538-da1de7588e3e)

**Comment by 34736384** [comment]
nope
