### ISSUE TITLE
When switching to other application display interfaces, the game will be stuck！

### ISSUE THREAD

**Issue by 17723319427** [34736384/genshin-fps-unlock#237]
When playing the game in full-screen mode, the game frame rate is set to 170Hz. When switching to other application display interfaces, the game will be stuck, and the system can only be logged out, and the task manager cannot be transferred.

**Comment by youngbe** [comment]
+1

**Comment by Licykoc** [comment]
the same problem

**Comment by 17723319427** [comment]
I've found a solution. Please deselect "Fullscreen" and "Popup Window" of "Options" in the frame rate unlocking software, and you can only set the full-screen mode in the game. There may be compatibility issues with the full-screen mode of this framerate unlocking software. @youngbe @Licykoc

**Comment by 17723319427** [comment]
https://github.com/34736384/genshin-fps-unlock/issues/92
