### ISSUE TITLE
stuttering keeps happening for no apparent reason

### ISSUE THREAD

**Issue by copyvw** [34736384/genshin-fps-unlock#238]

**Comment by bean789** [comment]
you'll probably notice it starts after diving underwater in Fontaine. 

it's a bug introduced in 4.0. I'm hoping for a fix and I wonder if it happens on Apple devices that run 120 fps too

**Comment by CirnoSalt** [comment]
#215 This is a bug triggered by the game itself and has been going on for two versions now, it is recommended that feedback be given to HoYoverse for a speedy resolution, for now it can only be temporarily mitigated by lowering the rendering resolution to "0.6" & "1.0" in the game's settings (which may vary for different monitor resolutions).

**Comment by CirnoSalt** [comment]
There is already a solution to this problem:
https://github.com/34736384/genshin-fps-unlock/issues/215#issuecomment-1806857015
