### ISSUE TITLE
Need to Update as failed to fine ReadToEnd

### ISSUE THREAD

**Issue by Stormanzanii** [34736384/genshin-fps-unlock#243]
Game launches, but keeps telling me thats it needs to update even thought both Genshin and the UnlockFPS are both the highest versions. Any clue on how i could possibly fix this? (reference down below.)

![image_2023-10-19_191743781](https://github.com/34736384/genshin-fps-unlock/assets/145221345/86e27aeb-600b-4b04-9adc-49d8fabcbb01)

**Comment by 34736384** [comment]
That's not even a part of the unlocker, it's the rsa patch for private servers, delete version.dll in the game folder

**Comment by Stormanzanii** [comment]
Wait, so can this be used on official Genshin or only modded/private servers?

**Comment by 34736384** [comment]
You're not understanding, you've used private servers before, and the files dropped by private server launchers did not get cleaned up. It has nothing to do with fps unlocker
