### ISSUE TITLE
客户端组件运行异常，请重新启动客户端

### ISSUE THREAD

**Issue by chashao33** [34736384/genshin-fps-unlock#244]
错误码：10259-4001
今天突然出现的弹窗报错，以前没遇到过。
在秘境里面和刚出秘境的时候非常容易触发。这个弹窗出来后就强制回到开门的登录界面了。

**Comment by chashao33** [comment]
今天又试了试，与genshin-fps-unlock无关，与秘境无关。只要用了五郎速射产生了伤害，1分钟左右必定会弹这个报错，用官方启动器60帧也会弹这个。

**Comment by tutuhl** [comment]
今天用了五狼速射就显示客户端组件运行异常，然后回到登录界面

**Comment by 281069483** [comment]
霄宫的也不能用了，看来是米哈游不让用了，有没有大佬解决这个问题的？

**Comment by chashao33** [comment]
我用云原神试了下也是一样的报错，已经在米游社提交问题反馈了，不知道官方会不会修。

**Comment by Zegic** [comment]
草，宵宫也不能用了，这下宵宫彻底fw了

**Comment by chashao33** [comment]
我不用宏，纯手按大概每秒射5次，都会弹这个。客户各种打马虎眼就是不给正面回复。
