### ISSUE TITLE
When video playing on second monitor, fps caps at 60

### ISSUE THREAD

**Issue by hiro-osu** [34736384/genshin-fps-unlock#247]
Pretty much the title, whenever a video is playing on second monitor, the fps is capped at 60. altough it only does that when the video is showing in the screen; if I change tabs or even scroll down it goes back to 120fps. any way to solve this? My second monitor is 60hz btw, not sure if it plays a factor

**Comment by lennysleo** [comment]
If you do something hardware accelerated on your second monitor, such as playing a video, both monitors will be capped to the lowest refresh rate. This is the result of a driver issue. You can try disabling hardware accelereation of the browser you are using to watch the video.

**Comment by ipisano** [comment]
Try checking "Auto-disable Vsync", Fullscreen, setting window mode to Exclusive. I didn't have the exact same issue as you do but in borderless if I have a video playing on my 2nd screen I get stutters in the game that are not detected by RTSS's frametime graph but is definitely present.
Also if you're using Free/G-Sync on both monitors disable it on the 2nd one.

**Comment by hiro-osu** [comment]
> If you do something hardware accelerated on your second monitor, such as playing a video, both monitors will be capped to the lowest refresh rate. This is the result of a driver issue. You can try disabling hardware accelereation of the browser you are using to watch the video.

It actually worked! Thank you so much, this problem was getting on my nerves. Really appreciate it
