### ISSUE TITLE
Version 4.2 Incompatibility

### ISSUE THREAD

**Issue by TheLonelyDevil9** [34736384/genshin-fps-unlock#248]
Hi there,

The fps unlocker doesn't seem to be working with the 4.2 update.

Just raising it for visibility, I'll wait for an update as I'm sure everyone else will.

Thanks.

**Comment by ipisano** [comment]
Looks like it works to me!
I've disabled vsync and chose exclusive fullscreen, set FPS cap set to 360 in the unlocker and I have RTSS capping the game at 143.990.

Note that I didn't change any settings from 4.1, I'm running exclusive fullscreen because in borderless if I have a video playing on my 2nd screen I get stutters in the game that are not detected by RTSS's frametime graph but is definitely present.

**Comment by weebly9** [comment]
Just want to add as well that I'm also successfully running the game uncapped with no settings modifications from 4.1.
Personally, I have the unlocker set to 144fps with RTSS capping to 120fps, borderless fullscreen (I think) and V-Sync off.

**Comment by whitfield-lyx** [comment]
Actually, It also seems to not work for me with 4.2 update. Also, i did not change any settings from 4.1.

**Comment by Gatoz97** [comment]
It is working for me, Windows 10.
But the smoothness is inconsistent, sometimes it's butter smooth, other times is choppy and stuttery as hell without changing anything.
I set max uncap of 360 and limit it to 144 via RivaTuner, monitor is 144hz, I use both Nvidia Vsync and in-game Vsync. I hate screen tearing.

**Comment by sonicjhon1** [comment]
For me, 
- The login door: FPS is unlocked, 
- In-game: FPS is locked at 60,
- Pausing the game: FPS is locked at 60,
- Opening Map UI: FPS is unlocked, 
- Opening Mail / Settings / Any fullscreen UIs: FPS is unlocked.

Didn't touched anything after updated to 4.2:
### **General**
- VSync disabled
- Game process priority: Above normal

### **Launch Options**
- Fullscreen
- Custom Resolution: 3480x1200
- Borderless

**Comment by blmarket** [comment]
Should we open another issue to discuss? I'm using some Linux environment where the launcher provides unlocker integration, and start to experience FPS 60 limit after 4.2 patch.
