### ISSUE TITLE
Potential warning/heads up in advance for 4.3

### ISSUE THREAD

**Issue by RahuX** [34736384/genshin-fps-unlock#249]
From leaks of the beta client, [4.3 seems to be adding in a lot of QoL changes to the game so far.](https://imgur.com/a/JOe7kSG) Obviously these are all subject to change, so maybe some of these won't make it into the final update.

However, there is one QoL update that's simply been listed by leakers as being a "game resource anomaly prompt", which upon being triggered just forces the game to close. There's no info on how exactly this is triggered, or if it does anything more than described (say flag accounts that trigger this) but the obvious implications are this could certainly affect modding in general. And given how this FPS unlocker works, I see it potentially, if not certainly, triggering this prompt.

At best, assuming the unlocker does trigger this, I see it being an annoyance until the mod is updated to bypass this prompt. At worst, if this does end up flagging accounts, then we could see this being the day we've all dreaded of Hoyo actually banning accounts for using this.

As such, assuming this change does make it into final, then this just serves as a notification to the developer of needing to potentially update the unlocker if possible, as well as a potential caution point to users to maybe not use the mod once 4.3 drops.

**Comment by 34736384** [comment]
4.2 beta had changes that weren't brought into 4.2 live, so I'll assume that's what gonna happen for 4.3
I care less about any leaks
