### ISSUE TITLE
Issue with VSync disabler after 4.2.

### ISSUE THREAD

**Issue by RealistikDash** [34736384/genshin-fps-unlock#251]
From my brief experimentation after the release of 4.2, the FPS cap cannot exceed your main monitor's refresh rate. In short, the VSync disabler does not seem to be working correctly/at all (reproduced on multiple machines). *This is likely the source of all of the confusion regarding 4.2 support, as not many people go beyond their refresh rate.*

From my minimal testing, this seems to be as simple as updating the VSync signature, which seems to have gotten changed.

**Comment by RahuX** [comment]
If you're talking about the setting not disabling the in game V-Sync when enabled, while that is an issue, it's really just meant as a setting to automatically set the in game setting to "off" from what I understand. At least that was the case for me when I've tried the setting before.

So the desired result "having v-sync set to off" should just be achievable by just changing it in game, regardless of if the setting is enabled or disabled in the unlocker.

Just to prove this, I did some testing myself. Unlocker has the "auto vsync disabled" setting disabled, in game vsync is disabled (and my testing shows this setting is saved upon restarting the game), and I set the FPS cap to 240. Went into my teapot to give the game as much headroom as possible to run over the 144hz refresh rate of my monitor. Overlay is from Special K.

![image](https://github.com/34736384/genshin-fps-unlock/assets/5471553/15e69a4c-7d43-4cbf-bbd1-d5d29be3fd76)

As you can see, at least for me, the game renders past 144 FPS no problem.

**Comment by 34736384** [comment]
Removed in new version, just turn off vsync manually
