### ISSUE TITLE
Make Genshin fullscreen mode after every time it starts up?

### ISSUE THREAD

**Issue by MegaMan0429** [34736384/genshin-fps-unlock#253]
With the FPS Unlocker, the game starts up in windowed mode. Is there a way to make it start fullscreen mode everytime I launch the game with the FPS Unlocker?

**Comment by lvuna** [comment]
In the fps_config file generated by the program, set the `fullscreen` and `IsExclusiveFullscreen` to true

**Comment by 34736384** [comment]
there's a settings window......
