### ISSUE TITLE
unlockfps_clr.exe got malicious warning from virustotal scan

### ISSUE THREAD

**Issue by fxavierho123** [34736384/genshin-fps-unlock#254]
![screencapture-virustotal-gui-file-cbe404e97faa75d2aafbfff617c4ed980e1948cbcab17fe6b7f18544f8165e73-2023-11-25-19_35_42](https://github.com/34736384/genshin-fps-unlock/assets/93583076/6b1406f9-1008-4902-8ecc-41151ef5d85c)

**Comment by 34736384** [comment]
and?
