### ISSUE TITLE
can it be made into a windows service?

### ISSUE THREAD

**Issue by is-a-gamer** [34736384/genshin-fps-unlock#255]
i am not a professional developer, unlock fps necessarily require this program to start genshin? or alternatively, you can detection `yuanshen. exe` and make modifications after starting the program

then we can set it as a windows service,start on windows boot

In this way, we don't have to manually start `unlock_fps` every time before starting `Genshin Impact`

if possible, i would greatly appreciate it

if not possible, i apologize for asking foolish issue

**Comment by shiiirro** [comment]
Try task scheduler.

**Comment by 34736384** [comment]
if you want to start on boot, just create a shortcut to the startup folder
and yes it does require the unlocker to start the game
