### ISSUE TITLE
A warning window appears saying that a virus has been detected in the new version.

### ISSUE THREAD

**Issue by nyaaso** [34736384/genshin-fps-unlock#258]
![image](https://github.com/34736384/genshin-fps-unlock/assets/60265428/a1b4912e-c9d9-42e6-a913-9ccfec2f8834)

It says that the newly uploaded version has a virus detected.

It is also detected by Windows Defender, so it appears that a fix is needed.

**Comment by 34736384** [comment]
no fix is needed
