### ISSUE TITLE
Windows reporting virus?

### ISSUE THREAD

**Issue by Shekkels** [34736384/genshin-fps-unlock#259]
have been using the unlocker for just over 2 years and windows has started saying its a virus and not letting me launch genshin, tried the most recent version and the one before and im getting the same report

**Comment by 34736384** [comment]
whitelist it or build it yourself

**Comment by NavyShark02** [comment]
![image](https://github.com/34736384/genshin-fps-unlock/assets/153530756/c5b12ca5-036f-4c56-8038-4a019a1b99e8)
