### ISSUE TITLE
A way to add parameters in the .exe

### ISSUE THREAD

**Issue by LordRene93** [34736384/genshin-fps-unlock#26]
Hello, since I have so many sttutering problems with the game, I use a shortcut with parameters that avoid having them. It would be nice if your app allowed to use shortcuts instead of the original .exe, or a way to add the parameters like Steam.

**Comment by DeltaMarine101** [comment]
I agree, having the ability to add launch options would be great. I use "-popupwindow" to get fullscreen borderless windowed mode, but I can't get it to work with this awesome tool.

**Comment by 34736384** [comment]
launch parameters is already supported, just pass it to the unlocker via command line or shortcut

**Comment by LordRene93** [comment]
> launch parameters are already supported, just pass it to the unlocker via command line or shortcut

Oh thanks. I didn't realize that I could do that. Then I will close the "Issue".
