### ISSUE TITLE
version 2.1.3 (.EXE) not downloadable 

### ISSUE THREAD

**Issue by dani-jen** [34736384/genshin-fps-unlock#263]
The .EXE is not downloadable via Microsoft Edge or Google Chrome due to "Virus detected".

**Comment by diepquynh** [comment]
Yeah Windows Defender is being extremely lolz today. Few hour ago it didn't trigger this warning, then I reinstalled Windows due to some random Windows Update bugs and here we are
![image](https://github.com/34736384/genshin-fps-unlock/assets/13411810/9ac00c8a-c220-48ff-84c3-edbb9946fdc7)

**Comment by 34736384** [comment]
duplicate, closed
