### ISSUE TITLE
可以考虑一下增加指定启动参数的功能吗

### ISSUE THREAD

**Issue by AizawaHikaru233** [34736384/genshin-fps-unlock#268]
use_mobile_platform -is_cloud 1 -platform_type CLOUD_THIRD_PARTY_MOBILE

**Comment by AizawaHikaru233** [comment]
以上是PC原神使用移动端UI的启动参数，大佬可以增加自定义启动参数或者干脆把这个功能集成进fpsunlock呢？目前我暂时尅找到可以同时解锁帧率和使用这个参数的办法

**Comment by 34736384** [comment]
可以

**Comment by zurce** [comment]
> use_mobile_platform -is_cloud 1 -platform_type CLOUD_THIRD_PARTY_MOBILE

Is there any list of the startup parameters? where did you get this? I wonder if there's a way to force Playstation Icons on PC, then we could just Xbox emulation to get vibration working again
