### ISSUE TITLE
Trojan detected on the latest release

### ISSUE THREAD

**Issue by bruhletmepickausername** [34736384/genshin-fps-unlock#280]
Be careful

**Comment by 34736384** [comment]
duplicate, closed

**Comment by bruhletmepickausername** [comment]
> duplicate, closed

Whatever you say man, it never gave 'false positives' and this is the first time. Won't be using it for now, what a shame.

**Comment by 34736384** [comment]
> > duplicate, closed
> 
> Whatever you say man, it never gave 'false positives' and this is the first time. Won't be using it for now, what a shame.

don't care, and learn how to properly ask questions before you lay your hands on the keyboard again
