### ISSUE TITLE
Issue you with the new version

### ISSUE THREAD

**Issue by Subarashill** [34736384/genshin-fps-unlock#282]
I just scanned the new ver of the fps unlocker in virustotal and it has something weird called "ArcSight Threat Intelligence" marked as suspicious is it safe to download it? Just wanted to make sure cuz I don't know if it were false positive

**Comment by 34736384** [comment]
false positive, ignorable

**Comment by bogdan-lamba** [comment]
> false positive, ignorable

How? Windows defender just insta deletes it.

**Comment by 34736384** [comment]
> > false positive, ignorable
> 
> How? Windows defender just insta deletes it.

ask google
