### ISSUE TITLE
Error : Outdated FPS Pattern

### ISSUE THREAD

**Issue by DocZeus** [34736384/genshin-fps-unlock#287]
Just started appearing after the new 4.3 patch dropped. It limits the game back to 60fps. Requesting to resolve this issue please.
![image](https://github.com/34736384/genshin-fps-unlock/assets/66434877/0f99635b-0ecc-485b-8120-44ea521f4f7b)

**Comment by 34736384** [comment]
duplicate

**Comment by DocZeus** [comment]
> duplicate

ok, but how to solve?

**Comment by 34736384** [comment]
> > duplicate
> 
> ok, but how to solve?

download the new version yourself?
