### ISSUE TITLE
Why won't microsoft let me download v2.2.1???

### ISSUE THREAD

**Issue by spzwohra4** [34736384/genshin-fps-unlock#289]

**Comment by 34736384** [comment]
false positive, whitelist it yourself

**Comment by spzwohra4** [comment]
but I can't find where to

**Comment by 34736384** [comment]
> but I can't find where to

ask google

**Comment by Nerbless** [comment]
> but I can't find where to

I fixed this by downloading the file in Windows Sandbox then copy pasting it over

**Comment by 34736384** [comment]
> > > but I can't find where to
> > 
> > 
> > I fixed this by downloading the file in Windows Sandbox then copy pasting it over
> 
> Thanks, I've fixed it by turning real-time protection off. <img alt="image" width="1280" src="https://private-user-images.githubusercontent.com/136093930/291873171-f9366a58-6174-4d24-82da-5a96bfc4262b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNzEzMDksIm5iZiI6MTcwMzA3MTAwOSwicGF0aCI6Ii8xMzYwOTM5MzAvMjkxODczMTcxLWY5MzY2YTU4LTYxNzQtNGQyNC04MmRhLTVhOTZiZmM0MjYyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQxMTE2NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDY5NDI2ZGE2Y2YzYmI3NGEyY2NlYTRkYTM5YWE1ZTc1N2ZmYThiN2M0NWUwZTUxZDVkNDgyNjkxYmE1MDVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s9KXfJMutM8cEkdqterAozTekcI0u0TFI3qnw_dp3zk">

please don't do that, only whitelisting the unlocker exe is good enough

**Comment by spzwohra4** [comment]
> > > > but I can't find where to
> > > 
> > > 
> > > I fixed this by downloading the file in Windows Sandbox then copy pasting it over
> > 
> > 
> > Thanks, I've fixed it by turning real-time protection off. <img alt="image" width="1280" src="https://private-user-images.githubusercontent.com/136093930/291873171-f9366a58-6174-4d24-82da-5a96bfc4262b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNzEzMDksIm5iZiI6MTcwMzA3MTAwOSwicGF0aCI6Ii8xMzYwOTM5MzAvMjkxODczMTcxLWY5MzY2YTU4LTYxNzQtNGQyNC04MmRhLTVhOTZiZmM0MjYyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQxMTE2NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDY5NDI2ZGE2Y2YzYmI3NGEyY2NlYTRkYTM5YWE1ZTc1N2ZmYThiN2M0NWUwZTUxZDVkNDgyNjkxYmE1MDVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s9KXfJMutM8cEkdqterAozTekcI0u0TFI3qnw_dp3zk">
> 
> please don't do that, only whitelisting the unlocker exe is good enough

it's ok, i turned it back on immediately after i downloaded the unlocker.
