### ISSUE TITLE
v2.2.0 release .exe being detected by Windows Defender as trojan

### ISSUE THREAD

**Issue by ypcpaul** [34736384/genshin-fps-unlock#290]
See attached screenshot. Previous version wasn't detected as such, but this one gets detected by Windows Defender the moment I downloaded it.

![unlocker-trojan](https://github.com/34736384/genshin-fps-unlock/assets/982576/cdbfb7bf-52ad-486f-94a8-eb41667881ba)

**Comment by 34736384** [comment]
duplicate, already addressed in closed issues
