### ISSUE TITLE
windows defender and google chrome prevent v2.2.0 exe file download

### ISSUE THREAD

**Issue by ha-Jong-ho** [34736384/genshin-fps-unlock#291]
windows defender report that Program:Win32/Wacapew.C!ml
and delete v2.2.0 unlockfps_clr.exe

there was no issue before versions
maybe something wrong while build exe file

here i rebuild file from exactly same source code
[unlockfps_clr.zip](https://github.com/34736384/genshin-fps-unlock/files/13726910/unlockfps_clr.zip)

**Comment by ypcpaul** [comment]
Same for me

![unlocker-trojan](https://github.com/34736384/genshin-fps-unlock/assets/982576/29d011ef-a179-42a3-8c6b-17352e40eda9)

**Comment by 34736384** [comment]
duplicate, closed
