### ISSUE TITLE
Detected as Trojan:Win32/ScarletFlash.A

### ISSUE THREAD

**Issue by cjfghd21** [34736384/genshin-fps-unlock#300]
Windows sees the executable as threat and automatically removes it.
![issue](https://github.com/34736384/genshin-fps-unlock/assets/60458858/84327a31-ec35-40d2-9043-3a2630a678a0)

**Comment by 34736384** [comment]
https://github.com/34736384/genshin-fps-unlock/discussions/296
https://github.com/34736384/genshin-fps-unlock/issues/292
