### ISSUE TITLE
能否增加延迟选项以避免“ReadProcessMemory或WriteProcessMemory”错误

### ISSUE THREAD

**Issue by zhouym233** [34736384/genshin-fps-unlock#307]
某一次更新AMD显卡驱动后，每次启动原神都会弹出这个错误提示。
![image](https://github.com/34736384/genshin-fps-unlock/assets/26868483/f49c018d-e3bf-453f-b4de-9ef6aa86bbec)
疑似是因为客户端启动变慢了，但是genshin-fps-unlock在原神客户端未完全启动时就修改内存，引起报错。
每次都需要切回桌面确认该弹窗后genshin-fps-unlock才能重新生效。
能否提供选项允许推迟数秒钟后再修改fps上限，避免报错？

**Comment by ghost** [comment]
作者可能是没空修 问就让人忽略 
每次都弹窗嫌烦先用这个吧 这个不报错  https://github.com/xiaonian233/genshin-fps-unlock

**Comment by 34736384** [comment]
已修
