### ISSUE TITLE
Game gets jittery at Hydro Tulpa boss area

### ISSUE THREAD

**Issue by wq2e2eqewqweq** [34736384/genshin-fps-unlock#311]
So I teleported to hydro tulpa boss and after i tp'ed character movement gets jittery which feels like my character is moving at 20 fps. Also tried to tp away and I noticed that the map stays smooth and it does go away after I tp away from hydro tulpa boss

**Comment by Raijin221** [comment]
he said he is rewriting and it will be done in 2 days, 3 days ago it so it shouldn't take much longer

**Comment by 34736384** [comment]
https://github.com/34736384/genshin-fps-unlock/issues/104#issuecomment-1342992315
