### ISSUE TITLE
Auto HDR not working in version 3.0.0

### ISSUE THREAD

**Issue by Jake0071945** [34736384/genshin-fps-unlock#313]
the game wont wont start at fullscreen and Auto HDR doesn't work with the new version had to rollback to older version.

UPDATE: Auto HDR still doesn't work with version 3.0.2

**Comment by rockenren** [comment]
Try version 3.0.1.

**Comment by tuanminh26596** [comment]
I had the same problem of not running in full screen on startup (Already check Fullscreen in app ). And when the program minimizes, it cannot be opened again. I'm still very happy and grateful because with the latest updated version I can use the app again.
