### ISSUE TITLE
After minimizing, cannot open any more, see issue #257

### ISSUE THREAD

**Issue by Purgepyro** [34736384/genshin-fps-unlock#316]
see issue #257

**Comment by 34736384** [comment]
works fine, can't reproduce

**Comment by Purgepyro** [comment]
![image](https://github.com/34736384/genshin-fps-unlock/assets/98635189/349f691f-abab-4ea9-bbc0-e5432e9d91ea)

**Comment by 34736384** [comment]
again, can't reproduce

**Comment by Purgepyro** [comment]
Are you using windows 11?
I will give you a recording.

**Comment by Purgepyro** [comment]
[2023-12-26 18-04-07.zip](https://github.com/34736384/genshin-fps-unlock/files/13770642/2023-12-26.18-04-07.zip)

**Comment by Purgepyro** [comment]
I suspect it is because after I click the button in the taskbar, the program still maintain the minimize state.

**Comment by 34736384** [comment]
should be fixed now

**Comment by Purgepyro** [comment]
Appreciate your work!
