### ISSUE TITLE
3.0.2 doesn't work with bilibili version

### ISSUE THREAD

**Issue by CarterLi** [34736384/genshin-fps-unlock#317]
I have a bilibili account. Surprisingly, If I run unlockfps_nc.exe with my bilibili version of GI, it shows the official login form.

**Comment by aquawius** [comment]
Same Problem on bilibili Server on using .net core version fps_unlocker

**Comment by s4e09** [comment]
I‘ve got totally same situation. It just opened an mihoyo version login ui but not my bilibili login ui.

**Comment by 34736384** [comment]
Will be fixed

**Comment by 34736384** [comment]
should be fixed
