### ISSUE TITLE
Still WD virus detection Windows 11 (Trojan:Win32/AgentTesla!ml)

### ISSUE THREAD

**Issue by Jonyee04** [34736384/genshin-fps-unlock#319]
I know this is a false positive but even if i put the file to exclusion in WD it still blocks the file

**Comment by win98se** [comment]
Please send a report on https://www.microsoft.com/en-us/wdsi/filesubmission. I did the same few days ago for v2.2.0.

![image](https://github.com/34736384/genshin-fps-unlock/assets/11819816/b163ef22-0afc-49f4-bd51-3e71f6a367f4)
