### ISSUE TITLE
is it safe to run unlockfps_nc.exe in this scenario

### ISSUE THREAD

**Issue by progenitorstardust** [34736384/genshin-fps-unlock#325]
my firewall threw a fit upon opening the program twice. unlockfps_nc.exe attempts to modify the following file

> DRIVE:/Windows/System32/HoYoKProtect.sys

i excluded the executable from my firewall but the issue was still present for the next few startups. after some time passed, the executable no longer triggered the warning from my firewall. i removed the executable from exclusion to attempt to recreate the issue i had on my first run of the program, but it still did not trigger the warning.
is it still safe to run unlockfps_nc.exe? is hoyokprotect.sys always modified on startup? is something still interfering with the program?

**Comment by 34736384** [comment]
https://github.com/34736384/genshin-fps-unlock/discussions/318
