### ISSUE TITLE
GSync Issues with v3.0.2

### ISSUE THREAD

**Issue by nwoltman** [34736384/genshin-fps-unlock#327]
GSync is no longer working properly with v3.0.2. My monitor says it's always running at the maximum refresh rate even if I set the target fps lower and even when I go to places in the game where I normally see fps drops (instead I see stutters now).

This makes me think that either Fullscreen Exclusive mode is no longer working or the in-game VSync is no longer being disabled (which would cause the game to lock its refresh rate to my monitor's max refresh rate).

**Comment by frankxu2004** [comment]
I am experiencing the same problem. Gsync worked on 2.2.0 version, but now with 3.x version, it didn't work no matter if it's fullscreen exclusive or borderless

**Comment by Raezifed** [comment]
Can confirm this issue, G-SYNC isn't working on 3.0.2.

**Comment by Purgepyro** [comment]
I also notice that the game is not as smooth as in the 2.2.0 version, did you feel that?

**Comment by Purgepyro** [comment]
> GSync is no longer working properly with v3.0.2. My monitor says it's always running at the maximum refresh rate even if I set the target fps lower and even when I go to places in the game where I normally see fps drops (instead I see stutters now).
> 
> This makes me think that either Fullscreen Exclusive mode is no longer working or the in-game VSync is no longer being disabled (which would cause the game to lock its refresh rate to my monitor's max refresh rate).

Actually if you are using 2.2.0 or below, you can turn on vsync in the game because that won't affect the launcher while giving a smoother experience.

**Comment by AquaSimulacra** [comment]
> I also notice that the game is not as smooth as in the 2.2.0 version, did you feel that?

I do confirm that. Here is the test way:

**Comment by Purgepyro** [comment]
> I am experiencing the same problem. Gsync worked on 2.2.0 version, but now with 3.x version, it didn't work no matter if it's fullscreen exclusive or borderless

I totally confirm this issue, here is the test way:
1. Launch NVIDIA Control Panel.
2. Click on Display (See the picture below)
![Screenshot 2023-12-29 235527](https://github.com/34736384/genshin-fps-unlock/assets/98635189/c8fb3038-1f64-43ed-ba3d-0010d9099d9b)
3. Check "G-SYNC (Compatible) Indicator" option
4. Launch the Game with version 2.2.0 and 3.0.2 respectively
5. While using 2.2.0
![原神 2023-12-29 23_51_22](https://github.com/34736384/genshin-fps-unlock/assets/98635189/a47d2f9c-7925-4364-8c64-e3a972885cbf)
6. While using 3.0.2
![原神 2023-12-29 23_52_58](https://github.com/34736384/genshin-fps-unlock/assets/98635189/294ab726-02c4-479a-9b4d-96d122c15661)
Check the top right corner of the two pictures above, and you can see the difference!
My suggestion is to revert to 2.2.0

**Comment by Purgepyro** [comment]
@nwoltman Suggest close this issue since 3.0.3 fixed the problem.

**Comment by nwoltman** [comment]
Yes, it's fixed in 3.0.3
