### ISSUE TITLE
FPS unlocker not working after updating to .NET 8.0.0 on GNU/Linux

### ISSUE THREAD

**Issue by Tearlyn** [34736384/genshin-fps-unlock#330]
OS specifications:
Arch Linux 
6.6.8-arch1-1 
i5-11400F 
RX 570 
16 GiB

FPS unlocker is  opening with an error to install .NET 8.0.0, even after already installed requirements.
Is there any solution for this problem? Thanks in advance.

Screenshot of the problem:
![Screenshot from 2023-12-31 09-35-46](https://github.com/34736384/genshin-fps-unlock/assets/83766904/65e3c7e7-ea9b-463f-bea1-6c51f9984d52)

**Comment by 34736384** [comment]
You'll probably need to ask the linux community instead
