### ISSUE TITLE
VSync AutoDisable

### ISSUE THREAD

**Issue by Akky99** [34736384/genshin-fps-unlock#34]
Hi, somehow my PC always got a problem (in general) with Vsync, if it's disabled games are always very laggy.
I have a 75hz monitor and i wanted to play genshin with 75fps instead of 60fps. 
I downloaded the last version of "genshin-fps-unlock" (1.4.0), and game was laggy, i instantly new vsync autodisabled was the problem. I then searched for a lower version (1.2.0) without vsync autodisable, worked like a charm, 75fps ingame with no lags.
So my question is, is there a way to avoid the vsync autodisable on the newer/s versions?

**Comment by Computron010** [comment]
I also have a 75Hz monitor and despite me changing the target FPS value to 75, I experience very frequent stuttering. The PR I created allows you to control VSync from `config.ini`, and brings smooth gameplay to me.

**Comment by 34736384** [comment]
https://github.com/34736384/genshin-fps-unlock/releases/tag/v1.4.2
