### ISSUE TITLE
How do i uninstall this? 

### ISSUE THREAD

**Issue by VN135766** [34736384/genshin-fps-unlock#340]
it made my game really choppy, won't go above 10 FPS now, i deleted the exe file and i thought that was that but i opened my game and it's still really choppy.

**Comment by SammyDeAgent** [comment]
> it made my game really choppy, won't go above 10 FPS now, i deleted the exe file and i thought that was that but i opened my game and it's still really choppy. 

Just to clarify, this is a FPS Unlocker, not a FPS Booster. 

A possible solution would be to verify the file integrity, reinstall the game, driver update etc.

...

Or consider upgrading your PC rig.
