### ISSUE TITLE
Why there is a title bar?

### ISSUE THREAD

**Issue by pengzhenghao** [34736384/genshin-fps-unlock#343]
<img width="1000" alt="屏幕截图 2024-01-21 064003" src="https://github.com/34736384/genshin-fps-unlock/assets/22206995/90a8a2e9-95fd-48fb-ac62-94d8fd7e87b9">

As you can see there, when opened with the unlocker, the window always has a title bar there. I have to go to the setting, change the window size to something smaller, and set it back to 4K so that the title bar would disappear. Does anyone has any idea on how to solve this? Thank you! It's quite annoying that everytime I login I have to go to the setting menu.

**Comment by 34736384** [comment]
https://github.com/34736384/genshin-fps-unlock/issues/98
