### ISSUE TITLE
Movable window during Borderless Window Mode

### ISSUE THREAD

**Issue by baghasseto** [34736384/genshin-fps-unlock#349]
![Untitled](https://github.com/34736384/genshin-fps-unlock/assets/144531728/cb4c3d04-9a09-4cde-990d-55d0a0a149a6)

my problem is that it always starts at the middle, without being able to move it to the bottom, or to the top

only happened if i tick borderless window mode.

is there still a way to do that? thank you for the hard work...the apps is much more useful now not just as fps unlocker

**Comment by 34736384** [comment]
that's how a borderless window is supposed to work, it doesn't have controls for changing window location by default
