### ISSUE TITLE
10fps lock

### ISSUE THREAD

**Issue by Arxomod** [34736384/genshin-fps-unlock#350]
Is there any way I can remove the 10 fps lock when switching to a second monitor?

**Comment by Arxomod** [comment]
1st monitor
![image](https://github.com/34736384/genshin-fps-unlock/assets/158301937/6a221e63-ca5b-4d1c-a0f0-ecdd1ceb18e3)
and when i click on 2nd monitor it's locks on 10fps
![image](https://github.com/34736384/genshin-fps-unlock/assets/158301937/e745314e-6f4d-4b89-aba7-cf2b1baefee0)

**Comment by Arxomod** [comment]
![image](https://github.com/34736384/genshin-fps-unlock/assets/158301937/10cf3b39-80fc-4fb3-8161-062260b8494c)
there is my settings

**Comment by 34736384** [comment]
![image](https://github.com/34736384/genshin-fps-unlock/assets/25654009/210551aa-5510-4dc9-ab37-39c90fc01a6c)

**Comment by Arxomod** [comment]
oh mb, i dumb, tyvm
