### ISSUE TITLE
Unlocker doesn't launch on Linux through WINE/PROTON after 3.0 update (dotnet 8.0.0)

### ISSUE THREAD

**Issue by Rodzioo** [34736384/genshin-fps-unlock#353]
I installed .NET 8.0 on my wine prefix but it just crashes. Pre 8.0 .NET versions of unlocker worked fine. Here's log below.

https://pastebin.com/cR7W7fJu

**Comment by ronhombre** [comment]
You might be using the wrong DLL if it's not finding something

**Comment by Rodzioo** [comment]
Which dlls should I replace with winetricks?

**Comment by ronhombre** [comment]
> Which dlls should I replace with winetricks?

```
System.EntryPointNotFoundException: Unable to find an entry point named 'GetThreadDpiHostingBehavior' in DLL 'USER32.dll'.
```

It's in the log

**Comment by aamaanaa** [comment]
what command did u use to install dotnet 8.0 ?

**Comment by Rodzioo** [comment]
> what command did u use to install dotnet 8.0 ?

I did just by using wine, since winetricks doesn't seem to support installing 8.0 as of now. Strangely most apps <= dotnet7 seemed to work out of the box and the problem is only on net8. I tried troubleshooting it by myself, that is setting some dlls to native, then built in and the other way around but without much success

**Comment by CrazyStevenz** [comment]
@Rodzioo This was fixed [here](https://bugs.winehq.org/show_bug.cgi?id=55892), so if you use any Wine on or after version 9.0-rc1, this should work again (tested by me with GE-Proton9-1). This issue can be closed.
