### ISSUE TITLE
CPU screaming for help at 144hz

### ISSUE THREAD

**Issue by insecxre** [34736384/genshin-fps-unlock#354]
CPU usage increases drastically when using the fps unlocker, temps jump from 55°C to 70°C and CPU is constantly at 100% usage. Anything I could do?

**Comment by Vuulfi** [comment]
It is ok. The more frames you need to output, the more work there is for the CPU. You can reduce the load only by limiting the number of frames below 144. If the load is 100% on 144 frames, then there may be freezes because of this, so I would advise reducing the limit to at least 120.

**Comment by insecxre** [comment]
There were no freezes/stuttering; however, I was just concerned about my CPU's condition

**Comment by ronhombre** [comment]
70C is nothing. Your CPU manufacturer already put in place measures to prevent you from breaking your CPU, so unless you're tinkering with it deliberately, then it's normal for the CPU

**Comment by spiwar** [comment]
> There were no freezes/stuttering; however, I was just concerned about my CPU's condition

This game is CPU limited, so this is expected behavior. It's also why the game has problem reaching 60fps even on mobile and older 4 core cpus.

**Comment by BlueStarBRS** [comment]
> CPU usage increases drastically when using the fps unlocker, temps jump from 55°C to 70°C and CPU is constantly at 100% usage. Anything I could do?
 
buy a new and better one.
