### ISSUE TITLE
Weird GPU performance.

### ISSUE THREAD

**Issue by h4ppyl1fe** [34736384/genshin-fps-unlock#362]
I recently upgraded my graphics card to an RTX 4070 Super, but its load is between 40-60%. Why doesn't the game want to load the graphics card at 100%? The processor is an i5 12400F, which is loaded at 50-60% and is stable at those values.

Advise any settings, maybe the solution lies on the surface. Drivers are naturally updated.

**Comment by flyrobot27** [comment]
Genshin Impact is relatively single threaded, and 12400F isn't fast enough for a 4070 super
