### ISSUE TITLE
Doesn't Work with 4.5

### ISSUE THREAD

**Issue by RahuX** [34736384/genshin-fps-unlock#364]
The game still launches with the current unlocker, but the game is still capped to 60 despite being set to 144.

**Comment by cnhy-nero-diskard** [comment]
Ive had the same issue as well. Locked at 60 after the update

**Comment by Mormaite** [comment]
Same here

**Comment by adrardossa** [comment]
using the release v2.2 seems working fine

**Comment by Gatoz97** [comment]
I can confirm latest release V3.0.3 doesn't work, but release V2.2.0 works.

**Comment by DChangka** [comment]
Hmm I see. Thanks for sharing the stopgap solution for now y'all.
I hope that a new and improved version is released which will address the FPS concerns of this patch.

**Comment by danialzikri14** [comment]
I can confirm latest release V3.0.3 doesn't work and the release V2.2.0 works.

**Comment by 34736384** [comment]
fixed
