### ISSUE TITLE
Fontaine Issue

### ISSUE THREAD

**Issue by tothekitsune** [34736384/genshin-fps-unlock#378]
When you start swimming or diving in the waters of the Fontaine, everything around (nor the character) begins to twitch and the frametime jumps up and down. This can be fixed either by re-entering the game (it’s better not to swim in the water of the Fontaine again), or if you simply leave the location where there is water that you can dive into (of course, if you return to this location, then everything will start to twitch again)
![Снимок экрана 2024-03-23 114143](https://github.com/34736384/genshin-fps-unlock/assets/76000152/9c36c6a3-cc27-4f24-8e6a-aab7fed34dcb)
![Снимок экрана 2024-03-23 114245](https://github.com/34736384/genshin-fps-unlock/assets/76000152/3b1708fa-8616-4aab-8dcc-ec8c233b5eba)

**Comment by BlueStarBRS** [comment]
i dont think that it is related to the unlocker cause it only changes the frame limit

**Comment by 34736384** [comment]
game issue
