### ISSUE TITLE
Exclusive Fullscreen

### ISSUE THREAD

**Issue by DerPon3** [34736384/genshin-fps-unlock#38]
i run the game in exclusive fullscreen with the -window-mode-exclusive shortcut, but it doesn't work with the fps unlocker, you should make a button or add it in the config file please

**Comment by 34736384** [comment]
**-window-mode-exclusive** is not a valid parameter
https://docs.unity3d.com/Manual/CommandLineArguments.html

All parameters passed to the unlocker is correctly passed to the game, you can use ProcessHacker to verify it

**Comment by DerPon3** [comment]
true, my bad
