### ISSUE TITLE
FPS unlocker not working on windows 10

### ISSUE THREAD

**Issue by chaud365** [34736384/genshin-fps-unlock#383]
Hello, I just recently got into genshin impact, wanted to quit the game because 60 FPS doesn't run smooth on 144hz for me, but the FPS unlocker was a life saver. After few days of playing I had to revert to windows 10, did fresh installation, installed genshin, unlocker, but the unlocker was not working properly. It does show the FPS I pick  on locker (144) on MSI afterburner, but the game stutters and feels like 50-60 FPS with 144 FPS shown. Because of that I reinstalled windows 11 again, did everything again and it's buttery smooth on windows 11. Does anyone have any solutions how to run it on windows 10? I don't know where else to ask for help. Thank you

**Comment by Confiac1563** [comment]
Same issue, I also use Windows 10 and this tool does not work, MSI Afterburner shows the FPS number at 60. It seems to only happen in this version, in the previous version my FPS reached the threshold 120 (i3 4150 + GTX 750 1GD5 + 8GB RAM DDR3 1600MHz single). Hope the developer fixes this bug quickly

**Comment by DAOWAce** [comment]
I'm still on Windows 10, v2004 in fact, and it works just fine, and I'm even still using the older 2.2.0 ("clr") version which shouldn't be working after 4.3 (and now we're in 4.6) according to the release notes.  Crazy.

**Comment by chaud365** [comment]
> I'm still on Windows 10, v2004 in fact, and it works just fine, and I'm even still using the older 3.0.2 version which shouldn't be working on 4.5 (and now we're in 4.6) according to the release notes. Crazy.

you are not getting any fps drops and stuttering even tho FPS stays high? I have tried it on 2 different PCs and both have the exact same issue on windows 10, FPS stay at 144 on 144hz monitor, but the game feels like 60 fps, on windows 11 buttery smooth with 0 issues

**Comment by DAOWAce** [comment]
Stays high?  Well, miHoYo's games have a memory leak, so FPS never 'stays' high through extended play sessions.  Stuttering also gets worse.  It is most definitely not 60FPS though, as I don't play games below 90FPS anymore.

But yes, the unlocker is working properly for the version I mentioned.  I have no intention of updating if everything works fine.

Did you try an earlier version?

**Comment by chaud365** [comment]
> Stays high? Well, miHoYo's games have a memory leak, so FPS never 'stays' high through extended play sessions. Stuttering also gets worse. It is most definitely not 60FPS though, as I don't play games below 90FPS anymore.
> 
> But yes, the unlocker is working properly for the version I mentioned. I have no intention of updating if everything works fine.
> 
> Did you try an earlier version?

I've been playing for 8+ hours when I started like month and a half ago, never had fps drops or stuttering on windows 11 even after 8+ hours of playing, its locked on 120 fps and stays there. On windows 10 fps stays at 120 but feels like 60, might be just me problem, last time I tried it was working on windows 10 when I started the game and when I alt tabbed to second monitor and back to the game the unlocker wasn't working anymore, even when I reopened the game, but I will just stick with windows 11 to avoid the problem, thanks for sharing your experience.
