### ISSUE TITLE
内存泄漏 memory leak

### ISSUE THREAD

**Issue by BUnipendix** [34736384/genshin-fps-unlock#389]
![image](https://github.com/34736384/genshin-fps-unlock/assets/100204822/bf11a69d-eecb-447e-85d5-42470029a981)

**Comment by 34736384** [comment]
noted, will check

**Comment by 34736384** [comment]
had it running over 8 hours, could not reproduce

**Comment by BUnipendix** [comment]
> had it running over 8 hours, could not reproduce

疑似是system informer统计问题
![图片](https://github.com/34736384/genshin-fps-unlock/assets/100204822/12462df8-3742-4e9a-903d-e73f89b73de9)
系统任务管理器正常
![图片](https://github.com/34736384/genshin-fps-unlock/assets/100204822/0bfc9b64-6a0d-4e98-97c5-ec5b8e81c05d)
