### ISSUE TITLE
Error code 31-4302

### ISSUE THREAD

**Issue by yp-isaac** [34736384/genshin-fps-unlock#398]
Hello, I'm playing in America Server.
Windows 10, ran the unlocker with "Run as administrator"
But didn't go well.

It's Korean, but it's saying that;

Data error, delete the game and re-install by downloading from official channel.
Error code: 31-4302

![image](https://github.com/34736384/genshin-fps-unlock/assets/169478973/f5d500d6-578b-46e3-af29-a009424b2798)

I have to delete the json file to start the game, and of course the rate is limited to 60 hz :(

**Comment by 34736384** [comment]
don't put the unlocker in the same location as the game

**Comment by PrincessAzulaBlue** [comment]
It errors out now with 4.7 non working
