### ISSUE TITLE
Unable to increase 120 limit since ver. 1.10

### ISSUE THREAD

**Issue by ApacheTriad** [34736384/genshin-fps-unlock#4]
Just recently downloaded the most recent release. I found that I was unable to increase the 120 fps limit. I went back and downloaded the versions beforehand. Before finding that version 1.10 was the last version to allow the fps cap to increase using the arrow keys. Any version beyond that doesn't allow me to do so. This isn't too much of a problem, but I would like to see it fixed.

**Comment by 34736384** [comment]
After ver1.1 I believe I made it to only check for key state while the game window is focused. That means, you have to tab into the game in order to use the arrow keys to change fps.

**Comment by ApacheTriad** [comment]
Ah, my bad. 
Thank for your help!
