### ISSUE TITLE
Unable to open for no reason

### ISSUE THREAD

**Issue by zyqassistant** [34736384/genshin-fps-unlock#401]

**Comment by 34736384** [comment]
i can't read your mind, i would need more information

**Comment by zyqassistant** [comment]
Thank you for your reply, the issue now is solved. Let me explain more about the issue.
The main problem is when i click the icon of your exe. the open interface was not appear and the game also didn't launch. And the issue is occurs suddenly, maybe i change some set by chance?
it is now solved after I delete the "fps_config.json"( i didn't even notice this until I try to find solvation in issue centre) and download again. I don't know why if I didn't delete this redownload is useless.&nbsp;


And thank you for your contribution of genshin fps unlock.


                       
Original Email
                       
                     

Sender:"REL"< ***@***.*** &gt;;

Sent Time:2024/6/4 15:24

To:"34736384/genshin-fps-unlock"< ***@***.*** &gt;;

Cc recipient:"zyqassistant"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [34736384/genshin-fps-unlock] Unable to open for no reason (Issue#401)




 
i can't read your mind, i would need more information
