### ISSUE TITLE
"ReadProcessMemory failed with code: 299" - Genshin 4.7

### ISSUE THREAD

**Issue by EritoKaio** [34736384/genshin-fps-unlock#402]
![image](https://github.com/34736384/genshin-fps-unlock/assets/26747759/79b70784-cf63-4ad0-8e4d-16b711069a91)

Doesn't work as of Version 4.7.

**Comment by UnlishedTen8** [comment]
Yup, lucky for us we should not have to wait that long for an update.

**Comment by fromadrk** [comment]
How to solve it？

**Comment by UnlishedTen8** [comment]
Those of you guys who are struggling with this. UPDATE YOUR PROGRAM 

Not sure why you opened an issue without even thinking about updating

**Comment by fromadrk** [comment]
sry,my bad
