### ISSUE TITLE
New issue on new patch

### ISSUE THREAD

**Issue by HadouGun** [34736384/genshin-fps-unlock#403]
I updated and was able to get the new launcher and updated, when starting the game code 299 happens now.
<img width="200" alt="2024-06-05_13-18-04" src="https://github.com/34736384/genshin-fps-unlock/assets/135528273/f15f527f-1eaa-4f6c-81b8-287ad89308a0">

**Comment by cyrosimulacra** [comment]
Had the same issue, reinstalling the program fixed it for me. Hope this works for you aswell.

**Comment by coowlu** [comment]
> Had the same issue, reinstalling the program fixed it for me. Hope this works for you aswell.

I tried the same method, but it didn't solve the problem for me.
I'm still getting an error message.

**Comment by 34736384** [comment]
That's not the latest version

**Comment by D34thCAP** [comment]
Having the same issue with the same error code
