### ISSUE TITLE
Stopped working as of 4.7

### ISSUE THREAD

**Issue by Wyzmic** [34736384/genshin-fps-unlock#405]
Giving this error "Read process memory failed code 299"

**Comment by Tenshi1061** [comment]
I have the same error, i hope it gets fixed. I'm used to playing at 240 fps and 60 is just outright unplyable...

**Comment by Amrsatrio** [comment]
Same for me.

**Comment by ArcherCZY** [comment]
I‘m asure you it still works in Ver4.7.I just download it in order to unlock my game in 144FPS.

**Comment by Raze876** [comment]
same error

**Comment by Frkovo** [comment]
same

**Comment by Amrsatrio** [comment]
@ArcherCZY Yeah you're right, thanks. Didn't realize that I was running the old unlockfps_clr.exe one.

Get the latest version (unlockfps_nc.exe), it worked for me.
https://github.com/34736384/genshin-fps-unlock/releases/tag/v3.0.4

**Comment by HadouGun** [comment]
Same I updated to NC and it worked.

**Comment by Raze876** [comment]
also was using old unlocker, updated to NC v3.0.4 and kept my old fps_config.json and working good

**Comment by ArcherCZY** [comment]
@Amrsatrio The reason why I'm here is that the old unlockfps_clr.exe I used didn't work.It happened in Ver3.4 once，and again today in Ver4.7.So I have to find a replacement.
