### ISSUE TITLE
Error with v4.7

### ISSUE THREAD

**Issue by Transcan** [34736384/genshin-fps-unlock#406]
I guess something changed in the update 4.7

I get this error when launching the game:
![image](https://github.com/34736384/genshin-fps-unlock/assets/2226763/cddcaac2-1a47-4584-b265-d972dd85cb54)

**Comment by 34736384** [comment]
why don't you check closed issues first

**Comment by Transcan** [comment]
Because closed issues aren't shown by default...
But I will next time.
