### ISSUE TITLE
Not working + Error window on WIN11 (ReadProcessMemory failed with code: 299)

### ISSUE THREAD

**Issue by ghost** [34736384/genshin-fps-unlock#407]
If you keep clicking OK, the window just shows up again, the unlocker is broken with the 4.7 update

![image](https://github.com/34736384/genshin-fps-unlock/assets/84100659/5e304ed1-b0de-4057-b6ba-59ce506707d8)

**Comment by 34736384** [comment]
https://github.com/34736384/genshin-fps-unlock/issues?q=is%3Aissue+is%3Aclosed

**Comment by ghost** [comment]
my bad, updated
