### ISSUE TITLE
Errors out after 4.7 update 

### ISSUE THREAD

**Issue by PrincessAzulaBlue** [34736384/genshin-fps-unlock#409]

**Comment by PrincessAzulaBlue** [comment]
It errors out with memory write error.

**Comment by 34736384** [comment]
https://github.com/34736384/genshin-fps-unlock/issues?q=is%3Aissue+is%3Aclosed

**Comment by BlueStarBRS** [comment]
> https://github.com/34736384/genshin-fps-unlock/issues?q=is%3Aissue+is%3Aclosed

what is now with the unlocker your link just put me to the main page ???
