### ISSUE TITLE
unlocker don´t work! since the genshin impact update 4.8 (error code: 209)

### ISSUE THREAD

**Issue by BlueStarBRS** [34736384/genshin-fps-unlock#410]
![image](https://github.com/34736384/genshin-fps-unlock/assets/25110093/f3ceaef3-be3c-4ac1-8375-0ba82f79d823)
error code: 209
it does not work fps are not hihger than 60!

**Comment by 34736384** [comment]
https://github.com/34736384/genshin-fps-unlock/issues?q=is%3Aissue+is%3Aclosed

**Comment by BlueStarBRS** [comment]
> https://github.com/34736384/genshin-fps-unlock/issues?q=is%3Aissue+is%3Aclosed

so what now you just show the old issue tab and there is no new version to download ?

**Comment by 34736384** [comment]
v3.0.4 is the new version

**Comment by BlueStarBRS** [comment]
> v3.0.4 is the new version

april ? 
uhm ok i tought i have this one already,
maybe i messed sometimg with my skript and i used an older ver. maybe it opens the wrong exe is my guess sorry for that

**Comment by BlueStarBRS** [comment]
yup i messed up lmao
![image](https://github.com/34736384/genshin-fps-unlock/assets/25110093/b4365b3f-9820-474b-936c-e891d21335ba)
