### ISSUE TITLE
no longer working after 4.7 update

### ISSUE THREAD

**Issue by parkercb** [34736384/genshin-fps-unlock#411]
tried reinstalling several different versions and deleting .json config file, still not working

**Comment by rajeshsingh381** [comment]
In my case, it still removes the FPS limit but it is very inconsistent, iirc I used to get 100+ FPS before 4.7. I think unlocker is working as intended but there is some other issue preventing high FPS.
![image](https://github.com/34736384/genshin-fps-unlock/assets/26227516/90f09dd5-fde2-4691-9efc-0bfa93517a7e)

**Comment by parkercb** [comment]
> In my case, it still removes the FPS limit but it is very inconsistent, iirc I used to get 100+ FPS before 4.7. I think unlocker is working as intended but there is some other issue preventing high FPS. 

the unlocker works intermittently now for me as well. At first it refused to work, I teleported away and back to mondstadt and now its working again, albeit only at 120fps. Any other framerate doesn't allow it to work

**Comment by frigab** [comment]
+1, unlocker stopped working for me
