### ISSUE TITLE
"outdated fps pattern"

### ISSUE THREAD

**Issue by juturna01** [34736384/genshin-fps-unlock#412]
When I attempt to launch it, i get an error saying "outdated fps pattern". The game then launches, the beginning logo screens will be in 120fps, then title screen drops to 60. It also wont let me boot into the game, because I get an in game notice saying there is an update needed, which there isn't, and upon confirming that it shuts the game down. At a loss here haha. I used it in administration mode as well.

**Comment by 34736384** [comment]
Wrong game path and you're not using the latest version, check closed issues first next time

**Comment by juturna01** [comment]
What do you mean? I just tried it, today, with the latest version. The exe path was also the correct one.

**Comment by 34736384** [comment]
If the game says update is needed then your game path is wrong. The latest version of the unlocker supports all versions of the game except for beta.

**Comment by juturna01** [comment]
Ill play around with it again. Just to be certain, the correct path is the genshinimpact.exe in the game folder, NOT the launcher right? It automatically selected that when i started the unlocker so i assumed that was the one it wanted.

**Comment by 34736384** [comment]
Correct, auto detect locates the game from registry, but it doesn't mean it is the latest version of the game. If it doesn't show up then you'll have to manually browse for it or simply open the latest version of the game at the unlocker setup screen

**Comment by juturna01** [comment]
Okie doke, thankyou! Ill figure it out XD
