### ISSUE TITLE
在b服里，会出现读取不到程序内存的情况。

### ISSUE THREAD

**Issue by qweretsd** [34736384/genshin-fps-unlock#413]
我这里的情况是，在进入游戏，登录账号之前的fps都可以读到解锁的帧率。
界面切换之后就一直锁60，尝试切副本也无法重置。
但有时运气好能成功进入解锁帧率的大世界，虽然在进入副本时就会锁60.
试了一下官服，似乎没有出现这个问题。
有一个很明显的地方就是账号登录在加载大世界的时候，原神主程序会最小化，切换到别的程序后面。

**Comment by 8940haoran** [comment]
我的情况与你类似。
今天，也就是6月13日，在游玩塔防活动中，我意识到了fps被锁定到了60帧，在此之前都没有遇到过这样的情况。
重启游戏则会恢复到fps解锁的状态，但在进入副本或是联机匹配后，fps解锁就会失效。
至于主程序会最小化的问题，我在调整unlockfps的启动设置中把全屏模式调为exclusive，就会出现你说的那种情况，调成borderless就不会最小化。

**Comment by qweretsd** [comment]
> 我的情况与你类似。 今天，也就是6月13日，在游玩塔防活动中，我意识到了fps被锁定到了60帧，在此之前都没有遇到过这样的情况。 重启游戏则会恢复到fps解锁的状态，但在进入副本或是联机匹配后，fps解锁就会失效。 至于主程序会最小化的问题，我在调整unlockfps的启动设置中把全屏模式调为exclusive，就会出现你说的那种情况，调成borderless就不会最小化。

两个模式结果是一样的，因为独占全屏切换焦点前台之后就会最小化，所以比较显而易见，无边框全屏没有那个独占要求，所以即使显示优先级被调整了，也不会有明显的显示，但是实际上最前台的焦点已经不在原神了。

**Comment by 34736384** [comment]
已修复
https://github.com/34736384/genshin-fps-unlock/releases/tag/v3.2.0
