### ISSUE TITLE
原神当前版本4.7进入秘境后，帧率会自动降回锁60帧，无法解锁帧率，退出秘境后帧率依旧锁60

### ISSUE THREAD

**Issue by coderGods** [34736384/genshin-fps-unlock#423]
如标题所述，首先进入圣遗物秘境后，帧率会变回锁60帧率，退出秘境后依旧锁60，只有退出原神，再次进入游戏，并且不进入圣遗物副本，帧率才不会锁60,希望大佬能排查下是什么导致的,谢谢

**Comment by Snvcaby** [comment]
不仅仅是圣遗物本，包括武器材料天赋材料本、甚至在场景切换的时候（例如枫丹沫茫宫）都会锁帧数。not only the relic quest room,when the sences switched(I test the meterials quest and the interior scenes such as Forsaken Rift), the FPS also locked to 60.

**Comment by Suzuku** [comment]
#415 作者已经在修了，静候大佬佳音
