### ISSUE TITLE
每次重启后需要重新自选路径，另外现在4.7下半更新后一进尘歌壶和副本后就直接回到60帧，并在回到大世界后依然60。但在重启后并停留在大世界的话就可以维持设定帧率

### ISSUE THREAD

**Issue by xzf0509** [34736384/genshin-fps-unlock#424]
![image](https://github.com/34736384/genshin-fps-unlock/assets/59432567/c1875040-7930-46ef-b685-6f92d4e582e3)

**Comment by zszxzzh** [comment]
#415

**Comment by 5945gx** [comment]
有人解决问题了吗？

**Comment by Silver7758** [comment]
@5945gx https://github.com/34736384/genshin-fps-unlock/issues/415#issuecomment-2183856728

**Comment by 5945gx** [comment]
> [#415 （评论）](https://github.com/34736384/genshin-fps-unlock/issues/415#issuecomment-2183856728)

程序 YuanShen.exe 版本 2017.4.30.0 已停止与 Windows 交互并关闭。若要查看是否有关于该问题的详细信息，请检查“安全性与维护”控制面板中的问题历史记录。
 进程 ID: 790
 开始时间: 01dac93ee3b9a6a4
 终止时间: 9
 应用程序路径: S:\Genshin Impact\Genshin Impact Game\YuanShen.exe
 报告 ID: 4a5a09be-a03d-4340-9e71-c9c248f4a915
 错误程序包全名: 
 错误程序包相关应用程序 ID: 
 挂起类型: Unknown

游戏会崩溃~~

**Comment by endcharlotte** [comment]
https://github.com/xiaonian233/genshin-fps-unlock
这个可以用，进入副本不会锁60（测试时间2024-6-30）

**Comment by 34736384** [comment]
已修复
https://github.com/34736384/genshin-fps-unlock/releases/tag/v3.2.0
