### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Manxas** [34736384/genshin-fps-unlock#427]
Genshin is hardlock at 60fps at the day the unlocker exist

**Comment by 34736384** [comment]
I don't understand what you're trying to say

**Comment by Manxas** [comment]
the unlocker still works the way intented, but genshin impact is still locked at 60 fps since the furina update

**Comment by Manxas** [comment]
my bad, nvidia setting somethings locks games at 60 , check your nvidia settings folks
