### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by portalthree** [34736384/genshin-fps-unlock#43]
I use a patch to play GI using linux and wanted to know if it would be possible to use this fps unlocker using linux

**Comment by Egoistically** [comment]
It is, add me on discord: shirome#0001. I'd rather avoid talking about it publicly.

**Comment by AdelKS** [comment]
@Egoistically I would like to be informed too x)

**Comment by Egoistically** [comment]
@AdelKS just saw this lol, i'm really sorry for missing it. did you figure it out?

**Comment by AdelKS** [comment]
@Egoistically No I did not xD
