### ISSUE TITLE
4.8版本又掉回60fps了

### ISSUE THREAD

**Issue by xshaon** [34736384/genshin-fps-unlock#436]
感觉解锁器游戏每个版本更新都要伴随更新了。
米哈游又不愿意开120，又不给工具解锁

**Comment by Soy-JPG** [comment]
一样，每次版本更新都要回到这里下载最新版本

**Comment by xshaon** [comment]
![20240717112126](https://github.com/user-attachments/assets/2e414ab8-f5e0-4727-9e58-67c35b16789d)

**Comment by 34736384** [comment]
你用的是最新版吗，已经更新过了

**Comment by xshaon** [comment]
> 你用是最新版吗
是的，用的是这个月发布的新版
