### ISSUE TITLE
[Error] Failed to get remote module base address

### ISSUE THREAD

**Issue by JinseiKen** [34736384/genshin-fps-unlock#438]
![image](https://github.com/user-attachments/assets/54f42e35-2446-4047-90f6-00eed910568a)

I have gotten this error message since the most recent update. I looked at all the closed tickets saying they have the same issue but saw no solution. I am using the most recent version of the unlocker and have done a clean installation of both Genshin and the launcher.

**Comment by 34736384** [comment]
duplicate of #435, you're not using the latest version
