### ISSUE TITLE
Failed to get remote module base address (GI 4.8, Unlocker 3.3.0)

### ISSUE THREAD

**Issue by dxdvostfr** [34736384/genshin-fps-unlock#439]
![image](https://github.com/user-attachments/assets/789759bc-a24f-4b26-829b-2d15f0b1c730)

Happens everytime, some seconds after startup. The unlocker has not effect.

**Comment by DanielGLee01** [comment]
Same issue here

**Comment by JinseiKen** [comment]
The author says we aren't using the latest version but I have downloaded the latest file on Releases and still experience the same bug

**Comment by DanielGLee01** [comment]
Yeah I downloaded from the 3.3.0 release page as well

**Comment by Monkibear** [comment]
I am getting the same error as well. Fresh install of Genshin with new version of unlocker.

**Comment by Guinguerz** [comment]
same here

**Comment by 34736384** [comment]
are you actually running the latest version? because that error popup is unreachable in the latest version

**Comment by Mitty654** [comment]
I have installed the latest version (v3.3.0) for Genshin Impact version 4.8 and I am getting this error. I have never had this problem before. Maybe the new Hoyoplay game launcher is causing this problem?

**Comment by 34736384** [comment]
> Yeah I think so ^^'

and you updated the game through official launcher?

**Comment by JinseiKen** [comment]
> > Yeah I think so ^^'
> 
> and you updated the game through official launcher?

I have the same version as him and the problem only popped up after updating Genshin Impact through the Hoyoplay Launcher

**Comment by system2ckc** [comment]
I updated to unlocker to 3.3.0 and it works for me now. Try restarting your pc first if its giving you error still.

**Comment by 34736384** [comment]
> Personnally I updated using the collapse launcher. So with or without the official launcher the issue can be present (makes sense, the game files are completely the same, and the fps unlocker runs the genshin executable directly, it does not communicate with the launcher).
> 
> For good measure I did a "check game files" on hoyoplay and got no issues. The unlocker stills outputs the error.

Well, that's probably the problem, you probably still have "UnityPlayer.dll" and "UserAssembly.dll" remain in your game files. Which, it should be removed in version 4.8

**Comment by sagve** [comment]
Same here, genshin-fps-unlock 3.3.0, genshin 4.8 updated via hoyoplay, "Failed to get remote module base access". PC restart had no effect unfortunately. Would you recommend fully reinstalling the game?

**Comment by Newroll** [comment]
> > Personnally I updated using the collapse launcher. So with or without the official launcher the issue can be present (makes sense, the game files are completely the same, and the fps unlocker runs the genshin executable directly, it does not communicate with the launcher).
> > For good measure I did a "check game files" on hoyoplay and got no issues. The unlocker stills outputs the error.
> 
> Well, that's probably the problem, you probably still have "UnityPlayer.dll" and "UserAssembly.dll" remain in your game files. Which, it should be removed in version 4.8

Can confirm, deleting "UnityPlayer.dll" and "UserAssembly.dll" manually does fix the issue.

**Comment by JinseiKen** [comment]
> > > Personnally I updated using the collapse launcher. So with or without the official launcher the issue can be present (makes sense, the game files are completely the same, and the fps unlocker runs the genshin executable directly, it does not communicate with the launcher).
> > > For good measure I did a "check game files" on hoyoplay and got no issues. The unlocker stills outputs the error.
> > 
> > 
> > Well, that's probably the problem, you probably still have "UnityPlayer.dll" and "UserAssembly.dll" remain in your game files. Which, it should be removed in version 4.8
> 
> Can confirm, deleting "UnityPlayer.dll" and "UserAssembly.dll" manually does fix the issue.

Same for me, had to search for said files in my Genshin Impact folder but it works now.

**Comment by Gavin-Alex** [comment]
> I don't have those files and it still doesn't work TwT Happy for you guys tho

bro no need to delete those files, just delete and redownload unlocker

**Comment by sagve** [comment]
Well, I also don't have mentioned DLLs in the game folder (they are present in HSR game folder tho, but it shouldn't matter, right?). 
A good bunch of game restarts just fixed the issue. Idk, I didn't actually do anything, now it just runs smoothly as always with fps unlocked. Weird but whatever.

**Comment by Monkibear** [comment]
Can also confirm that deleting "UnityPlayer.dll" and "UserAssembly.dll" fixed my issue.

**Comment by Gavin-Alex** [comment]
> > > I don't have those files and it still doesn't work TwT Happy for you guys tho
> > 
> > 
> > bro no need to delete those files, just delete and redownload unlocker
> 
> What? unlocker is just the exe and a json config file. I already had the latest version.

idk, but it just worked on me

**Comment by nasuoneko** [comment]
quick tuto, i made it if you didn't know, i just applied what he said.

> Well, that's probably the problem, you probably still have "UnityPlayer.dll" and "UserAssembly.dll" remain in your game files. Which, it should be removed in version 4.8

https://www.youtube.com/watch?v=Ypz8UjZ6MFk

**Comment by pombi114** [comment]
> > Personnally I updated using the collapse launcher. So with or without the official launcher the issue can be present (makes sense, the game files are completely the same, and the fps unlocker runs the genshin executable directly, it does not communicate with the launcher).
> > For good measure I did a "check game files" on hoyoplay and got no issues. The unlocker stills outputs the error.
> 
> Well, that's probably the problem, you probably still have "UnityPlayer.dll" and "UserAssembly.dll" remain in your game files. Which, it should be removed in version 4.8
First,thanks you sm for tips,but i can find  "UnityPlayer.dll" and "UserAssembly.dll" in folder of HSR and ZZZ,but i can't find in folder of genshin :(

**Comment by pombi114** [comment]
> > config file. I already had the latest version.
> 
> idk, but it just worked on me

After repair on launcher hoyoplay and redownload unlock 3.3,it worked on me. 
Before that,i can't find 2 file "UnityPlayer.dll" and "UserAssembly.dll" in folder genshin,because i don't install gi in C local,i install game on another disk and 2 file not display on my folder game.

**Comment by LurenRen1102** [comment]
Just delete my old unlocker and download the new release, it works now :)
Hoping mihoyo pay more attention on fixing those necessary bugs XD

**Comment by Valarck82** [comment]
this is was i did and work, i do a file check through Hoyolauncher, then donwload fps unlocker.

**Comment by Izuqinn** [comment]
> > Personnally I updated using the collapse launcher. So with or without the official launcher the issue can be present (makes sense, the game files are completely the same, and the fps unlocker runs the genshin executable directly, it does not communicate with the launcher).
> > For good measure I did a "check game files" on hoyoplay and got no issues. The unlocker stills outputs the error.
> 
> Well, that's probably the problem, you probably still have "UnityPlayer.dll" and "UserAssembly.dll" remain in your game files. Which, it should be removed in version 4.8

after i deleted these .dlls worked for me too, thank you

**Comment by jshika** [comment]
c

> > Personnally I updated using the collapse launcher. So with or without the official launcher the issue can be present (makes sense, the game files are completely the same, and the fps unlocker runs the genshin executable directly, it does not communicate with the launcher).
> > For good measure I did a "check game files" on hoyoplay and got no issues. The unlocker stills outputs the error.
> 
> Well, that's probably the problem, you probably still have "UnityPlayer.dll" and "UserAssembly.dll" remain in your game files. Which, it should be removed in version 4.8

This fixed the issue for me too. Thanks

**Comment by eternaljune** [comment]
I downloaded 3.3.0 and the problem disappeared.

**Comment by alter0z** [comment]
u guys just sync all the files u have in local storage with the new update genshin version by click repair now in hoyoplay launcher then the problem is gone. Note: the file named "UnityPlayer.dll" and "UserAssembly.dll" will deleted in ur game dir

**Comment by W1nn1e727** [comment]
I fixed this issue by moving the unlocker its self from my downloads in the "genshin impact" folder, not the "genshin impact game" folder. I also run it with 3dmigoto and reshade and it runs just fine after getting in that folder.
