### ISSUE TITLE
"error: That´s not the right place" when trying to browse for the game location

### ISSUE THREAD

**Issue by kastapi** [34736384/genshin-fps-unlock#440]
Since the new update 4.8 i had the issue with the fps unlocker not working that´s why i tried to just reinstall it. Now i have the issue that it doesn´t even find the game location and it gives the error: that´s not the right place. I don´t know why because i haven´t changed anything in the game location or whatever this error is supposed to mean. I hope somebody can help me

**Comment by 34736384** [comment]
Update to the latest version

**Comment by kastapi** [comment]
Last time i tried to reinstall the unlocker it didn´t work. Now it works, thank you! :)
