### ISSUE TITLE
won't works.

### ISSUE THREAD

**Issue by wen111234** [34736384/genshin-fps-unlock#443]
![1](https://github.com/user-attachments/assets/9330d071-f901-45e4-a9c1-71fceed4fb70)
when i just turn on my PC it works.  this error after i log out the game and try to relog.

which means it only works the first time i turn on my PC . otherwise i need to restart my PC... help me~~

**Comment by BlueStarBRS** [comment]
https://github.com/34736384/genshin-fps-unlock/releases/tag/v3.3.0

**Comment by BlueStarBRS** [comment]
if it still happens then after the 3.3.0 @34736384  used again a wrong adresss/pointer and he needs to update again the patern to a working pointer. this happend one time a year ago where hooking with first boot or sec boot form the game caused an error where it is not able to unlock the fps (see fix from 2.1.1 -> https://github.com/34736384/genshin-fps-unlock/releases/tag/v2.1.1)
