### ISSUE TITLE
Conflict with OBS

### ISSUE THREAD

**Issue by dailac-boiii** [34736384/genshin-fps-unlock#444]
It seems the unlocker is conflicted with the Game Capture source of OBS. Every time I use the unlocker, Game Capture will only show a black screen  
![image](https://github.com/user-attachments/assets/04e83b90-9bb2-455c-a85f-83575c9cbcb9)

**Comment by 34736384** [comment]
It shouldn't, is your obs running as admin

**Comment by dailac-boiii** [comment]
> It shouldn't, is your obs running as admin

Yes it is. OBS would capture the splash in when booting the game or just black screen. This did happen even back in older versions. Note that I'm playing on Laptop

**Comment by 34736384** [comment]
That sounds like a conflict with another overlay software, fps unlocker has nothing to mess with screen capture functionalities

**Comment by dailac-boiii** [comment]
> That sounds like a conflict with another overlay software, fps unlocker has nothing to mess with screen capture functionalities

Yeah it seems to work now. Will have to be more careful with performance overlay I guess
