### ISSUE TITLE
[Error] "Failed to get remote console base address" at the latest release "3.3.0"

### ISSUE THREAD

**Issue by Lytsu** [34736384/genshin-fps-unlock#446]
![image](https://github.com/user-attachments/assets/8cf7dd52-5c07-4e98-8bb1-8abc850f64a3)
Both the complied binary from the latest release and the build with VS 2022 are unavailable.
I've cloned the repo and tried to build but also not work.

**Comment by 34736384** [comment]
#439

**Comment by Lytsu** [comment]
> #439

I checked the issues and finally solved the problem by follow these steps:
1. Open the Hoyoplay, and select repair in the game option;
2. Delete `fps_config.json` of the unlocker;
3. Restart the unlocker and select the path of game again.
-----
下面为中文版本，供中文读者参照。
使用最新版解锁器仍提示 `Failed to get remote console base address` 的具体修复步骤，个人操作，供参考：
1. 打开米哈游启动器，选择游戏三横菜单中的“立即修复”选项；
2. 删除解锁器目录中的配置文件 `fps_config.json`；
3. 重新打开解锁器，并重新配置游戏目录。
