### ISSUE TITLE
Map zooming slows down as a function of FPS

### ISSUE THREAD

**Issue by maiiiiixo** [34736384/genshin-fps-unlock#448]
Map zooming (and maybe other things) seem to slow down drastically as a function of the FPS I set in the config. See the videos below:

[60 FPS - Normal Map Zooming](https://files.catbox.moe/p2acf7.mp4)

[144 FPS - Slower Map Zooming](https://files.catbox.moe/vgpp71.mp4)

[280 FPS - Very Very Very Slow Map Zooming](https://files.catbox.moe/myutuf.mp4)

Config:
{
  "GamePath": "C:\\Program Files\\HoYoPlay\\games\\Genshin Impact game\\GenshinImpact.exe",
  "AutoStart": true,
  "AutoClose": true,
  "PopupWindow": false,
  "Fullscreen": true,
  "UseCustomRes": false,
  "IsExclusiveFullscreen": false,
  "StartMinimized": false,
  "UsePowerSave": false,
  "SuspendLoad": false,
  "UseMobileUI": false,
  "FPSTarget": 280,
  "CustomResX": 1920,
  "CustomResY": 1080,
  "MonitorNum": 1,
  "Priority": 3,
  "DllList": []
}

G-Sync Compatible Enabled in NVIDIA Control Panel
V-Sync Enabled in NVIDIA Control Panel, V-Sync Off in-game
277 FPS Limit Enabled in NVIDIA Control Panel

**Comment by ghost** [comment]
very interesting finding, 60 fps seems to be more responsive

**Comment by 34736384** [comment]
that's an issue for genshin cs

**Comment by maiiiiixo** [comment]
> that's an issue for genshin cs

???

wtf does this have to do with genshin cs? "oh yeah so im using a mod that's against your TOS because it could break the game, and it did break the game. help pls." like are you serious? guess ill try fixing the issue on my own then lol, thanks i guess.

**Comment by 34736384** [comment]
> ???
> 
> wtf does this have to do with genshin cs? "oh yeah so im using a mod that's against your TOS because it could break the game, and it did break the game. help pls." like are you serious? guess ill try fixing the issue on my own then lol, thanks i guess.


Use your brain, it's obviously a game issue, not an issue of the unlocker. 
And you have even read the README?
Even if you did, you are just incompetent to understand what "Any artifacts from unlocking fps (e.g. stuttering) is NOT a bug of the unlocker" means or make an alt to submit a support ticket.

Grow some hair before you speak next time

**Comment by maiiiiixo** [comment]
yeah it's obviously a game issue, which is why the only changes between the clips are changes from your mod. stellar logic.

and even if it was the game, let's use some noggin as you put it, i make an alt, submit a support ticket that my game breaks at FPS values that aren't supported by the base game, wtf do you expect them to say? "oh yeah mb we'll go fix something we haven't even implemented ourselves".

the readme feels like a very broad stroke to deflect any issues with your mod, ofc i'm gonna make an issue thread because logically speaking the only difference between clips was the FPS, so why would i conclude this is a game issue?

you're utterly up your own arse with your ego, get a grip and learn to take criticism you freak.

**Comment by 34736384** [comment]
> Yeah it's obviously a game issue, which is why the only changes between the clips are changes from your mod. stellar logic.

So you do know it is a game issue and yet you opened an issue here making it sound like it's a bug of the unlocker. Yea, tard moment it is.

> and even if it was the game, let's use some noggin as you put it, i make an alt, submit a support ticket that my game breaks at FPS values that aren't supported by the base game, wtf do you expect them to say? "oh yeah mb we'll go fix something we haven't even implemented ourselves".

In fact, they have fixed issues with high fps in the past, but too bad your lazy ass couldn't search about it.

> the readme feels like a very broad stroke to deflect any issues with your mod, ofc i'm gonna make an issue thread because  logically speaking the only difference between clips was the FPS, so why would i conclude this is a game issue?

No, you're just incompetent to understand what's written on the README. Because your brain couldn't conclude this is a game issue, that's why I told you it is.

> you're utterly up your own arse with your ego, get a grip and learn to take criticism you freak.

I don't know where you got to this conclusion, this is not a YouTube comment section, if you act like a tard, then I'll talk like shit. There's no criticism for me to take here, it's the problem of the game. 

And using terms like 'ego' or 'can't take criticism' obviously shows that you haven't grown any hair yet. It's not the golden formula to argue with anyting
