### ISSUE TITLE
Error: "Failed to get remote module base address" as of Genshin version 4.8

### ISSUE THREAD

**Issue by JLHackSeven** [34736384/genshin-fps-unlock#449]
FPSUnlock_NC.exe is (partially) bugged as of 4.8.

--- Issue:

As of Genshin Impact version 4.8, an error "Failed to get remote module base address" appears once the game loads the title screen.

--- System:

Steam Deck (Arch Linux) using Proton-GE 8-32, Launched through Heroic Games Launcher 

(Heroic Games Launcher is a custom Linux frontend for the Epic Games Store, allowing you to run any game in your Epic Games Store library on Linux)

--- Notes:

Genshin FPS Unlock worked fantastic on the Steam Deck in 4.7, and could allow the framerate to be unlocked to 90 FPS.

Genshin FPS Unlock is important on the Steam Deck because it can force Genshin Impact to run in Fullscreen mode with a custom resolution (such as the Steam Deck's native 1280x800), which is necessary to use AMD's FSR 2 frame generation to improve performance in the game.

From Genshin's graphics options, the resolutions available include 1280x720 Fullscreen or Windowed, but for the Steam Deck's native 1280x800, only WINDOWED appears.

For Proton (Valve/Steam's custom version of Wine) forcibly enabling AMD's FSR 2 frame generation requires the game to be in FULLSCREEN.

Enabling AMD's FSR 2 Frame generation can significantly boost FPS in Genshin Impact. Normally performance in Genshin on the Steam Deck fluctuates between 54-63 FPS, but FSR 2 frame generation can boost framerate to between 66-78 FPS, sometimes even reaching as high as 80. 

Forcing the game to a custom resolution in fullscreen mode to enable frame generation allows the game to achieve a very stable framerate of 60+ FPS. The FPS Unlocker can also increase the framerate cap to 90 for use with an external monitor with a higher refresh rate if so desired.

--- How to enable (for anyone with a Stem Deck who is curious)

Launch the game in Heroic Games Launcher with Proton-GE-8-32, adding the following environment variables in the settings:

WINE_FULLSCREEN_FSR 1
WINE_FULLSCREEN_FSR_MODE performance

--- Unrelated Side Note:

Going to Vorukasha's Oasis and turning on Reflections in the graphics settings causes performance of Genshin on the Steam Deck to take a huge hit. Without frame generation, it fluctuates between 48-54 FPS and can drop as low as 43 FPS, which is very jarring.

FSR 2 frame generation drastically improves performance at Vorukasha's Oasis, hovering between 58-65 FPS, making the game noticeably more stable.

**Comment by 34736384** [comment]
are you using the latest version of the unlocker

**Comment by JLHackSeven** [comment]
> are you using the latest version of the unlocker

Thank you for making me double check, my downloads were being stored in the wrong folder. F*ck Linux.

Even though the fault is with Valve's Linux implementation, I can't even be mad, they have dramatically transformed the way that I play games with the Steam Deck. For example, playing the Final Fantasy VII remake _**with mods**_ at 60 FPS on a _**handheld device**_, is amazing.

The new version does unlock the FPS in Genshin, but it doesn't disable Vsync, you need to go to Genshin's graphics options and disable vsync manually, or it will still be capped at 60.

Other than that, everything works now. Thank you.
