### ISSUE TITLE
Hide the Cmd and add argument, possible?

### ISSUE THREAD

**Issue by WilliamLeGod** [34736384/genshin-fps-unlock#45]
Hi! 

Thank you so much for the tool. I can finally enjoy the game at 120 fps which has changed my gaming life bro!
To make this perfect, is it possible to:

1/ Hide this cmd everytime I run it? 
2/ Add  the argument: "-screen-fullscreen 1 -window-mode exclusive" to make the game run in exclusive fullscreen to prevent stutterings? (by running this tool, I cant use my game shortcut with the argument any more)

I really appreciate it if you could somehow guide me a way to achieve those 2 requests which gonna make me fulfill 100% bro!!!

Many thanks!

**Comment by dromzeh** [comment]
>  2/ Add the argument: "-screen-fullscreen 1 -window-mode exclusive" to make the game run in exclusive fullscreen to prevent stutterings? (by running this tool, I cant use my game shortcut with the argument any more)

#1

**Comment by WilliamLeGod** [comment]
> > 2/ Add the argument: "-screen-fullscreen 1 -window-mode exclusive" to make the game run in exclusive fullscreen to prevent stutterings? (by running this tool, I cant use my game shortcut with the argument any more)
> 
> #1

Thank you for your quick reply!
I've read the thread you mention but is it just create a shortcut of the unlock.exe file then add argument in properties or nope?
I'm sorry I'm noob when it comes to coding. Is there a step by step how to add this argument to your unlock.exe file?

Appreciate your time!

**Comment by dromzeh** [comment]
> Thank you for your quick reply! I've read the thread you mention but is it just create a shortcut of the unlock.exe file then add argument in properties or nope? I'm sorry I'm noob when it comes to coding. Is there a step by step how to add this argument to your unlock.exe file?

You can pass the argument using a command line such as Powershell: `Start-Process -filepath "unlockfps.exe" -ArgumentList "-screen-fullscreen 1 -window-mode-exclusive"`
Or, you can create a shortcut, go into the properties and add `-screen-fullscreen 1 -window-mode-exclusive` after `\unlockfps.exe`:
![image](https://user-images.githubusercontent.com/65048232/145680174-a885ecef-d2cb-424d-9e34-e7f8e8f5f2ed.png)

**Comment by WilliamLeGod** [comment]
Thank you so much. I've got it to work!

Any idea if I can Hide the Cmd window though?

**Comment by dromzeh** [comment]
> Thank you so much. I've got it to work!
> 
> Any idea if I can Hide the Cmd window though?

Good to know you've got that working. I'm not entirely sure about hiding the command window actually, you might be better of waiting for a response from the repo owner or from someone else.

**Comment by anpuhach** [comment]
> Any idea if I can Hide the Cmd window though?

Create a .bat file with the following content: start /min D:\Games\GenshinUnlockFPS\unlockfps.exe

**Comment by WilliamLeGod** [comment]
> > Any idea if I can Hide the Cmd window though?
> 
> Create a .bat file with the following content: start /min D:\Games\GenshinUnlockFPS\unlockfps.exe

Will this work with the argument "-screen-fullscreen 1 -window-mode-exclusive"?

**Comment by dromzeh** [comment]
> 



> > > Any idea if I can Hide the Cmd window though?
> > 
> > 
> > Create a .bat file with the following content: start /min D:\Games\GenshinUnlockFPS\unlockfps.exe
> 
> Will this work with the argument "-screen-fullscreen 1 -window-mode-exclusive"?

Might do, you'll have to try it, and make sure that the batch file is directing to the shortcut you created with the extra arguements.

**Comment by WilliamLeGod** [comment]
![explorer_09evCQskqj](https://user-images.githubusercontent.com/70202711/145694760-100e08ad-1d5e-4009-bf70-66f5c1c27c7b.png)
I keep getting this error even though the Path is 100% correct. Don't know why :(

**Comment by anpuhach** [comment]
> I keep getting this error even though the Path is 100% correct. Don't know why :(

When referring to a path with a space, you must enclose it in quotes. Try using: start /min "H:\...\unlockfps.exe"

**Comment by WilliamLeGod** [comment]
![explorer_zdchZnJztT](https://user-images.githubusercontent.com/70202711/145695308-f6189ef9-3f62-4174-9838-24c77821d6e1.png)
It doesn't work for me, it just shows this

**Comment by Shassk** [comment]
>Or, you can create a shortcut, go into the properties and add `-screen-fullscreen 1 -window-mode-exclusive` after `\unlockfps.exe`

Doesn't work in my case for some reason
![image](https://user-images.githubusercontent.com/62873560/145928839-eb4178b6-9ae9-4451-b8fe-47562c9306b9.png)
Version 1.4.2 which is latest atm.

**Comment by 34736384** [comment]
Check out the latest release https://github.com/34736384/genshin-fps-unlock/releases
Added GUI and interactive controls for configuring launch options

**Comment by WilliamLeGod** [comment]
> Check out the latest release https://github.com/34736384/genshin-fps-unlock/releases Added GUI and interactive controls for configuring launch options

Thank you sir! You made my day (today is my birthday actually). You are the best!
