### ISSUE TITLE
Unlocker not working after logo screen

### ISSUE THREAD

**Issue by victorchen01** [34736384/genshin-fps-unlock#450]
Don't know why but the unlocker suddenly stopped working today. Goes past 60 during the "Hoyoverse" screen, but once it hits the doors, it drops back down to 60. There's also a "failed to get remote module base address" popup, but I've always seen it there.

**Comment by sdfj123sdf** [comment]
i have this problem too, how fix that?

**Comment by DafyddWJ** [comment]
I have this issue as well. I think an update probably broke something so hopefully the creator of this can implement a fix.
But honestly, Hoyoverse just needs to get their act together and have this be a normal feature to unlock the 60 FPS cap. It doesn't even break anything + it makes the game feel so much better to play on higher refresh rate monitors so it seems like such a completely redundant thing to keep locked like this.
Even Roblox has finally learned their lesson in this regard now...

**Comment by 34736384** [comment]
are you using the latest version
if so, try to take a look at #446 #439
