### ISSUE TITLE
[Bug] Software stopped working as of 5.0

### ISSUE THREAD

**Issue by devrim6** [34736384/genshin-fps-unlock#456]
The specific error is "Failed to get remote module base address". Redoing the setup does not fix the issue.
![image](https://github.com/user-attachments/assets/59405934-6cd5-44ef-848e-fe16f6922181)

**Comment by p0358** [comment]
works perfectly fine for me tho

**Comment by 34736384** [comment]
#439

**Comment by devrim6** [comment]
That was it, thank you! I didn't update in 4.8 and this issue persisted.
