### ISSUE TITLE
5.0 release ETA?

### ISSUE THREAD

**Issue by TheSixEyes** [34736384/genshin-fps-unlock#457]
Just curious as to an eta for the updated release. I can no longer use the 4.8 variation. 
Is there a way to get the current version of fpsunlocker to work on the 5.0 update? If not I will wait :)

**Comment by zurce** [comment]
It works just fine

**Comment by TheSixEyes** [comment]
> It works just fine

when I use the exe it's launching with the 4.8 patch still

**Comment by RedMatterGG** [comment]
idk if im delusional but if i use the tool for 5.0,i swear the game feels sped up in certain areas,like character running animations and bursts.

**Comment by TheSixEyes** [comment]
my bad lol. It does work fine on 5.0 I just had some stuff messed up on my end.

**Comment by IcyFoxe** [comment]
Just a question: is it safe to use this app after 5.0 release? Isn't there anything different that needs to be updated first after the game's major update?
