### ISSUE TITLE
Im curious as to how you have found the memory values to change

### ISSUE THREAD

**Issue by Celibistrial** [34736384/genshin-fps-unlock#46]

**Comment by Celibistrial** [comment]
sorry for opening a thread , but i couldn't find another way to contact you

**Comment by 34736384** [comment]
just static analysis using ida

**Comment by Celibistrial** [comment]
Ok ill try using that software (the software i was using gets blocked by mhyprot)

**Comment by Celibistrial** [comment]
Also how do you get past mhyprot?

**Comment by 34736384** [comment]
static analysis is only analyzing the file on disk, there were no need to have the game running.
as of handle bypass,  the parent process(unlocker) has a full access handle to child process(game) unless the handle is stripped on launch

for the fps unlock feature there were no code being injected into the game, it's only changing an integer inside a rw region

**Comment by Celibistrial** [comment]
Also since you have a full access handle to the game mhyprot cant detect writes to the game process memory right?(I had thought the way it worked is it runs all the code before mhyprot launches, but apparently not because you can change fps cap after game launch)

**Comment by 34736384** [comment]
**mhyprot cant detect writes to the game process memory right?**
they can if they wanted to

for the fps value, if you take a look at the source, the value resides in unityplayer

**Comment by Celibistrial** [comment]
So you opened UnityPlayer.dll in ida?

**Comment by 34736384** [comment]
just defaults

**Comment by Celibistrial** [comment]
Which file do you open in Ida

**Comment by Celibistrial** [comment]
So I have found the signature and stuff. Wrote the code, unfortunately, the memory address I want to modify resides in GenshinImpact.exe, which is protected by mhyprot2. Do you know how to bypass it?

**Comment by 34736384** [comment]
just use the same method as shown in my source

**Comment by Celibistrial** [comment]
Your code modifies an address in UnityPlayer.dll which is not protected by mhyprot2.(I can read and write to UnityPlayer.dll but not to GenshinImpact.exe)

**Comment by 34736384** [comment]
**Your code modifies an address in UnityPlayer.dll which is not protected by mhyprot2**
No, UnityPlayer.dll is a part of GenshinImpact.exe which is indeed protected by the driver. There isn't a way to open a handle to a DLL

**Comment by Celibistrial** [comment]
Oh ok, thanks! 
I'll look into it further.

**Comment by Celibistrial** [comment]
![image](https://user-images.githubusercontent.com/82810795/147042087-d17d123f-da20-426a-9286-e7250cfe082c.png)
Hmmm I've cloned your repo and modified the code(only the pattern scan function and signature are different) 
Exception thrown at 0x00007FF7BD4838B7 in unlockfps.exe: 0xC0000005: Access violation reading location 0x00000000000000C4.

**Comment by Celibistrial** [comment]
char* ScanBasic(char* pattern, char* mask, char* begin, intptr_t size)
{
    intptr_t patternLen = strlen(mask);

    for (int i = 0; i < size; i++)
    {
        bool found = true;
        for (int j = 0; j < patternLen; j++)
        {
            if (mask[j] != '?' && pattern[j] != *(char*)((intptr_t)begin + i + j))
            {
                found = false;
                break;
            }
        }
        if (found)
        {
            return (begin + i);
        }
    }
    return nullptr;
}

This is the pattern scan function.

**Comment by Celibistrial** [comment]
`char* caddress = ScanBasic((char*)"9A 99 19 3B 9A 99 19 3B 00 00 80 BF 02 00 00 00 02 00", (char*)"9A 99 19 3B 9A 99 19 3B 00 00 80 BF 02 00 00 00 02 00", (char*)pi.hProcess, (intptr_t)sizeof(pi.hProcess));`

I probably made a stupid mistake lol

**Comment by 34736384** [comment]
I won't spoon feed so,
That's not how you use your pattern scan
Just look at my source and see how I utilized the pattern scan function

**Comment by Celibistrial** [comment]
Ok

**Comment by Celibistrial** [comment]
I have managed to complete the project, is there a risk of ban?(I'm changing the in-game sensitivity).
