### ISSUE TITLE
Forced resolution isn't working as of at least September 9th

### ISSUE THREAD

**Issue by JLHackSeven** [34736384/genshin-fps-unlock#466]
Forced screen resolution is not working as of at least the September 9th post-patch fix. The game retains the same resolution it was previously set to when last played. This can change depending on the monitor, and if the engine doesn't like the available resolutions of the current monitor, it changes the resolution to the lowest one available.

I change monitors with my laptop and steam deck when going from my bedroom to my living room, the latter of which has a 1440p 120hz monitor. 

Genshin does not like this monitor's choice of resolutions, so it defaults to the lowest resolution:
![Screenshot_20240908_165410](https://github.com/user-attachments/assets/c590f3ab-1e28-449e-9bf9-c478aa1f8cd4)

This is obviously unplayable.

**Comment by 34736384** [comment]
I've checked it and it is working just fine
