### ISSUE TITLE
fps unlocker doesn't work for Genshin CN ver. 5.1 

### ISSUE THREAD

**Issue by BUnipendix** [34736384/genshin-fps-unlock#474]
![图片](https://github.com/user-attachments/assets/69dd4b14-14de-4795-9dca-5a16ba6f4e53)

**Comment by BUnipendix** [comment]
已确定失效原因：启动程序，引擎，GameAssembly三合一
The cause of the failure has been determined: startup program, engine, GameAssembly three-in-one
![图片](https://github.com/user-attachments/assets/b7a350ff-dbb1-4931-949d-70062ff634a3)

**Comment by 34736384** [comment]
最新版没有失效，在4.8就已经3合1了

**Comment by BUnipendix** [comment]
> 最新版没有失效，在4.8就已经3合1了

之前在云原神和手机上玩的，没注意
![图片](https://github.com/user-attachments/assets/9e0814f5-7060-4c2e-95d8-9e5e892e0734)
目前我的电脑无法解锁帧率，这是我的系统版本，可以做个参考

**Comment by 34736384** [comment]
最新版的解锁器试过了吗

**Comment by BUnipendix** [comment]
> 最新版的解锁器试过了吗

试过了，还是签名版本的

**Comment by Rimliya** [comment]
仅使用解锁器 在26100.2033下成功解锁 5.1版本无论是签名还是不签名版本都能解锁

**Comment by v3i1y** [comment]
Doesn't work for international too.

**Comment by Thanatos-L** [comment]
国服昨天开服的时候还能用，今天会crash

**Comment by tovc** [comment]
> Doesn't work for international too.

works fine for me on global
![image](https://github.com/user-attachments/assets/321ef621-3548-4225-bd04-e8e1c4054ada)

**Comment by v3i1y** [comment]
Spent an hour today and figured it out. Disabling v-sync in game settings immediately unlocked FPS for me. It seems like previously the unlocker will work even if the v-sync setting is on. ~~Maybe something changed in 5.1 that unlocker is no longer able to disable v-sync automatically.~~

Edit: ~~maybe the unlocker was compatible with v-sync before. I noticed that screen tearing is a lot worse after disabling v-sync, so unlocker must have worked with v-sync before.~~

Edit2: OMG, I am so stupid, I suddenly realized something and checked refresh rate setting in my display settings, which was set to 60hz. That was the whole reason v-sync locks fps to 60. Ok nothing but my brain was ever broken for me.

**Comment by okanefps** [comment]
is it fine to use? any updates on potential bugs and what not?

**Comment by BUnipendix** [comment]
发现为什么没用了，我忘记关闭英伟达显卡设置里的应用程序帧率限制了
Found out why it didn't work, I forgot to turn off the application frame rate limit in the NVIDIA graphics control panel
