### ISSUE TITLE
Unlocker not working on Genshin version 5.1 for global version

### ISSUE THREAD

**Issue by ghost** [34736384/genshin-fps-unlock#475]
Hello,

The unlocker doesn't seem to be working on latest release 3.3.0. I ran exe as administrator, the FPS seems stuck on 58, VSync is off as well. Monitor refresh rate is 240Hz

**OS Name**: MS Windows 11 Home
**OS Version**:  10.0.22631 Build 22631
**Nvidia driver version**: 565.90
**Genshin version**: 5.1
**Unlocker release version**: 3.3.0

![Screenshot 2024-10-14 211415](https://github.com/user-attachments/assets/196ee5a2-782c-4a6b-bef4-c312edd0c6b3)
![Screenshot 2024-10-14 212343](https://github.com/user-attachments/assets/3aeb55d4-a33f-4f09-8546-a3e25f0c48e7)

I tried fullscreen and borderless 4k, still same issue. I usually have 2 monitors but I disabled one and ran it only on the 240Hz monitor, still stuck on 58 fps. I repaired installation on HoyoPlay as well, no luck.

 Let me know of any suggestions on how to potentially fix it, thanks.

**Comment by muitenphale** [comment]
The tool does work. It is just that MSI afterburner cannot capture the correct FPS. Try to  open the game without the tool then move camera around, u will see the difference.

**Comment by ghost** [comment]
I did try with and without unlocker, I see no visual difference. This tool used to work for me almost a year ago(even with MSI). I also tried another fps monitoring tool after your comment, but I still get the same 58 fps. I feel like my pc might be cursed or something.

**Comment by muitenphale** [comment]
> I did try with and without unlocker, I see no visual difference. This tool used to work for me almost a year ago(even with MSI). I also tried another fps monitoring tool after your comment, but I still get the same 58 fps. I feel like my pc might be cursed or something.

What is the refresh rate of your monitor? I would suggest following steps:
1. turn off V-sync ingame
2. reinstall GPU driver with clean install option (wipe all previous setting)
3. Run the FPS unlocker tool as admin

I am not sure if it impacts the tool but both my PC and laptop have "Memory integrity" setting in Windows Security turned off. You may want to take a look at this too.

**Comment by ghost** [comment]
Mem integrity is already off for me. Clean re-install drivers fixed it. Thanks a lot 👍
