### ISSUE TITLE
Error screen: "Data error. Finish uninstalling the game and reinstall it through official means. Error code: 31-4302"

### ISSUE THREAD

**Issue by cristiandevweb** [34736384/genshin-fps-unlock#479]
When I try to use the FPS Unlocker I always get this message from the screenshot, I have already reinstalled the game more than 3 times and it only appears when I use the unlocker, the vanilla game without using the fps unlocker works perfectly.

I look forward to a reply, thank you very much for the great work you do and greetings!

update: I managed to fix it by removing the fps unlocker from the game installation folder and moving it to the desktop, hopefully this will be your solution as well and I won't delete this post so that if someone else also has the same problem, see it c:

![Captura de pantalla (1)](https://github.com/user-attachments/assets/0f9984cc-936e-4f0f-a33b-5cbd64053e5a)

**Comment by aamaanaa** [comment]
i have the very same problem.

**Comment by cristiandevweb** [comment]
> i have the very same problem.

I managed to fix it by removing the fps unlocker from the game installation folder and moving it to the desktop, hopefully this will be your solution as well and I won't delete this post so that if someone else also has the same problem, see it c:

**Comment by aamaanaa** [comment]
i see i am on linux so it is a bit more complicated. i ll try placing it at other locations
