### ISSUE TITLE
Launch the unlocker then nothing happen, only a pop said "Error another unlocker is already running"

### ISSUE THREAD

**Issue by SharkPunch114514** [34736384/genshin-fps-unlock#481]

**Comment by 34736384** [comment]
So what is the issue here?

**Comment by MYSTICALMUSICAL** [comment]
Executing this program opens an instance that minimizes itself to the taskbar. Even after you exit Genshin Impact, it will still be running in the background.

Click on the up-arrow located on the right side of the taskbar, right click Paimon's face, and select exit. You can also terminate the program through task manager. It will be located in the background processes dropdown menu as "unlockfps_nc"
