### ISSUE TITLE
Unlocker causing Notice: Version update found

### ISSUE THREAD

**Issue by OGEpsilon** [34736384/genshin-fps-unlock#492]
Whenever I try to launch the game through the unlocker it opens just fine but as soon as I try to start the game past the loading door it tells me to update the game to the latest version even though I am already on the latest version of the game (5.2) I've tried to re download the unlocker and repair my files in the game but I still get this issue. If anyone can help, please do, I'd much rather play Genshin at 200 frames than 60.
![20241209_221223~2](https://github.com/user-attachments/assets/3a52f61d-e93f-4c74-885a-e6fc13a35776)
This is the notice
![20241209_221223~2](https://github.com/user-attachments/assets/0ae4481e-1ec0-4490-9b42-8a21a145d6e7)
As you can see the unlocker is working on start up but wont allow to go past the login screen
(I tried to zoom in as best as I could)

**Comment by OGEpsilon** [comment]
I accidentally sent the same picture twice.
THIS is the Notice
![20241209_221223](https://github.com/user-attachments/assets/4787d326-fc8a-4174-9d17-17ed10f536a7)

**Comment by 34736384** [comment]
you have the wrong game path

**Comment by OGEpsilon** [comment]
Thanks a lot, I just changed it and now it's working, sorry about that.
