### ISSUE TITLE
Add Requirements in readme

### ISSUE THREAD

**Issue by Meisterlala** [34736384/genshin-fps-unlock#5]
This program does not work on a clean Windows 10 System. It requires the Visual C++ runtime to start.

![grafik](https://user-images.githubusercontent.com/6453306/120773929-0cd86400-c522-11eb-8267-48d61a5b0c56.png)

as far as i can tell, this program requires the Visual C++ 2019 Redistributable.

Please add a "Requirements", "Dependencies" or similar section to the readme.

**Comment by 34736384** [comment]
Will do. The initially I had it to be in the same folder as the game launcher, which has all the required dlls. Then I thought it was inconvenient so I changed it, and forgot about the vcredist dependencies.
