### ISSUE TITLE
Reshade not working

### ISSUE THREAD

**Issue by Soggy-Pancake** [34736384/genshin-fps-unlock#51]
Reshade is injected and I can bring up the overlay but when I select a preset nothing loads.

Using custom reshade from https://genshade.github.io

logs
![Screenshot 2022-01-09 144432](https://user-images.githubusercontent.com/54160598/148702191-5e7a05b8-aa39-4ef2-b105-22ab52aaca97.png)

using the copper preset from genshade shows nothing
![copper](https://user-images.githubusercontent.com/54160598/148702239-a75a60ac-cf5f-49be-b899-b0cb85018a15.png)

Graphics Settings:
1920x1080 fullscreen
fps: 60  (set to 144 by unlocker)
vsync: off
render res: 100%
shadow quality: High
Visual Effects: High
SFX: High
Environment: High
A-A: SMAA
Volumetric Fog: On
Reflections: On
Motion Blur: Off
Bloom: On
Crowd Density: High
Co-op Effects: On
Subsurface Scattering: High
Anisotropic Filtering: 4x

Hardware:
CPU: Ryzen 5 1600 af
RAM: 16gb 3000mhz
GPU: Radeon RX 590

**Comment by leonardo-spy** [comment]
try do it:
![img1](https://user-images.githubusercontent.com/19514153/149031157-63acf263-0d11-4eca-bd8e-d9f201d993ab.png)
just add this lines in your code:
```
MODULEENTRY32 hKernel{};
while (!GetModule(pi.dwProcessId, "KERNELBASE.dll", &hKernel))
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
```
and move `InjectReshade(pi.hProcess);` to up (and down kernel code)

**Comment by DzXAnt22** [comment]
how are you even getting in the game without getting data error using reshade? I'm getting it every single time :(

**Comment by Soggy-Pancake** [comment]
Reshade was just configured wrong but data errors still kick me out of the game.

**Comment by DzXAnt22** [comment]
damn :( please let me know if you ever figure it out!! I would love to know
