### ISSUE TITLE
FPS Remains Locked at 60

### ISSUE THREAD

**Issue by ThisIsMyAccnt** [34736384/genshin-fps-unlock#54]
Hi, I've been trying to get this work for my set up but for some reason I can't.

I've managed to set it to 240 fps, but it won't actually run at 240 fps when I alt+tab into the game.

I've tried deleting and redownloading the file, but no luck.
I have tried toggling it on and off in game too.

I do have a dual monitor set up (2nd monitor is 60 hz), but the game & global settings are set to run on my main monitor w/ 240 hz with 236 fps set in nvidia control panel. No limits set in afterburner/rivatuner. Nothing in GeForce experience either.
Genshin is saved on a secondary drive, but that shouldn't matter.
The program and shortcut are set to run only in administrator mode.
Vsync is turned off.

Do you have any recommendations for me?
I've tried reading through some of the comments on the youtube video (https://www.youtube.com/watch?v=YxqrVnfytcs), but nothing seemed relevent.

PS. image looks wide because if I alt+tab out of the game then my fps goes up so I had to put the console on my second monitor. When I'm playing the game it stays at 60.
My hardware: 5600x + 3080

Thanks in advance

![image](https://user-images.githubusercontent.com/97902122/149800973-bc50dfdf-4a06-4d83-9e64-4f5466bf0287.png)

**Comment by DAOWAce** [comment]
> if I alt+tab out of the game then my fps goes up

Sounds like something else is capping the framerate of your active window..

**Comment by ThisIsMyAccnt** [comment]
> > if I alt+tab out of the game then my fps goes up
> 
> Sounds like something else is capping the framerate of your active window..

Funny enough, I turned of full screen optimization and that seems to have enabled higher fps modes.

![image](https://user-images.githubusercontent.com/97902122/150608248-1ae4cba1-e1f8-4438-bb16-dfce46673ba1.png)
