### ISSUE TITLE
Its not working anymore

### ISSUE THREAD

**Issue by Amoodaa** [34736384/genshin-fps-unlock#57]
sending a crashreport as soon as i open the game, tried to reset the config still nothing

**Comment by Steakchop** [comment]
same issue

**Comment by Kert** [comment]
Still works fine here

**Comment by catchips9** [comment]
It works fine for me as well, maybe a clean reinstall may help.

**Comment by Amoodaa** [comment]
Sorry! windows update broke things, back to normal
