### ISSUE TITLE
Any way to make it fullscreen borderless?

### ISSUE THREAD

**Issue by hybridbyte** [34736384/genshin-fps-unlock#62]
Currently you can play genshin on fullscreen borderless either by adding it to steam with the launch command -popupwindow or create a shortcut to the .exe and using that command as well. I was wondering how would I go about to play borderless with the fps unlocker

**Comment by 34736384** [comment]
#1

**Comment by theasdaf67** [comment]
I am able to do this by creating a shortcut to the unlock fps exe with the same command
Target "C:\Games\unlockfps.exe -popupwindow"
