### ISSUE TITLE
Getting error after trying the fps unlocker.

### ISSUE THREAD

**Issue by ZeldaPeatan** [34736384/genshin-fps-unlock#65]
When I log in after the door animation, I get this error.
![image](https://user-images.githubusercontent.com/100961214/157271986-c0e0b76f-c807-4499-ae76-62f77a233963.png)
After closing the fps unlocker, the error still appears. It was working fine 5 minutes earlier just before trying the unlocker.

Not even repairing the game files fixed this.

**Comment by 34736384** [comment]
I've stated under notes in readme, do not place it in the same folder as the game

**Comment by ZeldaPeatan** [comment]
> I've stated under notes in readme, do not place it in the same folder as the game

Yep, I figured it out too. I removed the files and it works again. Sorry.
I'd change the _Usage_ section from this "Place the compiled exe anywhere you want" to this"Place the compiled exe anywhere you want **expect the game folder**".
