### ISSUE TITLE
Borderless option isn't working

### ISSUE THREAD

**Issue by Xinsar** [34736384/genshin-fps-unlock#69]
Uhh hello, as what title said, the borderless isn't working somehow

Here's the Launch Options setting. Did I make a mistake on this? https://prnt.sc/jaA6Y87Z0zmU

Thanks!

**Comment by 34736384** [comment]
please read the tooltips on the options by hovering your mouse over them, you are probably looking for popup window option

**Comment by otomegitsune** [comment]
did you try pressing alt+enter
