### ISSUE TITLE
与此项目不兼容

### ISSUE THREAD

**Issue by Rakau** [34736384/genshin-fps-unlock#7]
https://github.com/Tsuk1ko/genshin-borderless-launcher
会导致窗口全屏化失败

**Comment by 34736384** [comment]
之前的参数传递有bug，这边忘了更新了，现已更新
给解锁器创建个快捷方式然后在快捷方式里添加启动参数-popupwindow即可

**Comment by Rakau** [comment]
感谢更新~~
