### ISSUE TITLE
Memory leak type FPS loss in 2.6

### ISSUE THREAD

**Issue by DAOWAce** [34736384/genshin-fps-unlock#76]
Anyone been noticing an issue akin to a memory leak (FPS loss over time) after 2.6 with the new version of the unlocker?

I wanted to keep using the 1.x version but that ceased to work properly in 2.6 (menus set fps back to 60).  Have to use the 2.0 version to get the unlocker working well, but I've been having this memory leak esque issue ever since 2.6 released.  Don't know if it's Genshin itself *(probably; mihoyo bung up something every patch)* or a side effect of using the unlocker.

2.7 was "indefinitely" delayed, figured I'd report this in the meantime.

**Comment by 34736384** [comment]
There has been the same problem reported over at CN also. The main functionality of the unlocker didn't change, so it's probably just the game

**Comment by logib** [comment]
I can confirm this is an ongoing issue with the game itself. After having the game running for a couple hours and traveling around the world my ram usage goes up to 3.5-4gb and my fps drops to 120-160. Reboot the game and I'm back to 200 fps with only 2.5gb ram usage
