### ISSUE TITLE
Program doesn't return running exe filepath correctly during initial setup

### ISSUE THREAD

**Issue by Kert** [34736384/genshin-fps-unlock#8]
It just stores "R" as a folder name in the config. Probably related to encoding/locale or something. I used the latest release
Writing filepath to exe in the config manually works though

**Comment by 34736384** [comment]
which windows version are you using? win7?

**Comment by Kert** [comment]
yes

**Comment by 34736384** [comment]
fixed and updated, check release section

**Comment by Kert** [comment]
Works. Thanks
At last the game can be played comfortably :)
