### ISSUE TITLE
Will it get banned?

### ISSUE THREAD

**Issue by noxyasha** [34736384/genshin-fps-unlock#84]
Yeah, I used FPS unlocker month ago only for 5 min. Set limit to 120 instead of 60 (on iOS devices it's okay with 120)
Tested out my new PC.
Now I'm just curious.. Will my account get banned only for one launch of 5 minutes? (now i'm not using it)
And what is anti-cheat in this game? I heard that it's like Kernel, but I have no clue it's true or not..

P.S. I know about Hoyoverse's ban waves, that maybe account may be flagged for future ban but anyway..

**Comment by dromzeh** [comment]
Look at #19, you can check reported bans.

**Comment by noxyasha** [comment]
> Look at #19, you can check reported bans.

Yeah I know, but... I have one specific thing... I forgot to mention that. 
I wrote to CS about this thing, and I think I have made only worse to my acc :D

**Comment by noxyasha** [comment]
> Look at #19, it's a pinned issue that will be updated if anyone has got banned, and other people vouching they haven't been banned. FYI, I've been using it for a year straight with no ban.

You're using on main acc, aren't ya?

**Comment by dromzeh** [comment]
> You're using on main acc, aren't ya?

Yes, I am - it is AR 58, with quite a bit of money spent.

> I wrote to CS about this thing, and I think I have made only worse to my acc :D

I did too a year ago with the same email with my Genshin Account, they just reccomended not to use it. I've been using it for ages anyways since then with no issue.

**Comment by noxyasha** [comment]
> > You're using on main acc, aren't ya?
> 
> Yes, I am - it is AR 58, with quite a bit of money spent.
> 
> > I wrote to CS about this thing, and I think I have made only worse to my acc :D
> 
> I did too a year ago with the same email with my Genshin Account, they just reccomended not to use it. I've been using it for ages anyways since then with no issue.

Well, I did too in-game function "Feedback" (if i'm not mistaken)

**Comment by noxyasha** [comment]
> > You're using on main acc, aren't ya?
> 
> Yes, I am - it is AR 58, with quite a bit of money spent.
> 
> > I wrote to CS about this thing, and I think I have made only worse to my acc :D
> 
> I did too a year ago with the same email with my Genshin Account, they just reccomended not to use it. I've been using it for ages anyways since then with no issue.
> 
> Note: I didn't tell CS I used it, I just asked what would happen if I were to use it in the future.

Well, In that pinned issue I copypasted their answer

**Comment by noxyasha** [comment]
They also said, that it's not recommended to use, but if you deleted this stuff and never used it again, the risk of ban wouldn't be higher

**Comment by noxyasha** [comment]
> They also said, that it's not recommended to use, but if you deleted this stuff and never used it again, the risk of ban wouldn't be higher

Also they said, that I'm free to play as usual

**Comment by dromzeh** [comment]
> They also said, that it's not recommended to use, but if you deleted this stuff and never used it again, the risk of ban wouldn't be higher

> Well, I need to cure my paranoia, I guess 😅 Sorry for disturbing you. Thanks for answering, you reassured me a lot :)

Honestly, I'm not sure if this would make much difference but if you wanted to 'play it safe', you could just wait a while before using it on your account. And no worries. If you want to ask me again in the future if I've got banned or anything you're more than welcome to send a message on discord.

**Comment by noxyasha** [comment]
> > They also said, that it's not recommended to use, but if you deleted this stuff and never used it again, the risk of ban wouldn't be higher
> 
> > Well, I need to cure my paranoia, I guess 😅 Sorry for disturbing you. Thanks for answering, you reassured me a lot :)
> 
> Honestly, I'm not sure if this would make much difference but if you wanted to 'play it safe', you could just wait a while before using it on your account. And no worries. If you want to ask me again in the future if I've got banned or anything you're more than welcome to send a message on discord.

I don't want to use it, I'm pretty comfortable with 60 FPS. I just don't want to lose this account. And I would like to have your Discord and UID, if it's possible and you're in Europe ^^
