### ISSUE TITLE
Latest Golden Apple Archipelago event cannot be completed using the unlocker

### ISSUE THREAD

**Issue by jordanmerkel** [34736384/genshin-fps-unlock#86]
When doing the GAA Fischl castle event, there is a puzzle where you must rotate the towers. They are unable to be rotated while using the FPS unlocker. An image is attached to show where this occurs:
![image](https://user-images.githubusercontent.com/47964738/179851993-31e1dd65-d8a5-4e56-bb72-f42839d03ddb.png)

I've restarted a few times on the unlocker to no avail. Using the base game works completely fine as expected. Seems to only be an issue on a higher framerate. Feel free to chime in if you do/don't have this issue.

**Comment by dromzeh** [comment]
I'm not sure if this isn't a case with the FPS unlocker, I did this with the unlocker just fine. 
Seems that the rotate thing just takes a while.

**Comment by jordanmerkel** [comment]
> I'm not sure if this isn't a case with the FPS unlocker, I did this with the unlocker just fine. Seems that the rotate thing just takes a while.

Gotcha, mine did not work at all running on 150 fps. Restarts did not fix the issue.

I'll leave this thread up for 2 days and see if anyone else encounters this, otherwise I'll mark as resolved. Thanks!

**Comment by noxyasha** [comment]
Your game looks so frickin' good... How long do you use reshade and fps unlocker?

**Comment by jordanmerkel** [comment]
> Your game looks so frickin' good... How long do you use reshade and fps unlocker?

I do not use Reshade. I use Nvidia filters, which can be accessed by pressing Alt+Z (if you have Nvidia card). It has no performance impact compared to Reshade. I've been using the unlocker and filters for about 7-8 months now 
My personal filter settings are:

Brightness / Contrast:
-Exposure: -12%
-Contrast: 14%
-Highlights: 16%
-Shadows: 16%
-Gamma: 0%

Sharpen:
-Intensity: 25%

Vignette:
-Intensity: 30%

**Comment by Flatfire** [comment]
> > I'm not sure if this isn't a case with the FPS unlocker, I did this with the unlocker just fine. Seems that the rotate thing just takes a while.
> 
> Gotcha, mine did not work at all running on 150 fps. Restarts did not fix the issue.
> 
> I'll leave this thread up for 2 days and see if anyone else encounters this, otherwise I'll mark as resolved. Thanks!

Same problem for me. Works fine provided I'm not using the unlocker. If I had to guess, this is something funky with the event and FPS being tied to the operation of the puzzle, rather than something that could be fixed on the end of the unlocker.

**Comment by BlueStarBRS** [comment]
> When doing the GAA Fischl castle event, there is a puzzle where you must rotate the towers. They are unable to be rotated while using the FPS unlocker. An image is attached to show where this occurs: ![image](https://user-images.githubusercontent.com/47964738/179851993-31e1dd65-d8a5-4e56-bb72-f42839d03ddb.png)
> 
> I've restarted a few times on the unlocker to no avail. Using the base game works completely fine as expected. Seems to only be an issue on a higher framerate. Feel free to chime in if you do/don't have this issue.

omg its a game bug man just resatrt your game and take your time.

**Comment by jordanmerkel** [comment]
> omg its a game bug man just resatrt your game and take your time.

As you quoted from my original reply, I restarted my game a few times and it did not fix it. I'll still close this issue because the event is over. Thanks
