### ISSUE TITLE
Deletion

### ISSUE THREAD

**Issue by noxyasha** [34736384/genshin-fps-unlock#87]
Should I reinstall Genshin Impact after using FPS Unlocker?
After deletion, will other accounts (where I didn't use it) be affected to get banned? 
(I decided to start rerolling, 'cause my main is under threat to get banned (reshade+fps unlocker))

**Comment by dromzeh** [comment]
There's no point, reinstalling wont do anything. 
Your account will be fine, don't worry.

**Comment by noxyasha** [comment]
> There's no point, reinstalling wont do anything. Your account will be fine, don't worry. I've used reshade in the past multiple times too in the past year, my account is still fine.

The main problem is that I snitched on myself to CS, telling them that I used it for 5 min or so..

**Comment by dromzeh** [comment]
> > There's no point, reinstalling wont do anything. Your account will be fine, don't worry. I've used reshade in the past multiple times too in the past year, my account is still fine.
> 
> 
> 
> The main problem is that I snitched on myself to CS, telling them that I used it for 5 min or so..
> 
> 

I know, reinstalling won't make a difference, like I said in a previous issue if you're that worried just don't use it again and continue to play the game normally without the unlocker. Your account will be fine.

**Comment by noxyasha** [comment]
> > > There's no point, reinstalling wont do anything. Your account will be fine, don't worry. I've used reshade in the past multiple times too in the past year, my account is still fine.
> > 
> > 
> > The main problem is that I snitched on myself to CS, telling them that I used it for 5 min or so..
> 
> I know, reinstalling won't make a difference, like I said in a previous issue if you're that worried just don't use it again and continue to play the game normally without the unlocker. Your account will be fine.

I didn't use it from that first time day (month ago), only for ~5 min. Now I'm just worrying about those 5 min could be crucial idk

**Comment by noxyasha** [comment]
I know, that they won't ban me just because I wrote about it to CS (they would definitely check my account and need more evidence to it but anyway, i don't trust their anticheat and knowing that they ban people in waves drives me more and more mad)

**Comment by 34736384** [comment]
You are too paranoid

**Comment by noxyasha** [comment]
> You are too paranoid

Yeah, I know :D
Sometimes I think that I need to visit the doctor in order to cure this shit and turn off my Internet for ~2-3 years
