### ISSUE TITLE
奇怪的幀數波動

### ISSUE THREAD

**Issue by XPRAMT** [34736384/genshin-fps-unlock#88]
2.0版 如果"AutoDisableVSync=false"，幀數會有奇怪的波動
上一個版本"VSYNC=1"則正常
如果關閉VSYNC則會有嚴重的撕裂
![image](https://user-images.githubusercontent.com/34093551/180125285-8b8c02cf-af03-4d11-a6ff-fc0390ee31d4.png)
![image](https://user-images.githubusercontent.com/34093551/180125342-e0e0e76c-cef1-4c3a-8f44-b53f587aeadf.png)

**Comment by 34736384** [comment]
这个说实只是游戏的问题，自动关闭vsync就等于在自动把游戏设置里的垂直同步关了而已
