### ISSUE TITLE
Does not apply launch options.

### ISSUE THREAD

**Issue by lolflakes** [34736384/genshin-fps-unlock#9]

**Comment by Spedemix** [comment]
Yeah, I agree this unlocker needs to let you start the exe with launch options (or arguments) like `-window-mode-exclusive` in order to have things like G-sync working properly.

**Comment by 34736384** [comment]
It's working fine, nothing looks wrong to me
![Capture](https://user-images.githubusercontent.com/25654009/123696843-371ff780-d82a-11eb-8d08-794f0b39378d.PNG)

**Comment by 34736384** [comment]
And here is borderless windowed
![Capture](https://user-images.githubusercontent.com/25654009/123697873-6aaf5180-d82b-11eb-8703-10956ccd8b20.PNG)

**Comment by Spedemix** [comment]
OK, maybe I'm dumb then. How exactly am I suppose to make this happen then? if I put `-popupwindow` in the unlockfps.exe shortcut it won't even launch the game.

**Comment by 34736384** [comment]
> OK, maybe I'm dumb then. How exactly am I suppose to make this happen then? if I put `-popupwindow` in the unlockfps.exe shortcut it won't even launch the game.

You probably put the launch options some where else or had it inside the double quote
![Capture](https://user-images.githubusercontent.com/25654009/123698936-abf43100-d82c-11eb-9301-1cbd6b9b918c.PNG)

**Comment by Spedemix** [comment]
It's in the right place, if I put in a launch argument, unlockfps.exe starts but the game won't.

![image](https://user-images.githubusercontent.com/64281393/123699317-ce577000-d867-11eb-87ea-9aed6156992f.png)

**Comment by Spedemix** [comment]
Never mind. Deleted the old shortcut, created a new one; it works now.

Thank you and sorry for the inconvenience.

**Comment by 34736384** [comment]
> It's in the right place, if I put in a launch argument, unlockfps.exe starts but the game won't.
> 
> ![image](https://user-images.githubusercontent.com/64281393/123699317-ce577000-d867-11eb-87ea-9aed6156992f.png)
are you using the latest version? I just tried your launch options on the latest version of the unlocker and it started up fine

**Comment by Spedemix** [comment]
> > are you using the latest version? I just tried your launch options on the latest version of the unlocker and it started up fine

Yeah, I'm using the latest version. After some further investigation it turns out the game won't launch for me if Processhacker.exe is running, that was culprit.

**Comment by Louis-AC** [comment]
-window-mode-exclusive and disable fullscreen optimizations do not seem to work on Windows 11.
With this argument I was able to Alt-Enter in and out of exclusive fullscreen on Windows 10.
Now G-Sync is locked to Windows framerate and the game stutters all over the place.
Any way to fix it ?

**Comment by 34736384** [comment]
Check out the latest release https://github.com/34736384/genshin-fps-unlock/releases
Added GUI and interactive controls for configuring launch options
