### ISSUE TITLE
No options window

### ISSUE THREAD

**Issue by Volern** [34736384/genshin-fps-unlock#91]
There doesn't appear to be any way to edit the options. The only options I can see is the fps limit and slider for it, and start game automatically. Nothing else shows up and I cannot see any way to view the options. I have managed to figure out how to build the code in visual studio which creates a json file I can edit so I can use that as a stopgap but still no ui menu for it.

**Comment by 34736384** [comment]
So you don't see an "Options" menu on top left?
![image](https://user-images.githubusercontent.com/25654009/185518547-d4dd5ca7-5541-4a52-a2b1-abbce4bbac6f.png)

**Comment by Volern** [comment]
Yes, but that's all you see. You don't see any of the launch options like automatic fullscreen and start minimized for the unlocker among other options that should be available, noted in the readme under version 2.0.0 changes

**Comment by 34736384** [comment]
I'm not understanding, did you try clicking on it and look around in "Settings"

**Comment by Volern** [comment]
Where is settings? There is buttons except start game.

**Comment by 34736384** [comment]
![image](https://user-images.githubusercontent.com/25654009/185678010-bb2fc70d-9a8d-43e4-8717-4789854d2629.png)

**Comment by Volern** [comment]
Right thats the issue. Options is a button that doesnt look like a button. It just looks like a text field with no indication that you can click on it.
