### ISSUE TITLE
Custom resolution not worked

### ISSUE THREAD

**Issue by Zimong** [34736384/genshin-fps-unlock#93]
Add “-screen-width” and “-screen-height” to command line manually, it’s fine.
Set up “UseCustomRes”: true, do not worked.

手动没问题，在配置文件里开启 UseCustomRes 啥事没有发生。

**Comment by 34736384** [comment]
Custom Resolution没问题，要用的话勾上然后输入需要的分辨率就行
![image](https://user-images.githubusercontent.com/25654009/187350690-20d30ff3-d703-4c2c-aa8f-094c0021bb5e.png)

**Comment by Zimong** [comment]
> Custom Resolution没问题，要用的话勾上然后输入需要的分辨率就行
> ![image](https://user-images.githubusercontent.com/25654009/187350690-20d30ff3-d703-4c2c-aa8f-094c0021bb5e.png)

重复测试后发现，在勾选“Fullscreen”后，只能在“Windows Mode: Borderless”下生效。Feature or Bug？
![CEA0DE67-290C-405D-B3DA-F1EB63D55BDD](https://user-images.githubusercontent.com/12237255/187356250-20385438-f83f-4bed-b260-2d2e103276d3.png)
