### ISSUE TITLE
Trojan.Malware.300983.susgen according to VirusTotal

### ISSUE THREAD

**Issue by m3dus444** [34736384/genshin-fps-unlock#95]
Hi, heres the hash https://www.virustotal.com/gui/file/1bcc67f7a4f42a94e5dc593509d0156f02161373f6e6922e914e180d4153aa56
I might be an error, i'll check the code to see that 😅 

Medusa.

**Comment by 34736384** [comment]
😅😅😅

**Comment by m3dus444** [comment]
Ayoo what does that mean ? that's an error ! ...right ? 😭

**Comment by KiritoVeres** [comment]
Considering I've been using this for awhile now, and it's only picked up by two antivirus/antimaleware softwares I've never heard of before. I think its fine.

**Comment by Luminitza-Noptzii** [comment]
It looks like a false positive
