### ISSUE TITLE
Deletion question

### ISSUE THREAD

**Issue by Fafoglio** [34736384/genshin-fps-unlock#96]
I used this tool for a few weeks and It works perfectly, but I'm really getting too paranoid about this, and i deleted It. Do i have to delete any other file other than the folder with the unlocker exe? Does the exe create some files in the game folder that have to be deleted? Like config or similar? I know a config file Is created when running the tool for the First time, but it's created into the tool location e NOT into the game folder? I do not have to delete any unlocker file from the game folder right?  In less words, how do i get rid of the tool without leaving any trace of It in the system? Because i feel like the cursor Is Still more than 60 fps, even if i re installed genshin and deleted the unlocker folder.. Is It supposed to be smoother even if the game Is now normally capped at 60? Or there are some residual files from the unlocker? Thanks for your answer, I'm so scared in the future they May find residual third party prog files and ban me :/

**Comment by Luminitza-Noptzii** [comment]
You can launch the game normally and it will act like you don't have the unlocker installed. If you want to delete it just remove the 2 files. Do note that cursor smoothness doesn't always mean high fps. You can use msi afterburner or any fps overlay app (or drivers) to check your frame rate.

**Comment by 34736384** [comment]
Just simply delete it

**Comment by Fafoglio** [comment]
Thanks for the answer. With the 2 files u mean unlocker exe and the config in the unlocker folder? My doubt was if the unlocker created idk like some tracks in the game register so maybe i'm already in the black list ready to get banned even of I'm not using the tool anymore...Sorry i know I'm extremely paranoid...

**Comment by 34736384** [comment]
You're not gonna get banned
