### ISSUE TITLE
the launch is not in full screen

### ISSUE THREAD

**Issue by holden93274** [34736384/genshin-fps-unlock#98]
![image](https://user-images.githubusercontent.com/116509218/197404804-ab56df9a-0fcf-482f-8630-e2ff444e57e7.png)
with unlocker fps 
-
![image](https://user-images.githubusercontent.com/116509218/197405190-cdbcddf0-5938-4fd0-a414-17b9079f2c96.png)
![image](https://user-images.githubusercontent.com/116509218/197405207-59c53fba-309a-4f42-a975-482a33f56daf.png)
without unlocker fps , first through geforce experience with settings 2560 - 1440 in full screen , and then through epic games . 
- 
how to launch 2560 - 1440 in full screen via unlocker ? ( via fps_config does not work )

**Comment by TsungLinYeh** [comment]
![image](https://user-images.githubusercontent.com/61908909/198273558-8fd48c5c-0ad5-42bf-b345-078a159ac9ce.png)
Try setting the launch options to fullscreen and window mode to borderless

**Comment by holden93274** [comment]
> ![изображение](https://user-images.githubusercontent.com/61908909/198273558-8fd48c5c-0ad5-42bf-b345-078a159ac9ce.png) Попробуйте установить параметры запуска на полноэкранный и оконный режим на без полей.

Where are these settings located ? ( it is desirable to paint )

**Comment by holden93274** [comment]
> ![image](https://user-images.githubusercontent.com/61908909/198273558-8fd48c5c-0ad5-42bf-b345-078a159ac9ce.png) Try setting the launch options to fullscreen and window mode to borderless

Where are these settings located ? ( it is desirable to paint )

**Comment by BlueStarBRS** [comment]
here i use this while my game is se to Window with my tool i make it borderless 
https://github.com/Codeusa/Borderless-Gaming/releases

**Comment by 34736384** [comment]
Uncheck fullscreen and use popup window instead
